### ISSUE TITLE
Introducing layout dialect in the core

### ISSUE THREAD

**Issue by heat** [thymeleaf/thymeleaf#131]
Hello
Recently, in a architecture design decision we decided to use:
JavaServlets and Thymeleaf.
I confess that I fell in love with thymeleaf.

We missed a way to do pages composition, or macro, and http://docs.zope.org/zope2/zope2book/ZPT.html#whole-page-macros .

I found a solution here https://github.com/ultraq/thymeleaf-layout-dialect . But my question is: have this feature in themyleaf?

It is very helpful and avoids problems of layout.

**Comment by danielfernandez** [comment]
Emanuel Rabina's _layout dialect_ is not a part of the thymeleaf core, but anyway it is a useful and stable piece of software. 

Besides, Emanuel is a member of the Thymeleaf development team (see http://www.thymeleaf.org/team.html), so you can be sure this dialect will implement high quality standards and a good integration with the official thymeleaf core.

**Comment by ultraq** [comment]
Now to live up to those high quality standards you talked about! :)

**Comment by manish-in-java** [comment]
I would suggest moving the Layout Dialect into the core.  First of all, it will avoid having an additional Maven dependency.  Then, I get freaky when I see different package names.  Having everything as part of the same library keeps things simple.  Next, having code in the same library ensures that upgrades can be performed smoothly and that version compatibility issues do not crop up.  Additionally, having a single library means a single license to deal with rather than potentially multiple licenses.  Finally, teams in many organisations have to go through software certification cycles.  Two different libraries means potentially two different certification cycles and delays in getting up and running with the software.  Before you say that this sounds ridiculous, I can assure you that I have worked in one such organisation and worked for 4 other clients where I had to face this problem.  In all cases it took a minimum of 3 months to get something certified for use within applications, not to mention the amount of business case documentation I had to produce to get the process going.

All in all, I would really like to see the Layout Dialect being merged into the core library as the downsides of not doing so are too many.
