### ISSUE TITLE
Node local variable can not be named "class"

### ISSUE THREAD

**Issue by java-artisan** [thymeleaf/thymeleaf#138]
Setting a local node variable with name "class" results in wrong markup:

Template markup:

<div class="accordion" th:classappend="${class}"/>

Renders in:
<div class="accordion class org.thymeleaf.context.VariablesMap">
....
</div>

**Comment by danielfernandez** [comment]
It seems github formatting made your code dissapear. Could you please rewrite your example code and result?

The following test executes successfully:

```
%CONTEXT
class = 'My class text'
# ------------------------------------------------------------
%INPUT
<p th:text="${class}">...</p>
<div th:with="class='My local class text'">
    <p th:text="${class}">Some text</p>
</div>
# ------------------------------------------------------------
%OUTPUT
<p>My class text</p>
<div>
    <p>My local class text</p>
</div>
```

And also does adding local variables to a node from an `IProcessor` returning `ProcessorResult.setLocalVariables(...)`

**Comment by danielfernandez** [comment]
I've done some changes to `Arguments`-`Node` synchronization of local variables in order to solve a side problem, but I don't think this could be related to an issue with variable names.

I've also created this test which includes a variable named `class`. It works OK: https://github.com/thymeleaf/thymeleaf-tests/blob/master/src/test/resources/dom/dom01.thtest

I'm closing this issue for now, in order to release 2.0.17. Please reopen it (or create a new one) should you encounter further problems.
