### ISSUE TITLE
StandardMessageResolver and encoding issue

### ISSUE THREAD

**Issue by WonderBeat** [thymeleaf/thymeleaf#139]
In current implementation, *.properties files with localization messages should be in ISO 8859-1 only.
This limitation prevents localization for some languages ;)

---

Problem is in `MessageResolutionUtils#loadMessages`.

``` java
 final Properties properties = new Properties();
        try {
            properties.load(propertiesIS);
        } catch (final Exception e) {
            throw new TemplateInputException("Exception loading messages file", e);
        }
```

`Properties#load` default encoding is **ISO 8859-1**.
Is it possible to read localization messages in **UTF-8**?
- I can submit patch if you do not mind

**Comment by danielfernandez** [comment]
The problem is Thymeleaf should be compatible with Java 5, and until Java 6 (when a `Properties.load(Reader)`) mehod appeared, the specification clearly required that every `.properties` file should be encoded in ISO-8859-1, and non ISO-8859-1 characters should be represented as unicode escapes.

Anyway, if your needs are other, you can write your own implementation of `IMessageResolver`.

**Comment by frenchfrie** [comment]
Hie there!
I'm having the same problem. I'm currently writing a copy of the standard resolver and all the static utility methods it needs. It creates a lot of code duplication that could be avoided if an encoding dependant message resolver was included in Thymeleaf itself.

Would it be possible to include such a class?

Thanks a lot
