### ISSUE TITLE
No "Repeat" method for Strings

### ISSUE THREAD

**Issue by t-oster** [thymeleaf/thymeleaf#152]
Hi,

I am using thymeleaf in my https://github.com/t-oster/VisiCut/pull/152 application to generate SVGs. However for complex paths, I need a String in an attribute repeated a number of times. like:

``` xml
<path
 th:attr="d=' m 10,20' + ${'3,0 0,5 6,0 0,-5 3,0'.repeat(5)}"/>
```

I could not find a way to do that. I would suggest extending the #strings Object with a method repeat(Object o, int number), which will just repeat the String number of times.

or am I missing something?

**Comment by peteruithoven** [comment]
I get why you want to do this, but next you also want to use i in the string for example. In the long some kind of  boolean operations (difference, union, intersection) would be better. I think it's easier to write and more dynamic. When you have this you can use basic paths to create shapes.

**Comment by t-oster** [comment]
Well... using i in the string is already possible. The boolean operations are SVG specific... even more, they are path specific. Since thymeleaf is originally targeted at XML and HTML, I don't think we should mix template logic with meaning of the underlying objects.
Thymeleaf already has many string operations present, but "repeat" seems just missing...

**Comment by danielfernandez** [comment]
Hi again Thomas,

I was examining your pull request in order to merge it, but I have a question... I see your implementation and this line:

``` java
new String(new char[times]).replace("\0", str);
```

...creates three objects: a char array and two Strings (one with `new`, another one as a result of `replace`). Of course there's also a `"\0"` String, but that is interned so it isn't really important. Then we all depend on how well the `replace` method is implemented for actually doing something like this...

Is there a reason why this implementation is better than the more common one based on a `StringBuilder` object, a `for` loop and a simple `strBuilder.append(...)`? 

``` java
final StringBuilder strBuilder = new StringBuilder();
for (int j = 0; j < times; j++) {
    strBuilder.append(str);
}
final String result = strBuilder.toString();
```

For me, the `replace` option seems slower (and less understandable)...

**Comment by t-oster** [comment]
I got it from here: http://stackoverflow.com/questions/1235179/simple-way-to-repeat-a-string-in-java . I am not sure if it is more efficient, I just thought it was less code ;). Feel free to use either way.

**Comment by danielfernandez** [comment]
`#strings.repeat(target,times)` been added to 2.1.0-SNAPSHOT. See the commit referenced above for an associated test.

@t-oster I finally decided to implement it the `StringBuilder` way... I read your link, and to be honest I don't share the poster's concerns about loops at all. I did some testing and the `StringBuilder` option seems to perform much better (besides being more readable), so I went for it. Thanks a lot, anyway!
