### ISSUE TITLE
Thymeleaf seems to be escaping the & character while rendering the th::href attribute and also adding a shape attribute (?)

### ISSUE THREAD

**Issue by ncrawl** [thymeleaf/thymeleaf#189]
I don't know if I am doing something wrong, but there seems to be a bug while rendering the th::href attribute using the @{...} syntax. 

```
<a th:href="@{/foo/bar(bug='y',ornot='f')}" href="#"></a>
```

The result I am getting is:

```
<a href="/foo/bar?bug=y&amp;ornot=f" shape="rect"></a>
```

It's escaping the '&' character and adding a shape attribute. 

Please! I really need a fix... I am using it everywhere. =(

**Comment by ncrawl** [comment]
So far, I am unable to render any URL with query strings - using the @{..} or not.
I tried to concatenate the strings myself into the template, but that didn't work also. The sax parser requires the & character to be followed by an entity name and a ;.

**Comment by jmiguelsamper** [comment]
Thymeleaf has its own syntax for URL parameters, look at
  http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#link-urls

**Comment by jmiguelsamper** [comment]
Escaping ampersand inside an attribute is correct HTML.

**Comment by danielfernandez** [comment]
@jmiguelsamper is right. Per XHTML specification, `&` symbols must be encoded as `&amp;` in tag attributes (like `href`). Your links are perfectly right and work OK. It's just that you are used to seeing them ill-formed ;-)

As for the `shape` attribute, that happens because you are using an XHTML template mode and therefore an XHTML DTD. As it happens, the `shape` attribute is mandatory in `<a>` tags (the DTD says so), so the only thing thymeleaf does there is add an attribute which should already be there (though nobody writes it), with its default value. So, again, your links are OK.

**Comment by ncrawl** [comment]
Wow, I was totally unaware of this behaviour. Thank you for the fast response!

Anyway, I have chosen XHTML to improve thymeleaf performance, forcing an XML compliant document. If I switch to HTML5, will I have any performance degradations?

**Comment by jmiguelsamper** [comment]
No, no there is performance impact in using HTML5.

The only modes with a little performance impact are the LEGACY modes, as the HTML must be tidier the first time the template is loaded.

**Comment by harikk** [comment]
@jmiguelsamper 

> Escaping ampersand inside an attribute is correct HTML.

If this is the case, how could I pass the following url?

http://example.com?id=20&somevar=content_with_&amp;rr=29

Here, I have only two parameters: id => 20 and somevar => `content_with_&amp;rr=29`

but according to the reply, it will have three parameters (id => 20, somevar => content_with_, rr =>29)

Also when I tried https://www.google.co.in/search?source=hp&amp;q=thymeleaf instead of https://www.google.co.in/search?source=hp&q=thymeleaf I got the wrong page.
So clearly, & is not same as &amp;  in urls.

So can you tell me how can I add & in urls with Thymeleaf?

**Comment by dopatraman** [comment]
why is this closed? clearly @harikk question has not been answered.

**Comment by danielfernandez** [comment]
@dopatraman this issue was closed in 2013. And @harikk's question was posted on a 3-yr-old closed ticket in 2016, after what he opened a new ticket, #456, which was sufficiently answered IMHO.

Regards.
