### ISSUE TITLE
Inline text not happening before tag removal

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf#198]
From this forum thread: http://forum.thymeleaf.org/Order-of-processing-th-attributes-tp4026551.html

The OP has some inline text (`th:text` and an inline text expression `[[${...}]]`) that's expected to be processed before the `th:remove="tag"`, but the result is as if the `th:remove` happened first.

I was able to reproduce it using Thymeleaf 2.0.17.

Also, when this is fixed, we might want to update the documentation to show where inline text processing occurs in the order of things.  Right now it shares roughly the same precedence value as other text processors.

**Comment by danielfernandez** [comment]
Yup. This was a bug. The flags that determine whether `Text` or `Comment` nodes had to be processed at all were stored at the `Arguments` object, which meant they only propagated from father to children nodes.

The problem is, when a `th:remove="tag"` was executed, there was no propagation because the children nodes of the host tag turned into brothers after the host tag was removed, and this meant the value of the above mentioned flag never propagated correctly for them.

I have changed those flags to live at the `Node` class, and not at `Arguments`.

Associated tests:
- https://github.com/thymeleaf/thymeleaf-tests/blob/20130811/src/test-common/resources/engine/attrprocessors/inline/inline08.thtest
- https://github.com/thymeleaf/thymeleaf-tests/blob/20130811/src/test-common/resources/engine/attrprocessors/inline/inline09.thtest

Already updated both 2.0.18-SNAPSHOT and 2.1.0-SNAPSHOT.
