### ISSUE TITLE
Include fragment in the same template

### ISSUE THREAD

**Issue by emilime** [thymeleaf/thymeleaf#2]
Add the ability to define a fragment in a page and use the fragment later in the same page that defines it.
Useful to reuse the same pagination toolbar or for representing trees or data structures which depth is not known beforehand.

**Comment by huxi** [comment]
Any news on this? This, and recursive templates, would be really helpful.

**Comment by mindhaq** [comment]
+1

**Comment by emilime** [comment]
no news about recursive templates? it's the only thing I miss with Tymeleaf...

**Comment by danielfernandez** [comment]
Yup, this has been included in the thymeleaf 2.1 backlog.

**Comment by danielfernandez** [comment]
2.1-SNAPSHOT now allows including fragments from the same template. There are two available syntaxes: one specifying no template name:

``` html
<div th:include="::fragment_name">...</div>
```

...and another one specifying the keyword `this`:

``` html
<div th:include="this :: fragment_name">...</div>
```

See associated example tests:
- https://github.com/thymeleaf/thymeleaf-tests/blob/20130702/src/test-21/resources/engine21/attrprocessors/include/include01.thtest
- https://github.com/thymeleaf/thymeleaf-tests/blob/20130702/src/test-21/resources/engine21/attrprocessors/include/include03.thtest

By the way, @emilime, it seems I misunderstood your question and for some reason thought you were asking for same-template fragments. Recursive templates are allowed since long ago in 2.0.x. See this test: https://github.com/thymeleaf/thymeleaf-tests/blob/20130702/src/test-common/resources/engine/attrprocessors/include/include13.thtest

**Comment by emilime** [comment]
yes I was asking for recursive templates and I had not realized was included in 2.0.x!
I'll test it as soon as possible, thanks.

**Comment by huxi** [comment]
Awesome! Thanks a lot!

**Comment by bubuzzz** [comment]
Just awesome !! your example is exactly what I need. Thank you very much

**Comment by flyasky** [comment]
add this to documentation about fragments&layouts, please
