### ISSUE TITLE
Rename classes and interfaces.

### ISSUE THREAD

**Issue by AlexCzar** [thymeleaf/thymeleaf#215]
Call me crazy but I think this is one of the must-be-done features. I know it will be a small period of tough time while all the existing developers catch up and transfer, but it will ensure new developers wont turn the framework down due to this design horribleness (pardon my "French").
To the point: Interface name should not ever have `I` in front of the name! E.g.
`IWebContext` is just horrible and promotes users to use implementation class when declaring a variable of the type. In IoC days with so many developers using Spring and JEE having `I` in the interface name is the worst thing to do with naming of things.
So, in case of `IWebContext` interface and `WebContext` class there should be a renaming like this: `WebContext` becomes the name of the interface and `DefaultWebContext` (or something like that) for the class. The same should be done for all the `I{Name}` interfaces.
Please, forgive the harsh tone of this post, but seeing `ISomething`s make my eyes water and politeness switch fails in my brain.
Read this: http://stackoverflow.com/questions/541912/interface-naming-in-java
This: 
And this discussion http://stackoverflow.com/questions/541912/interface-naming-in-java

All these people have more points and are expressing them better than I do.

**Comment by jmiguelsamper** [comment]
Although I don't follow the I-prefix convention, I wouldn't call it "design horribleness", it's just a naming convention, which it's not so important, even not important at all. Having worked with many different teams, I tend to adapt myself to the group conventions instead of trying to change them.

**Comment by danielfernandez** [comment]
@AlexCzar I understand your point. Your position is very common and poses many benefits, though also some drawbacks and, in the end, it's just a matter of choosing a naming option. As far as I know, there is at least an example of another popular Java framework using this syntax: Apache Wicket

I chose the `I+name` naming scheme for interfaces specifically to signal they are possible extension or configuration points. Obviously I understand this goes against the reasoning that _"a context is a context, and I should not matter whether it is an interface of a class_, but I think this _intrusion_ into the semantic dimension of code pays its price in code readability and, especially, API learning curve.

Also, if you think of it, the `I`-thing is not really worse than starting abstract classes with `Abstract*` (and there are dozens of classes in the Java SE API starting with `Abstract`), or even --though I admit it's not exactly the same-- finishing classes with `*Service`, `*Repository`, etc. just because they have no state --and thus are no entities-- but have a very specific function in applications  modelled using the _Transactional Script_ pattern.

But anyway, as I said... it's just a matter of choosing an option and getting used to it. I appreciate your opinion.
