### ISSUE TITLE
Reflection w/ Google App Engine and Thymeleaf 2.1

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf#242]
From the forums: http://forum.thymeleaf.org/Google-App-Engine-error-Thymeleaf-2-1-td4027046.html

Running Thymeleaf 2.1 in Google App Engine leads to errors when it comes to using reflection.  The OP then found that this wasn't a problem in Thymeleaf 2.0.19, so something happened between 2.0 and 2.1 that is causing this.

Stack trace shows that `org.thymeleaf.context.OGNLVariablesMapPropertyAccessor` is involved (is this a purely OGNL thing, or does it get used in Spring too?).

[EDIT]: reply on forum thread - they're using Spring.

**Comment by danielfernandez** [comment]
Might be related to #235

**Comment by danielfernandez** [comment]
This couldn't be reproduced. A similar scenario was tested using Google App Engine SDK 1.8.7 and 1.8.8, both using the Dev server and the Google Cloud server. Everything worked OK.

The lines of code provoking this issue seem to be https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-2.1.1.RELEASE/src/main/java/org/thymeleaf/context/VariablesMap.java#L58-L65, where a default-visibility constructor is executed using `newInstance()`. However, code is fine, and in fact seems to work OK in GAE for us.

Anyway, just in case, the initialization code for `OGNLVariablesMapPropertyAccessor` has been modified in 2.1.2-SNAPSHOT to remove reflection code, so that the possibilities of exceptions in restricted environments like Google App Engine are reduced.
