### ISSUE TITLE
th:block not working properly in document head

### ISSUE THREAD

**Issue by ghost** [thymeleaf/thymeleaf#246]
Using org.thymeleaf.spring3.SpringTemplateEngine and template mode LEGACYHTML5, th:block is not behaving as expected. For example: 

``` xml
<th:block th:if="${false}">
    <script type="text/javascript">//I should not appear.</script>
</th:block>
<!--/*/ <th:block th:if="${false}"> /*/-->
    <script type="text/javascript">//I should not appear.</script>
<!--/*/ </th:block> /*/-->
<th:block th:unless="${true}">
    <script type="text/javascript">//I should not appear.</script>  
</th:block>
<!--/*/  <th:block th:unless="${true}"> /*/-->
    <script type="text/javascript">//I should not appear.</script>
<!--/*/ </th:block> /*/-->
```

renders as

``` html
<script type="text/javascript">//I should not appear.</script>

<script type="text/javascript">//I should not appear.</script>

<script type="text/javascript">//I should not appear.</script>  

<script type="text/javascript">//I should not appear.</script>
```

Also th:each in th:block does not render in head tag as expected. In document body th:block behaves as expected.

**Comment by danielfernandez** [comment]
This has been verified. Apparently, when using the `LEGACYHTML5` template mode, nekoHTML (executed prior to the thymeleaf parsers) is performing an inconvenient tag balancing operation, closing the `<th:block>` when it encounters the `<script>` tag, like:

``` html
<th:block th:if="${false}">
    </th:block><script type="text/javascript">//I should not appear.</script>
```

...which basically provokes the `<th:block>` to execute OK, but not do anything.

In order to solve this, it would be necessary to somehow instruct nekoHTML not to perform tag balancing operations specifically involving `<th:block>`. I'm not sure whether this is possible or not...

The obvious workaround is writing XML-well-formed markup and not using the `LEGACYHTML5` template mode in this scenario, but `HTML5` instead.

**Comment by ghost** [comment]
Daniel, many thanks for analyzing this issue. We'll discuss to switch to an XML syntax variant and the respective parser. By now we tried to avoid it for its 'verbosity'.

**Comment by danielfernandez** [comment]
The `LEGACYHTML5` template mode has dissapeared from Thymeleaf 3.0 and no tag balancing operations are being performed on template markup anymore, so this is no longer an issue. See #390 

Already in `3.0.0-SNAPSHOT`
