### ISSUE TITLE
Add CDN support for LinkExpression

### ISSUE THREAD

**Issue by dimw** [thymeleaf/thymeleaf#247]
The Link URL Expression `@{...}` should be enhanced in order to allow to relink existing resources to a CDN. As analogy to the server-relative URLs, this could be done by adding a certain static prefix before the resource address: 

```
@{+/link/to/file.txt}
```

(which is suitable for a single-domain CDN) or defining a certain specific dummy protocols:

```
@{mycdn1://link/to/file.txt}
@{mycdn2://link/to/file.txt}
```

The latter, if explicitly defined, should be evaluated to something like:

```
http://cdn.primary.net/link/to/file.txt
http://cdn.secondary.net/link/to/file.txt
```

**Comment by danielfernandez** [comment]
Our current position on this is that these URL tuning operations should be performed outside thymeleaf, by means of URL rewriting filters such as http://tuckey.org/urlrewrite/ (which we recommend). This is so because the rules that match URLs to CDNs might be complex, and they clearly fall into the category of _application configuration_, not _view layer configuration_. A specialized tool (like an URL rewriting filter) can therefore do a better job here.

In order to allow this, thymeleaf calls the `response.encodeURL(...)` method in `javax.servlet.http.HttpServletResponse` for each URL it generates with `@{...}` expressions, and this method acts as an extension point where URL rewriting filters execute, modifying --if needed-- any output URLs.

**Comment by refacktor** [comment]
does anybody have a working example of how to do this by overriding HttpServletResponse.encodeURL()?

**Comment by dallaslu** [comment]
> 
> 
> does anybody have a working example of how to do this by overriding HttpServletResponse.encodeURL()?

```Java
@Component
public class CdnUrlWebFilter extends OncePerRequestFilter {
	@Override
	protected void doFilterInternal(HttpServletRequest request, 
			HttpServletResponse response, FilterChain filterChain)
			throws ServletException, IOException {
		HttpServletResponseWrapper wrapper 
			= new HttpServletResponseWrapper(response) {
			@Override
			public String encodeURL(String url) {
				if (url.startsWith("/assets")) {
					url = "https://cdn.com" + url;
				}
				return super.encodeURL(url);
			}
		};
		filterChain.doFilter(request, wrapper);
	}
}
```
