### ISSUE TITLE
Make ICache more accessible (keySet etc)

### ISSUE THREAD

**Issue by Antibrumm** [thymeleaf/thymeleaf#258]
It would be nice to have more accessors on the ICache interface. In particular getting all keys would be good to have in my situation (thymeleaf-cache-dialect).

Currently i have to use reflection to get all the keys in the cache. 

Having this accessor it would allow implementing cache eviction based on startsWith, regex and so one.

**Comment by danielfernandez** [comment]
This `keySet()` method should not be added to the `ICache` interface (at least not in 2.1) because it would break the existing interface and therefore code compatibility. However, if you assume you can do a cast to the `StandardCache` class (the standard implementation), it could be added there.

However, note that this `keySet()` method would have a drawback: it would return to you all the names of the cache entries, but it might happen that these cache entries contain values that are no longer valid, because they might have already expired.

As you can see here: https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-2.1.2.RELEASE/src/main/java/org/thymeleaf/cache/StandardCache.java#L177-L178 every cache entry, once retrieved, is checked for validness. This validness might be determined by anything, not only time (it is implemented by the `ICacheEntryValidityChecker` interface).

So you'd end up with a list of cache entry names for each of which you'd still have to manually determine whether they are still valid or not (if such thing is relevant to you)...

Would this still be useful?

**Comment by Antibrumm** [comment]
Basically I'd like to clean the evictByStartsWith method in the thymeleaf-extras-cache-dialect. For this I need to be able to get all cache keys to iterate over it.
Currently I have to get a reference to the cache container map to be able to get this info: 

```
@SuppressWarnings("unchecked")
private Map<String, List<Node>> initializeCacheContainerReference(StandardCache<String, List<Node>> cache) {
    try {
        Field fieldCacheDataContainer = cache.getClass().getDeclaredField("dataContainer");
        fieldCacheDataContainer.setAccessible(true);
        Object cacheDataContainer = fieldCacheDataContainer.get(cache);
        Field fieldContainer = cacheDataContainer.getClass().getDeclaredField("container");
        fieldContainer.setAccessible(true);
        Object containerConcurrentMap = fieldContainer.get(cacheDataContainer);
        return (Map<String, List<Node>>) containerConcurrentMap;
    } catch (Exception e) {
        log.warn("Could not access ConcurrentHashMap of StandardCache. evictByStartsWith will not work!", e);
    }
    return null;
}

public void evictByStartsWith(final String cacheName) {
    Map<String, List<Node>> cacheContainerReference = getCacheContainerReference();
    if (cacheContainerReference == null) {
        return;
    }
    for (String key : cacheContainerReference.keySet()) {
        if (key.startsWith(cacheName)) {
            getCache().clearKey(key);
        }
    }
}
```

I use the ValidityChecker already for the TTL eviction feature in the dialect.
Do you mean that instead of going to the cache and remove the entry, another possibility could be to use a ValidityChecker and flag it as Invalid? I would have to check the code, but this means that I need to keep a reference to the ValidityChecker and manage this removal also, right?

**Comment by danielfernandez** [comment]
A `keySet()` method has just been added to `StandardCache`. It will not be added to the `ICache` interface until Thymeleaf 3.0 (see #306), but for the moment you can cast your objects to `StandardCache` (the implementation class they most probably are instances of) and call it.

**Comment by danielfernandez** [comment]
Updated 2.1.4-SNAPSHOT

**Comment by Antibrumm** [comment]
Thanks Daniel, i will try it out soon.

**Comment by danielfernandez** [comment]
Thymeleaf 2.1.4 has just been published, including this improvement.
