### ISSUE TITLE
Limitation in externalized text containing links

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#260]
Reference: http://forum.thymeleaf.org/Correct-way-to-localize-text-containing-links-td4027464.html

This is related to the fact that, in Spring-enabled environments, the `RequestDataValueProcessor#processUrl(...)` method is applied not on the `@{...}` expression itself, but on the `th:href` attribute processor as explained at https://github.com/thymeleaf/thymeleaf-spring3/issues/7#issuecomment-27643488. This is done so in imitation of what is being done at Spring's JSP TagLibs.

However, possible workarounds for this scenario could involve thymeleaf's core instead of only the Spring integration module. So this ticket is open here instead of the Spring module.

This ticket is intended to discuss possible approaches to this problem.

**Comment by danielfernandez** [comment]
**Approach 1**: create a new attribute, for example `th:eval`, that would work exactly like `th:utext` but allowing code inside, this is, not including the results of evaluating its expression as a `Macro`, but rather as a subtree of DOM nodes, which would be subsequently executed as a part of the template (like `th:include` does).

This should allow users to include `th:href` attributes inside externalized text entries (e.g. `Messages.properties`) and therefore allow the execution of artifacts like `RequestDataValueProcessor`.

Given the similarities of the described feature with the _standard fragment inclusion mechanism_ -----though not retrieving such fragments from another template--, a valid alternative name for this attribute could be `th:includetext`.

**Comment by cm-rudolph** [comment]
I think `th:includetext` (or an abbreviated form like `th:itext`) would be a good solution, because there is definitely the need for an "intelligent" solution to handle the referenced case.
For example, it might be needed to escape some characters with respect to their occurence (whether they are inside a tags attribute or just content, e. g. when repeating the `href` as content of the `a` tag).

I think `th:includetext` / `th:itext` would be a better name than `th:eval`, because it is related to `th:text`, with slightly modified behaviour. This relationship is expressed through the suffix `text`.

**Comment by danielfernandez** [comment]
I'm moving this to the Thymeleaf 3.0 milestone, as it is now covered by #307 and #308.

**Comment by danielfernandez** [comment]
This scenario is solved in Thymeleaf 3.0 by means of the `#requestdatavalues` expression object detailed at thymeleaf/thymeleaf-spring#97
