### ISSUE TITLE
Adjust app context path for @{} expressions

### ISSUE THREAD

**Issue by kaanozdokmeci** [thymeleaf/thymeleaf#272]
Hello, currently you can specify the following:
-Context relative urls
-Server relative urls
-Absolute urls
-Protocol relative urls

While developing, we generally run our applications on localhost. But deployed apps run behind a reverse proxy.

context root for the app: my-app
expression: @{/login}
localhost url: /my-app/login
deployed url: /login

so, as a feature, would you please consider adjusting the context root of the application for thymeleaf? (take it from servletcontext if not specified, omit if specified as empty/null)
so that devs would be able to configure their test/deployment scripts while using a single link style in the @{} expressions.

Note: I would also be glad if you could point out a current workaround for the problem?

**Comment by ultraq** [comment]
I also work behind a reverse proxy to redirect domains to apps, so one method I use to get around those paths is to set the `<base>` tag in my HTML, eg:

``` html
<base href="http://mydomain.com/" th:href="${siteURL}"/>
```

(The HTML5 spec for the `<base>` element: http://www.whatwg.org/specs/web-apps/current-work/multipage/semantics.html#the-base-element)

`siteURL` is set from an environment property so that on my dev machine/s it can stay `http://localhost:8080/servlet-context/` and on live/testing environments it can be the live/test URL.

**Comment by danielfernandez** [comment]
Hmmm... the preferred configuration here is setting up _URL rewriting_, so that URLs are rewritten in a manner completely transparent to thymeleaf or even the MVC technology of choice. This can be done by means of the `HttpServletResponse.encodeURL(...)` method in the Servlet API, an extension point that Thymeleaf honors.

Then the transformations applied can of course be configured differently depending on the deployment scenario. One of my favourite technologies for this is **UrlRewriteFilter** http://tuckey.org/urlrewrite/

Also, maybe you can achieve some degree of useful URL rewriting too by means of combining reverse proxying and _mod_rewrite_ at your Apache HTTPd (or the equivalents in your web server of choice, if not Apache HTTPd).
