### ISSUE TITLE
Rendering of Java Date objects breaks JavaScript inlining

### ISSUE THREAD

**Issue by cwong15** [thymeleaf/thymeleaf#290]
Forum post here:

http://forum.thymeleaf.org/Inline-JavaScript-rendering-of-Java-dates-syntax-error-td4027910.html

Release 2.1.3 added the method StandardJavaScriptTextInliner.printDate to fix issue #121. Unfortunately, this results in invalid JavaScript when we try to inline any object that contains a Java Date property, because it gets converted into a human-readable string instead of a valid JS expression. That is, if I have an object myFoo with a createdDate property of type GregorianCalendar (which has 2 Date properties), the following Thymeleaf construct:

<script th:inline="javascript" type="text/javascript">
    var foo = /*[[${myFoo}]]*/
</script>

Will output the following value for the createdDate property. The "gregorianChange" and "time" properties get values that fail to parse asJavaScript.

'createdDate': { 
        'firstDayOfWeek': 1, 
        'gregorianChange': Thu Oct 04 19: 00: 00 EST 1582, 
        'lenient': false, 
        'minimalDaysInFirstWeek': 1, 
        'time': Tue Apr 22 16: 22: 21 EDT 2014, 
        'timeInMillis': 1398198141020, 
        'timeZone': { 
            'DSTSavings': 3600000, 
            'ID': 'America/New_York', 
            'dirty': false, 
            'displayName': 'Eastern Standard Time', 
            'lastRuleInstance': { 
                'DSTSavings': 3600000, 
                'ID': 'America/New_York', 
                'displayName': 'Eastern Standard Time', 
                'rawOffset': -18000000 
            }, 
            'rawOffset': -18000000 
        }, 
        'weekDateSupported': true, 
        'weekYear': 2014, 
        'weeksInWeekYear': 52 
    }

**Comment by cwong15** [comment]
Sorry, the following got swallowed by the editor. This is the Thymeleaf construct that generates the above text:

<pre>
&lt;script th:inline="javascript" type="text/javascript">
    var foo = /*[[${myFoo}]]*/
&lt;/script>
</pre>

**Comment by jmiguelsamper** [comment]
In order to make the Javascript object creation work, we could display dates as:

```
    new Date(12345678)
```

where the number inside is the time in milliseconds date.getTime()

Or, if we want a more readable output

```
   new Date("2011-10-05T14:48:00.000Z")
```

with the date inside following the format YYYY-MM-DDTHH:mm:ss.sssZ specified in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString

**Comment by danielfernandez** [comment]
The date being output is not being surrounded by single quotes :-(:-(

All "simple" objects are being output as string literals, and the aim of this change was to convert `java.sql.Date` and `java.util.Date` in such directly-convertible objects so that introspection was avoided, so the:

```
new Date("2011-10-05T14:48:00.000Z")
```

...wouldn't be completely adequate IMHO, because it would output the `Date` as an object instead of a literal.

I think it would be better to just use the ISO-formatted literal:

```
'2011-10-05T14:48:00.000Z'
```

...and then just let the user decide whether he/she wants to use that literal for creating a javascript `Date` object or not.

**Comment by danielfernandez** [comment]
For the record: section **15.9.1.15 Date Time String Format** of the ECMAScript specification, version 5, states that:

_ECMAScript defines a string interchange format for date-times based upon a simplification of the ISO 8601 Extended Format. The format is as follows: **YYYY-MM-DDTHH:mm:ss.sssZ**_

Of special interest is the meaning of **Z**, which is defined as:

_Z is the time zone offset specified as `Z` (for UTC) or either `+` or `-` followed by a time expression `HH:mm`_

So this would be a valid rendering for a `Date` object in our JavaScript inlining:

```
2014-05-17T01:48:36.449+02:00
```

**Comment by danielfernandez** [comment]
More info: the pattern that would produce an ECMAScript-valid date literal using a `java.text.SimpleDateFormat` object would be:

```
yyyy-MM-dd'T'HH:mm:ss.SSSXXX
```

But unfortunately the `X` pattern, defined as _ISO 8601 time zone_ at http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html was only added in Java SE 7. So a different solution should be evaluated.

**Comment by danielfernandez** [comment]
Updated 2.1.4-SNAPSHOT

**Comment by danielfernandez** [comment]
Thymeleaf 2.1.4 has just been published, including this fix.
