### ISSUE TITLE
th:replace and th:include behave differently

### ISSUE THREAD

**Issue by danielplappert** [thymeleaf/thymeleaf#295]
While working with <b>th:replace</b> and <b>th:include</b> I found out that these tags behave differently.
Let's say I've a fragment for displaying messages. This message should be displayed only under a given condition. 

Fragment: 

<pre>
&lt;div class="message" th:fragment="info-message (message)"&gt;
    &lt;p th:text="${message}" class="some-other-style-class" /&gt;
&lt;/div&gt;
</pre>

... my other html file, where I want to include this fragment: 

<pre>
&lt;div th:include"../fragments/basics :: info-message (message='Hello World')" 
    th:if="${condition}" /&gt;
</pre>

The problem now is that the class attribute "message" of my fragment will be removed because the div tag, which includes this fragment, will be kept. Therefore I used th:replace instead: 

<pre>
&lt;div th:replace"../fragments/basics :: info-message (message='Hello World')"
    th:if="${condition}" /&gt;
</pre>

Now I've the problem that <b>th:if will not be evaluated</b>, because the tag will be replaced completely before evaluating other attributes.  

I find this behavior inconsistent because, in my opinion, the th:if attribute has to be evaluated before th:include or th:replace are processed. It makes no sense to include or replace a fragment if the condition evaluates to false.

**Comment by danielfernandez** [comment]
The way it is now, attribute precedence works like this:
- 1st: Fragment inclusion: `th:replace`, `th:include`
- 2nd: Iteration: `th:each`
- 3rd: Conditional evaluation and rendering: `th:if`, `th:unless`
- (others)

I think it is important that we keep Conditional rendering **after** iteration, so that we can decide whether a block must be evaluated or not for each element of the iterated collection. But I'm unsure right now whether moving fragment inclusion to a position after conditional evaluation would have immediate drawbacks. At first thought, it might even seem that being able to include fragments iteratively would be a nice feature...

This is something to think of for 3.0 (we shouldn't change such a core behaviour in 2.1), and it might even be possible that this becomes completely invalid given we will be re-thinking the way fragment inclusion works (see #176) in order to make it more simple to understand...

**Comment by danielfernandez** [comment]
These precedences have been left untouched in Thymeleaf 3.0. Conditional evaluation must come after iteration in order to be able to determine if a block has to be shown or not _per iteration_, i.e. depending on the iterated variable. This is a quite common scenario.

Also, iteration has to come _after_ fragment inclusion because doing otherwise would mean executing fragment inclusion (a potentially complex operation, involving all layers of the library from the parser) once per iterated element, potentially thousands of times.

I'm closing this as declined, therefore.
