### ISSUE TITLE
Not implemented specific cache

### ISSUE THREAD

**Issue by vitornp** [thymeleaf/thymeleaf#296]
Method getSpecificCache is not implemented in https://github.com/thymeleaf/thymeleaf/blob/2.1-master/src/main/java/org/thymeleaf/cache/AbstractCacheManager.java#L120

**Comment by danielfernandez** [comment]
Those _specific cache_ methods are intended for override, that's why they return `null` (or empty). 

I suppose that you mean that `AbstractCacheManager` does not provide a map for storing and retrieving specific caches at the will of the user, and that's because neither it nor its default implementation `StandardCacheManager` are meant to have any specific caches (note they only have _getters_ for such specific implementations, not _setters_. They simply allow custom implementations to have them...

I see nonetheless some advantages in the standard cache implementation offering storage for _specific_ cache implementations, so I'm adding this as a feature improvement for the 3.0 milestone.

**Comment by danielfernandez** [comment]
After evaluation, providing some kind of standard configuration for specific caches that allow their creation and use only by calling `getSpecificCache()` has proven to be very prone to configuration issues and even memory leaks.

Each configured cache has to provide default and maximum sizes, as well as a _validity_ policy, in order to work correctly and make sure it doesn't grow above its limit (or even indefinitely). But the `getSpecificCache(name)` method is definitely too small an interface for provoking the _creation_ of new caches on the fly --which would have to use some kind of default configuration--, and this could lead to important memory and performance issues. It's definitely better to have users customize their own cache manager and implement the specific caches they might need --- perhaps by using the already-provided `StandardCache` implementation of `ICache`.

The documentation of the related methods in `ICacheManager` has been improved in order to better explain this.

Closing this as _declined_.
