### ISSUE TITLE
Text is double escaped in Thymeleaf 2.1.3

### ISSUE THREAD

**Issue by jamesagnew** [thymeleaf/thymeleaf#298]
I have a template with the following (spaces added to prevent the pre tag from actually rendering):
< pre th:text="${requestBody}" >< /pre >

..where the ${requestBody} contains raw HTML that is displayed in a PRE block. In Thymeleaf 2.1.2 the HTML is correctly escaped (< becomes &amp;lt; etc...) but in Thymeleaf 2.1.3 the HTML is double escaped ( < becomes &amp;lt;lt; ).

(This is my first issue on this project, it is great work!)

**Comment by jmiguelsamper** [comment]
Hello,

I have just tested it and the escaping on Thymeleaf 2.1.3 works OK, maybe you should double check your code.

Regards,
   Zemi

**Comment by danielfernandez** [comment]
Actually, Thymeleaf 2.1.2 was doing HTML escaping wrong, and 2.1.3 fixed this. See https://github.com/thymeleaf/thymeleaf/issues/255#issuecomment-42370355

Your `requestBody` variable probably comes already HTML-escaped, and `th:text` simply escapes it again. Please, double-check this. This wasn't happening to you before because 2.1.2 wasn't correctly escaping `&lt;` into `&amp;lt;`, but leaving it as `&lt;` giving you the wrong impression that it was escaping OK when it was actually not doing it.

If you confirm that your `requestBody` variable is already HTML-escape, you can write it without Thymeleaf escaping it again using `th:utext` instead of `th:text`

**Comment by jamesagnew** [comment]
You are completely correct, my apologies. I should have paid closer attention to my own code. :)
