### ISSUE TITLE
'font-family' name's quotes are no longer escaped,

### ISSUE THREAD

**Issue by ktsunoda** [thymeleaf/thymeleaf#322]
When I use version 2.1.3.RELEASE for org.thymeleaf - thymeleaf, email created gets formatted incorrectly due to the font name not being escaped anymore. It works with 2.1.2.RELEASE.

From version 2.1.2.RELEASE (maven):

```
<groupId>org.thymeleaf</groupId>
<artifactId>thymeleaf</artifactId>
<version>2.1.2.RELEASE</version>
```

```
<td class=3D"kmTextContent" valign=3D"top" style=3D"border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; color: #585858; font-family: &quot;Helvetica Neue&quot;, Arial; font-size: 14px; line-height: 150%; text-align: left" rowspan=3D"1" colspan=3D"1"></td>
```

Notice the "&quot;"s surrounding "Helvetica Neue" in the above version, but not in the below version. Both are generated using Thymeleaf.

From version 2.1.3.RELEASE (Maven):

```
<groupId>org.thymeleaf</groupId>
<artifactId>thymeleaf</artifactId>
<version>2.1.3.RELEASE</version>
```

```
<td class=3D"kmTextContent" valign=3D"top" style=3D"border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; color: #585858; font-family: "Helvetica Neue", Arial; font-size: 14px; line-height: 150%; text-align: left" rowspan=3D"1" colspan=3D"1"></td>
```

**Comment by danielfernandez** [comment]
What is the thymeleaf code that generates the value for your `style` attribute?

**Comment by ktsunoda** [comment]
```
<td class="kmTextContent" valign="top" style='border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; color: #585858; font-family: "Helvetica Neue", Arial; font-size: 14px; line-height: 150%; text-align: left'></td>
```

It's just part of the HTML template that I have. I run that through the template engine from Spring-Thymeleaf library.

**Comment by danielfernandez** [comment]
OK, so you are not using `th:style`, which means that thymeleaf 2.1.3 is just leaving your attribute value as was in the original template, unchanged. Modifying the values of unprocessed attributes in order to add escaping codes that did not exist in the original code was actually a sort of bug in versions previous to 2.1.3.

However, the problem for you here is that thymeleaf 2.1 does not support outputting attributes with single quotes, so you have a problem with your single-quoted attribute that contains double quotes.

Single-quoted attributes will be supported in thymeleaf 3, but unfortunately there is no way to do that in v2.x. Your easiest workaround is modify your attribute switching single and double quotes:

```
<td class="kmTextContent" valign="top" style="border-collapse: collapse; mso-table-lspace: 0; mso-table-rspace: 0; color: #585858; font-family: 'Helvetica Neue', Arial; font-size: 14px; line-height: 150%; text-align: left"></td>
```

**Comment by ktsunoda** [comment]
Awesome. Thank you very much for such a quick turnaround!
