### ISSUE TITLE
Include non-HTML files

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf#325]
I have a JavaScript configuration for RequireJS that is managed in an upstream project, packaged in a jar, and served from a Spring classpath resource. I would like to be able to include the contents of a `config.js` file immediately (preferably with inlining evaluation) instead of requiring a separate round-trip for it, something like

```
<script data-th-inline="config.js"></script>
```

**Comment by danielfernandez** [comment]
As a workaround, maybe you can configure a separate template resolver for your non-HTML files --one that wouldn't add an `.html` suffix, for example-- and then just configure the `resolvablePatterns` property in your template resolvers so that you make sure it's this non-HTML resolver the one that runs when you ask for your `config.js` file.

The _issue_ you might encounter with this is that Thymeleaf will try to parse your `.js` file as if it were HTML, so you will need to surround your JavaScript code with `<![CDATA[...]]>` so that it doesn't try to do parse anything there...

Template modes and inclusion mechanisms will change for 3.0, so I'm adding this to the 3.0 milestone in order to make sure that a better alternative can be offered in 3.0.

**Comment by chrylis** [comment]
My current planned workaround is to just slap `<script>` tags with the necessary spells around the JS file during a build step and then include that as a fragment.

**Comment by danielfernandez** [comment]
A new mechanism has just been implemented into Thymeleaf 3.0 that allows _cross-template-mode_ fragment insertion, i.e. insertion of fragments that use a template mode different to the one used by the including template.

This, together with the new template mode system explained in #391 allows the implementation of the scenario explained in this ticket and any others which may involve the insertion of CSS, JavaScript or other format (text) files by processing them (including the use of the inlining mechanisms) and then including their result into the main template being processed.

Note also that these included JavaScript, CSS or Text files will be processed using the _also-new_ textual syntax (see #395) and will be applied the refactored and improved inlining mechanism (see #396).

For a quick example of this _cross-template-mode_ fragment insertion, see this test: https://github.com/thymeleaf/thymeleaf-tests/blob/e45dc5807febddbfc4e66547e883848600472d86/src/test/resources/templateengine/attrprocessors/insert/insert56.thtest

This has already been included in `3.0.0-SNAPSHOT`

**Comment by nishanta454** [comment]
Can we include text file in thymeleaf html file / template?

**Comment by chrylis** [comment]
Eagerly looking forward to the 3.0 series!
