### ISSUE TITLE
Make "absent message representation" customizable

### ISSUE THREAD

**Issue by magat** [thymeleaf/thymeleaf#328]
The webapp I'm working on provides internationalization to its users by letting them set the translations in a dedicated page. 

When there is no translation provided, I'd like to customize the message displayed, instead of the Thymeleaf representation (??code.locale??)

I have identified the MessageResolutionUtils.getAbsentMessageRepresentation(final String messageKey, final Locale locale) method, but this method and its caller are both static. 

From there I'm not sure how should I go in overriding this behaviour ?

As an everyday Thymeleaf user, I'm willing to write and contribute code to the project if you could point me in the right direction.

**Comment by danielfernandez** [comment]
This has been just implemented into Thymeleaf 3.0 as a part of a major refactoring for the Message Resolution API (see #421), needed in order to support other required modifications on the Template Resolution API (#419) and Context API (#420).

Many thanks for your contributed PR and sorry for the delay, but unfortunately a series of changes in the architecture meant we had to go for a complete refactoring of the Message Resolution API for 3.0 instead of applying the changes you designed.

**Comment by magat** [comment]
Thank you for your answer, I'm looking forward to Thymeleaf 3.0 !
