### ISSUE TITLE
Cache a specific ITemplateResolver result with another key

### ISSUE THREAD

**Issue by delgurth** [thymeleaf/thymeleaf#329]
I was looking at issue #300 for a feature we are trying to realise.

We have a template resolver that changes the location where to search for the template name based on information in the HTTP request, a bit like issue #300, but with different conditions. But now I was looking at the [org.thymeleaf.TemplateRepository#getTemplate method](https://github.com/thymeleaf/thymeleaf/blob/2.1-master/src/main/java/org/thymeleaf/TemplateRepository.java#L191). The cache seems to be using only the getTemplateName() from the TemplateProcessingParameters to determine whether or not to return the cached version. 

So yes, you can add your custom ITemplateResolver implementation, but that would either result in undesirable results when you enable caching (since the getTemplateName() will be the same for the different devices as per example of #300), or bad performance since the template will be parsed on every request. 

To enable caching in this situation you will need to be able to use a different key. Perhaps something based on the TemplateResolution getResourceName(), or saver a new method within the TemplateResolution class?

I was first thinking about using the ITemplateResolutionValidity for this, but that won't work since the cache key is still the not unique getTemplateName(). 

The only way to get this working that I see right now is add our own cache implementation to Thymeleaf and then dynamically change the key being worked on. Or did I miss something and is it possible to do this without having to hack my way around the getTemplateName()?

**Comment by delgurth** [comment]
That commit is just a quick workaround I'm testing now. Since overriding the cache implementation is quite hard with all the finals in the classes/methods. 

I guess we should discuss this feature request and if it's something you indeed see as a good feature, the way to implement it before a real pull request can be created. Do you want to do that here or by e-mail?

**Comment by delgurth** [comment]
The fix is a bit more challenging then I initially thought (isn't that always the case...).

The problem is that once the template is in the cache under it's original name, the overrides are never going to be used. But you also don't want to check for an override if you do not want to use that functionality, for performance reasons. I'm still not sure how to properly fix this. I've made some more changes in our fork to try and see if that's going to work.

**Comment by danielfernandez** [comment]
After re-reading your and #300 with more care, I'm afraid I misunderstood Diego, and you would be right in thinking there is no easy or elegant way of doing this with an implementation of `ITemplateResolver`. The problem is, as you say, that `TemplateRepository` class only uses the template name for accessing the template cache, and this means there is no real way to introduce new variants like using request parameters.

The problem is there is no easy improvement to be done on 2.1 that would solve your scenario. `TemplateRepository` is not an interface (the extension point is `ITemplateRepository`, which lives in a lower tier), and the template cache is indexed using only the template name as key. Neither of these aspects should and/or could be changed in 2.1, as they would either create a new extension point (creating a potential confusion with `ITemplateRepository`) or modify the template cache interfaces already in use.

So I'm afraid the _stable_ solution for this will have to come in 3.0, most probably by generalizing the template cache keys so that they can be computed from the `TemplateProcessingParameters` instances and therefore allow much more generic cached template matching. This said, if we finally have template cache in 3.0, something that is not yet 100% clear because we have achieved such huge template parsing performance improvements that a cache might be of little use in 3.0.

For a workaround, my first option would be to actually modify the template name `String` object returned by Spring controllers, so that they contain both the _real_ template name and a suffix including any additional relevant information needed for template resolution. That way template cache would work as expected, and it would be the responsibility of the (custom) `ITemplateRepository` implementations to determine when they must execute (based on extended-template-name suffix), and then actually removing such suffix to perform real template resolution.

Does this make sense to you?

**Comment by yacota** [comment]
I've just created yesterday https://github.com/thymeleaf/thymeleaf/issues/380 and now found this ticket

From @danielfernandez 'workaround explanation' I do not understand this part :
  That way template cache would work as expected, and it would be the responsibility of the   (custom) ITemplateRepository implementations to determine when they must execute (based on extended-template-name suffix), and then actually removing such suffix to perform real template resolution.

There is no such thing as ITemplateRepository at least in 2.1.x 

If you read my issue description I think It won't be any incompatibility and no performance penalty  to use templateName+resourceName as key in the cache

**Comment by danielfernandez** [comment]
The new mechanism implemented for _template resolution attributes_, explained in #423, should solve this. Please have a look at it and test it if you can. It's already available in `3.0.0-SNAPSHOT`
