### ISSUE TITLE
Replacements in conditional comments

### ISSUE THREAD

**Issue by pfeigl** [thymeleaf/thymeleaf#33]
I'm using a conditional comment to load a javascript file only when running within IE7 or earlier.
I'm using the following code for that

```
<!--[if lte IE 7]>
<script type="text/javascript" src="@{/resources/externals/navigation/jquery.dropdown.js}"></script>
<![endif]-->
```

Unfortunately the resource link is not resolved, due to the content not beeing part of the actual document but just within a comment.
Is there any change to make thymeleaf handle the replacement anyways?

**Comment by danielfernandez** [comment]
Hi,

The Standard Dialects do not include any processors for comments, but you can create your own for processing this kind of comments.

What you have to do is to create your own implementation of the `IProcessor` interface and include it into a new dialect (implementing `IDialect`). You will then be able to add this dialect to your template engine in order to process comments in whichever way you need.

Regards,
Daniel.
