### ISSUE TITLE
StandardCache does not handle SoftReferences correctly.

### ISSUE THREAD

**Issue by frankbregulla1111** [thymeleaf/thymeleaf#332]
When the gc cleares SoftReferences the effective cache size may be reduced to below the max cache size.

Imagine we have a cache with a max size of 3 and insert values with keys "a", "b" and "c" in this order.
The internal fifo pointer will now point to the first entry key "a".
Now the gc decides to remove the soft references for all entries.
A get("b") will now return null and remove cache entry "b" from the internal container data structure. A subsequent put("b", ..) will remove "a" (because the fifo-pointer points here) and insert "b" into the container. The container now contains the keys "b" and "c". The fifo contains "b", "b", "c" and the fifo-pointer points to the 2nd "b".
A get("c") will remove c from the container.  A subsequent put("c", ..) now will remove "b" from the container (because the pointer points here) and insert "c". 
The container now contains only the key "c". The fifo contains "b", "c", "c" and the fifo-pointer points to the last "c".
If you put("a") for example, the "c" will get removed and the container will only contain the "a". We have now reduced the effective cache size to 1 and a new put(..) may lead to the removal of existing entries, even though we are below the max cache size.

I have a small test which demonstrates this behaviour. After the gc removes all soft references, the cache will be reduced to only one entry.

``` java
    public static final int MAX_SIZE = 10;

    @Test
    public void thatCacheDoesNotHandleSoftReferencesCorrectly () {
        StandardCache<String, String> cache = new StandardCache<>("test", true, 2, MAX_SIZE, NOPLogger.NOP_LOGGER);

        int keyCount = 0;
        long counter = 0;
        while (counter < 50) {
            String key = "key" + keyCount;
            cache.get(key);
            cache.put(key, "value" + keyCount);

            System.out.println("Size: " + cache.size());
            keyCount = (keyCount + 1) % MAX_SIZE;

            counter++;
            if (counter == MAX_SIZE + 1) {
                //force soft references to be cleared by gc
                try {
                    Object[] ignored = new Object[(int)Runtime.getRuntime().maxMemory()];
                } catch (Throwable e) {
                    // Ignore OME
                }
            }
        }
    }
```

**Comment by danielfernandez** [comment]
Thanks for your detailed explanation. I see the problem. However, if I'm right once we get to the scenario where we only have one entry in the container, (that `a` at the end of your example), it's not that the cache is reduced to size 1, but just that we only have one entry in the container and some specific `put` call sequences (but not all) would provoke entries recently added to the `container` to be removed. So the number of entries that we could have in cache from then could actually grow from 1.

Anyway, in my opinion this could be solved if, every time we consider an entry obtained from the `container` as _not-valid_ (for example, because its soft reference has been GCed), we not only removed it from the `container` map but also traversed the fifo array and removed the entry corresponding to such cache key. Right?

**Comment by frankbregulla1111** [comment]
Hi Daniel,

thank you for looking at this. I think your proposed solution should work. 

Regards
Frank

**Comment by danielfernandez** [comment]
Thymeleaf 2.1.4 has just been published, including this fix.
