### ISSUE TITLE
Thymeleaf removes name-attribute

### ISSUE THREAD

**Issue by inkrement** [thymeleaf/thymeleaf#342]
I found some strange behavior. Thymeleaf strips my name-attribute but I don't have a clue why. I tried several things, but I wasn't able to find a solution.

```
<select name="a"  id="paymentType" class="form-control" th:field="*{paymentType}" th:remove="all-but-first">
    <option th:each="type : ${paymentType}" th:value="${type}" th:text="${type}">Credit card</option>
    <option value="wirecard">Wirecard</option>
    <option value="debit">Debit</option>
</select>
```

generates the following:

```
<select class="form-control" id="paymentType" name="">
    <option value="CREDIT_CARD">CREDIT_CARD</option>
    <option value="DEBIT">DEBIT</option>
    <option value="WIRECARD">WIRECARD</option>                              
</select>
```

**Comment by ultraq** [comment]
I'm no pro in the Spring integration, but I'm wondering if it might have something to do with the `th:field` attribute you have on the `<select>` element.  `th:field` invokes some Spring magic that binds values in forms to request parameters so that they can be picked-out in your controllers, and the `name` attribute might be how it does that.

**Comment by danielfernandez** [comment]
The only possibility I see for the `name` being set to the empty string is that you are specifying a non-existing form attribute binding. This is, that the bean you have bound the form to (by using `th:object` on the containing `<form>` tag) has no property (or at least public and settable property) called `paymentType`...

Could this be?

**Comment by inkrement** [comment]
nope. the form does not have a `th:object` attribute. Here is the whole html-block:

```
<form class="form-horizontal" role="form" action="" th:action="@{paymentProvider}" method="post">
    <div class="form-group">
        <label class="control-label col-sm-2" for="paymentType">payment type</label>

        <div class="col-sm-10">
            <select name="paymentType"  id="paymentType" class="form-control" th:field="*{paymentType}" th:remove="all-but-first">
                <option th:each="type : ${paymentType}" th:value="${type}" th:text="${type}">Credit card</option>
            <option value="wirecard">Wirecard</option>
            <option value="debit">Debit</option>
        </select>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary" value="Submit">send</button>
    </div>
    </div>
</form>
```

**Comment by danielfernandez** [comment]
So if you have no form bean... where is that `paymentType` property from?

The problem is that Spring is not finding any binding for the `paymentType` expression. If you have no form, then I would recommend not using `th:field`, but simply the standard `name` and `id` attributes in your `<select>` tag, and then using `th:selected` in your `<option>` to determine which option should appear selected by default.

**Comment by inkrement** [comment]
I added it as object:

```
.addObject("paymentType", EnumSet.allOf(PaymentType.class));
```

ok, so I just remove `th:field` and use `th:each`.
