### ISSUE TITLE
Inconsistent entity handling in script blocks

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf#343]
I'm trying to embed a script that needs an ampersand character. If I use a raw `&`, I get a SAX parser error. If I use `&amp;`, Thymeleaf passes the literal `&amp;` into the output instead of turning into a plain ampersand.

```
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&amp;version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
```

**Comment by danielfernandez** [comment]
Yes, the XML parser used by Thymeleaf 2.1 does not really know about HTML elements which body should be treated as `CDATA` (as `<script>` should). This will be improved in 3.0.

In the meanwhile, you'll have to enclose your `<script>` body contents in a CDATA Section with `<![CDATA[...]]>`, an old trick:

``` html
<script>
// <![CDATA[
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
// ]>
</script>
```

**Comment by chrylis** [comment]
Now I'm getting `org.xml.sax.SAXParseException: XML document structures must start and end within the same entity.` Investigating.

**Comment by chrylis** [comment]
Closing tag needs to be `]]>`. Works with that.

**Comment by JeroenVdb** [comment]
@danielfernandez I bumped into the same issue as @chrylis with a Facebook widget. The widget embed code contains a raw `&` which we must escape as `&amp;`. But in the `<script>`tag this also stays `&amp;` and thus calling the Facebook SDK.js with a wrong set of parameters ("amp;version" instead of "version").

![image](https://cloud.githubusercontent.com/assets/657797/12746970/aef8359e-c9a1-11e5-9147-c8bee08f2bdd.png)

Extra info: http://stackoverflow.com/a/35149371/229532
