### ISSUE TITLE
I18n messages and array arguments

### ISSUE THREAD

**Issue by leroyvi** [thymeleaf/thymeleaf#345]
Hello,

I have an issue using `#{my.message.code(${someStringsArray})}` syntax.

The `MessageExpression.executeMessage` method, doesn't detect the param as an Array. So I have to use `#{my.message.code(${#strings.listJoin(someStringsArray,',')})}`.

Am I missing something ?

**Comment by afillatre** [comment]
Hi,

I have the same issue. I could use a shorter syntax as well.

**Comment by danielfernandez** [comment]
I might not be understanding completely your issue...

From what I understand, you are passing **only one** parameter to your message, and this parameter is an array.

So you have a message such as:

```
my.message.code=My message is {0}.
```

And then `someStringsArray` is a `String[]` such as `["hello", "goodbye"]`.

If you do:

```
<p th:text="#{my.message.code(${someStringsArray})}">...</p>
```

The expected result would be something like:

```
<p>My message is [Ljava.lang.String;@354c78e3.</p>
```

Which is normal, because arrays have no `toString()` implementation in Java, so the `java.text.MessageFormat` used underneath will end up outputting that. Note the Standard Message Resolver used in thymeleaf (which can be overriden) does not manually perform formatting, instead it simply delegates to Java's standard message formatting infrastructure.

Or is it that you are expecting your array's n positions to work as the message's n arguments such that with:

```
my.message.code=My message is {0} and {1}.
```

...you'd end up having?

```
<p>My message is hello and goodbye.</p>
```

If so, I'm afraid that is not possible, as there would be no way to determine whether you want to pass an array as the only parameter, or several parameters at a time. Actually, you could make it work that way by simply writing:

```
<p th:text="#{my.message.code(${someStringsArray[0]}, ${someStringsArray[1]})}">...</p>
```

**Comment by omblanco** [comment]
You can use a case, it is not a real solution to any number of messages, but it is valid.

```
<div th:switch="${#lists.size(someStringsArray)}" th:remove="tag">
      <span th:case="0" th:text="#my.message.code}"></span>
      <span th:case="1" th:text="#{my.message.code(${someStringsArray[0]})}"></span>
      <span th:case="2" th:text="#{my.message.code(${someStringsArray[0]}, ${someStringsArray[1]})}"></span>
      <span th:case="3" th:text="#{my.message.code(${someStringsArray[0]}, ${someStringsArray[1]}, ${someStringsArray[2]})}"></span>
      ....
</div>
```

Its work for me.

**Comment by vkuzel** [comment]
Use the [preprocessing](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#preprocessing).

```java
List<String> arguments = Arrays.asList("First", "Second");
```
Message:
```
message-code=Message with an argument {0} and another argument {1}.
```
Template:
```html
<span th:text="#{message-code(__${#strings.listJoin(arguments, ',')}__)}">
```
Result:
```
Message with an argument First and another argument Second.
```

**Comment by Owheee** [comment]
In case you have variable number of params there is a solution `${#messages.msgWithParams('my.message.code', someStringsArray)}`
