### ISSUE TITLE
Allow fragment parameters to have default values

### ISSUE THREAD

**Issue by kalgon** [thymeleaf/thymeleaf#350]
It would be great if fragment parameters could have default values:

``` html
<div th:fragment="frag (param = 'hello')">
```

**Comment by matodrobec** [comment]
It would be great to me too

**Comment by danielfernandez** [comment]
This should be mostly covered in Thymeleaf 3.0 by the creation of an out-of-the-box implementation of `ITemplateResolver` that always returns a previously configured text. This should be useful in some cases as the last element of a resolver sequence.

**Comment by danielfernandez** [comment]
Note that the previous comment does not apply - default template resolution (#440) should have no effect in this, as we are here talking about default values for fragment parameters.

**Comment by danielfernandez** [comment]
This behaviour should be actually covered in Thymeleaf 3.0 by combinations of `th:with` with default expressions and also the no-op token explained at #452.

For example, `th:with` can be used for applying a default value to `param` with:

``` html
<div th:with="param=(${param} ?: 'hello')">...</div>
```

...and also the no-op token could be used in some scenarios where `hello` is used as _prototyping text_, such as:

``` html
<span th:text="${param} ?: _">hello</span>
```

So I see no need to make the fragment signature syntax more complex to cover this more explicitly. I'm therefore closing this.

**Comment by JavaWebinar** [comment]
I've found this problem on stackoverflow: https://stackoverflow.com/questions/22093149/thymeleaf-fragments-and-default-parameters

I failed to to pass default param to fragment using `th:with`:
```
<th:block th:fragment="headTag (title)" th:with="img=${img} ?: 'default'">
  <div th:text="${img}"/>
</th:block>

<div th:replace="fragments::headTag('title')" th:with="img='value'">
```

Could you please give a sample how it could be done?

**Comment by danielfernandez** [comment]
@JavaWebinar please note that `th:replace` has greater precedence than `th:with`, so in your tag:
```html
<div th:replace="fragments::headTag('title')" th:with="img='value'">
```
That `th:replace` will execute, replace the tag, and therefore make that `th:with` simply disappear. So it will never execute and your `img` local variable will be never given a value.

If you want to specify that additional parameter, you can do:
```html
<div th:replace="fragments::headTag(title='title',img='value')">
```

**Comment by anschnapp** [comment]
@danielfernandez sorry for posting to this already closed issue.

But I don't get it and maybe I missed something.
How does the example with the image tag support default values for a fragment?
I only realise that it's possible to give in parameters over the fragment parameter list or via th:with but in both cases I don't see a possibility to define a default value on the fragment definition side (not the caller side)

Please let me know if i missed something here. And thank you in advance.

**Comment by danielfernandez** [comment]
@git2snap the idea is that, at the fragment side, a `th:with` can assign a default value to a parameter that is not given it (or is null).

Note that parameters appearing in the signature (`frag(par1,par2)`) are required, so we would have two options:

First option:
```html
<div th:fragment="frag (one)" th:with="two=${two} ?: 'default'">...</div>
```
Which we could call in several ways (note using named parameters as in the last line we can include parameters that are not in the signature):
```html
<div th:replace="::frag(${onevalue})">...</div>
<div th:replace="::frag(one=${onevalue})">...</div>
<div th:replace="::frag(one=${onevalue},two=${twovalue})">...</div>
```

Second option:
```html
<div th:fragment="frag (one,two)" th:with="two=${two} ?: 'default'">...</div>
```
Which requires us to specify both parameters (nulling the second one if needed):
```html
<div th:replace="::frag(${onevalue},${twovalue})">...</div>
<div th:replace="::frag(${onevalue},${null})">...</div>
<div th:replace="::frag(one=${onevalue},two=${twovalue})">...</div>
<div th:replace="::frag(one=${onevalue},two=${null})">...</div>
```

**Comment by anschnapp** [comment]
Hi @danielfernandez, thank you very much! Now it's clear for me. Looks like a good solution for supporting default values.

**Comment by anschnapp** [comment]
Hi @danielfernandez, one more question. If I want to have multiple default values, i would suggest to just use multiple th:with declarations for it.

But it seems not be supported, I get the following error message:
> Malformed markup: Attribute "th:with" appears more than once in element

How could I use your second option solution with multiple default parameters?

**Comment by danielfernandez** [comment]
@git2snap `th:with` allows the specification of several variable assignations, separated by commas.

**Comment by iansedano** [comment]
I have been using this method to create fragments with default values and it has served me well in many contexts. That said, I've often run into issues where scope and naming conflicts occur.

Say I have a fragment with optional parameters with generic names (e.g., "title" or "message"), and these names are also used higher up in the template hierarchy, the fragment can't **distinguish between parameters explicitly passed in and those inherited from the broader scope**.

Here's a basic example:

```html
<!-- Parent template -->
<div th:with="title='Parent Title'">

    <!-- ... -->
    <!-- Lots of other stuff -->
    <!-- ... -->
    
    <div th:replace="fragment :: myFragment"></div>
    <!-- ... -->
</div>

<!-- Fragment -->
<div th:fragment="myFragment" th:with="${title} ?: 'Default Title'">
    <p th:text="${title}"></p>
</div>
```

In this example, the fragment receives "Parent Title" instead of "Default Title" when no value is provided for `title` where the fragment is called.

I'm working around this by using unique parameter names, but this results in clumsy and less fluent fragment calls. What's more, when these issues occur, it can often be quite the head-scratcher, especially if the developer isn't well familiarized with Thymeleaf.

I think it would be great to have a way to detect the scope or somehow make these variables behave more like function arguments, where the "defaults" are used if no argument is passed through, instead of grabbing the variable if it exists anywhere in the context.

---

Apologies if it's better for this to be opened in a new issue with a summary of this issue. If that's better, I can do that. I eventually decided to extend this issue since it already seems to be well indexed and readily came up in related search results.
