### ISSUE TITLE
th:fragment inside th:include

### ISSUE THREAD

**Issue by JeroenVdb** [thymeleaf/thymeleaf#367]
For our progressive enhancement effort we respond with complete pages if the request isn't ajax and respond with only a fragment of the page when requested via ajax.

Example: when "Next articles" is clicked and requested with ajax the page is rendered and only the list items are send (views/all-your-articles.html :: ajax) back so we can append them with Javascript.

**views/all-your-articles.html**

```
...
<ul th:include="views/includes/list-of-articles" th:with="articles=${articles}" th:fragment="ajax">
</ul>
<a href="page2.html">Next articles</a>
...
```

**views/includes/list-of-articles.html**

```
<li th:each="article : ${articles}" th:text="${article.title}">Article 1</li>
```

**The problem:** when the th:fragment **isn't** set in the "top" page (that isn't included anywhere) this doesn't work. Is this for a reason? Or am I implementing this wrong?

**Comment by danielfernandez** [comment]
This is actually the expected behaviour. By the moment you specify to Spring you want the `views/all-your-articles.html :: ajax` fragment, and Spring passes that request to Thymeleaf, Thymeleaf will go to the `all-your-articles.html` template and parse+execute _only_ the `ajax` fragment. So such fragment has to actually live inside that template.

In order to work placing `th:fragment` inside `list-of-articles.html`, Thymeleaf would have to parse+execute the entire `all-your-articles.html` template, and then parse+execute `list-of-articles.html` when it reaches that `th:include`. That would of course be a performance problem, because the idea behind specifying fragment names at Spring controllers is precisely to focus on only a small part of the markup, executing only that specific part and therefore benefitting from discarding all non-relevant parts.

**Comment by yvanavermaet** [comment]
@danielfernandez Isn't that strange behaviour? Imagine that we've passed some data via th:with, from the actual page over various includes to that include-file that contains th:fragment="ajax". The way you describe, this isn't possible.

We're working progressive enhanced:
- No working JS for whatever reason, then the link will go to "all-your-articles.html".
- If you have JS, you just want a small partial of "all-your-articles.html" (wherever the th:fragment residesin , the parent or an include)

In our solution, both scenario's would have to render the page, so how is the 2nd option a performance issue?

I do think that this is an issue with Thymeleaf. I do understand that you COULD make it faster by specifying the actual include, but why would one use th:fragment in this case? I could just create a new include which contains the needed html.

Imo, you could advise to specify the include to speed things up, but it shouldn't be made mandatory.

I hope to hear from you.

**Comment by yvanavermaet** [comment]
@danielfernandez Still awaiting a reply. Thanks in advance!

**Comment by danielfernandez** [comment]
@yvanavermaet that's what fragments were defined for, actually...

The idea behind fragments is to process only a part of a template, for instance, in order to include them into another fragment. If a template `home.html` includes fragments `header`, `menu` and `footer` from template `layout.html`, used to define the general appearance of an entire site, it would not make much sense to execute the entire template `layout.html` three times in order to include those three fragments. Same goes for templates that include (maybe recursively or iteratively) a fragment defined inside themselves: we would get into an infinite loop.

If what you want to do is process an entire template but ignore all of its output except a specific part, I would do that by means of a post-processor in Thymeleaf 3.0. But unfortunately, there is no such thing in 2.1.
