### ISSUE TITLE
different evaluation of @ symbol / context using th:src

### ISSUE THREAD

**Issue by ttwhy** [thymeleaf/thymeleaf#371]
hello,

we found something strange within the context annotation and modified contextPath. 
We are using a Filter concept which modifies the contextPath.
contextPath original: /my-app
contextPath modified: /my-app/additionalInformation

if we use th:src="@{/myUrl}" the result will be src=/my-app/myUrl
the same syntax using th:attr="src=@{/myUrl}" returns src=/my-app/additionalInformation/myUrl

Is there a different way of handling the context segment within th:src and th:attr?

**Comment by danielfernandez** [comment]
The only real difference between how your URL will be treated in `th:src` and `th:attr` is that, if you are using Spring, `th:src` will call Spring's `RequestDataValueProcessor#processUrl(request, url)` in order to enable Spring's own URL rewriting and form tuning mechanism, which in turn enables things like CSRF protection in Spring Security.

Maybe you are directly acting somehow on the `RequestDataValueProcessor` infrastructure? does your filter create a wrapper on the `HttpServletRequest`? and if so, does it execute before Spring's, which creates its own wrapper too?

**Comment by ttwhy** [comment]
Thanks for the fast reply! The filter will be executed within the Spring Application Filter Chain (The stack shows org.springframework.web.filter.DelegatingFilterProxy as a part of the current position ...so the filter chain will be started and Springs filters will be started before the custom Filter).
The Filter wrappes the request within a extended HttpServletRequestWrapper class.

I will lookup the RequestDataValueProcessor#processUrl. If there is a possibility to access this method explicitly, this could be a workaround.

**Comment by lukosan** [comment]
A word of warning: if you are using the CSRF protection in SpringSecurity this is also achieved by a class which implements the `RequestDataValueProcessor` interface and the  `RequestDataValueProcessor4Delegate` in Thymeleaf only delegates to a single implementation. So you could either extend the `CsrfRequestDataValueProcessor` class or create a different implementation of the delegate interface `IRequestDataValueProcessorDelegate` and wire up two RequestDataValueProcessor classes into it. Incidentally this isn't really a limitation of Thymeleaf itself but rather one imposed by Spring as the `RequestContext` class only holds a single `RequestDataValueProcessor`. It _sort of_ makes sense - in that you only really want one thing playing around with your URLs but it also _sort of_ doesn't, in that the 4 methods of `RequestDataValueProcessor` can deal with up to 4 different use cases. If the latter is true for your application then you'd potentially want 4 different implementations and thus 4 different interfaces.

I have a similar situation - I'd like to use CSRF but I'd also like to use an implementation of the `RequestDataValueProcessor` to prepend all URL's with the full protocol and domain name so that I can use a Resource Oriented Client Architecture style of serving links.
