### ISSUE TITLE
Cannot pass arguments to fragment, if fragment name is the same as already used tag

### ISSUE THREAD

**Issue by globalbus** [thymeleaf/thymeleaf#373]
Take this as a example

```
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<div>
<button></button>
<div></div>

<div th:fragment="button(countArg)">
    <div th:text="${countArg+1}">Add file</div>
</div>
</div>
</html>
```

If I use somewhere in the same file tag with name of any defined fragment (in this example, "button"), arguments passed to fragment will not be accessible (nulls). Position of tag is irrelevant.
This fragment, loaded anywhere, will cause an error in expression evaluation (null+1)

Error is not very problematic (I only need to change the name of fragment), but can be very tricky.

**Comment by ultraq** [comment]
This might be because fragment selectors don't just select fragments by their names, but are also DOM selectors according to the docs here: http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#defining-and-referencing-fragments  It says they're also XPath or CSS selectors, and I think it's the CSS selector you're running into.
