### ISSUE TITLE
Unescape Java Script 

### ISSUE THREAD

**Issue by yugakiran** [thymeleaf/thymeleaf#374]
Hello All, 

I have a problem, where i would like to render the value of string with unescaped in the inline java script of thymeleaf. 
Ex: abc =/_[[${xyz}]]_/; 
expectedOutput: abc = "hello="world"". 
Actual output: abc = "hello=\'world\"". 

Tried many things, like thymeleaf escapeJavaScript/unescapeJavaScript. But nothing works. Please let me know if we can achieve this through thymeleaf. I am using Spring MVC to pas the value of xyz as attribute. 

Thanks

**Comment by danielfernandez** [comment]
It seems you need inlining inside JavaScript code, but without thymeleaf actually understanding that it is processing JavaScript (thymeleaf outputs that as a string literal because that kind of inlining is for outputting such kind of litterals). In such case, wouldn't using text inlining (intead of javascript) solve your scenario?

**Comment by yugakiran** [comment]
Thanks for rep;lying Daniel. I am using Thymeleaf 2.1.3
Here is my actual code snippet  <div th:inline="javascript">[[${session['STRING_HTML']}]]</div>
Now I would liek to render this STRING_HTML on browser.

But the STRING_HTML wasn't unescaped and as a result its breaking the prcoess of rendering the markup.
