### ISSUE TITLE
Possible infinite loop with Numbers.sequence

### ISSUE THREAD

**Issue by mohic** [thymeleaf/thymeleaf#377]
Hi,

If I use this code

``` java
Numbers.sequence(5, 2, -1)
```

it's make an infinite loop.

Best Regards,
Christophe

P.S.: I use Thymeleaf 2.1.4

**Comment by ultraq** [comment]
Thanks for the bug report :+1:

I've found the problematic code: https://github.com/thymeleaf/thymeleaf/blob/3.0-dev/src/main/java/org/thymeleaf/util/NumberUtils.java#L146-L159

Looks like `step` is assumed to be positive for when `from` < `to`, and negative for when `from`> `to`.  Fix should probably be to assume nothing about `step`, and always add it to the current value until the value exceeds the range of `from` to `to`.  Current code doesn't infinite loop, but probably takes a helluva long time because it's generating an array from 5 to `Integer.MAX_VALUE`! O_O

**Comment by kreuzman** [comment]
Hi, I would like to contribute and fix this issue but it's unclear to me what is expected behaviour in this case. Should step <= 0 be allowed anyway? If step is 0 there will be definitely infinitive loop. There's just not null validation of step value. If 0 and negative step is allowed what is the desired output of below examples?

``` java
Numbers.sequence(1, 5, 1) == [1, 2, 3, 4, 5]
Numbers.sequence(5, 1, 1) == [5, 4, 3, 2, 1]
Numbers.sequence(1, 5, -1) == ?
Numbers.sequence(5, 1, -1) == ?
Numbers.sequence(5, 1, 0) == ?
```

Also it seems there's no test for Numbers utility class should I create one?

**Comment by mohic** [comment]
Hi,

My goal was to obtains 5, 4, 3, 2, 1 sequence number but at this time, I don't know that Numbers.sequence(5, 1) count from five to one. I thought that Numbers.sequence(5, 1) just don't work.

I my head, sequence function is based on this code:

``` Java
for (int i = firstArgument; i < secondArgument; i += thirdArgument) {
// ...
}
```

Now I know that 5, 1 give me 5, 4, 3, 2, 1 sequence and it's not necessary to add third argument.

**Comment by danielfernandez** [comment]
This has been finally implemented like this:

``` java
Numbers.sequence(1, 5, 1) == [1, 2, 3, 4, 5]
Numbers.sequence(5, 1, 1) == (exception)
Numbers.sequence(1, 5, -1) == (exception)
Numbers.sequence(5, 1, -1) == [5, 4, 3, 2, 1]
Numbers.sequence(5, 1, 0) == (exception)
```

**Comment by danielfernandez** [comment]
Already in `2.1.5-SNAPSHOT`

**Comment by mohic** [comment]
Thanks for this fix... And for Thymeleaf  :smile:

**Comment by PawelJagus** [comment]
Unfortunately this fix breaks already existing reverse sequences in views. For example numbers.sequence(9,1) ends now with IllegalArgumentException. Not cool.
