### ISSUE TITLE
Modify TemplateRepository in order to build cache keys based on templateName+resourceName

### ISSUE THREAD

**Issue by yacota** [thymeleaf/thymeleaf#380]
We have implemented our own ThymeleafViewResolver which is tenant aware. So if a request comes from site A we will look for templates in BASE_DIR/tenantA/template.html, and if a request comes from site B we will look for templates in BASE_DIR/tenantB/template.html and so on. 

So far so good, BUT, fragment resolution done by TemplateResolver class assumes that resource location of fragments resides ALWAYS in the BASE_DIR (the prefix attribute specified in the current TemplateResolver).

We can implement another TemplateResolver which will be used before the default one, and this could be tenant aware, if the resource is not there(for whatever reason) TemplateRepository is capable of using the next TemplateResolver .... so everything is fine up until now.

The problem that we face here is that the cache mechanism build into TemplateRepository assumes that given a templateName only one resource can exist, but that's not true in our case, because given a template name, for instance template.html, two resources could exist tenantA/template.html and tenantB/template.html.

So we are asking you to modify the way you are caching templates in order to use templateName+resouceName as a key of the cache.
I think that this change is absolutely backward compatible with no side effects, and will also help other similar issues I've found that could be solved this way, like : 
https://github.com/thymeleaf/thymeleaf/issues/264
https://github.com/thymeleaf/thymeleaf/issues/213

By the way TemplateRepository is final so we can not do anything there :)

**Comment by yacota** [comment]
Ups I've just found https://github.com/thymeleaf/thymeleaf/issues/329 .... adding a comment on that ticket

**Comment by yacota** [comment]
Also changing method's signature of TemplateResolver.getPrefix to a non final method would be welcomed because then any customized TemplateResolver could modify the prefix path at runtime for instance.

**Comment by danielfernandez** [comment]
I don't think adding the resource name to the cache key would be possible, because by the time the template engine accesses the cache in order to determine whether the requested template is there or not, _template resolution_ as such has not been executed yet. So we don't have a resource for the template, nor a resource name. Therefore we wouldn't be able to get entries from the cache.

Your solution might need three steps: 

First, creating a custom `ThymeleafViewResolver` like the one you have created, modifying the template name that is passed to the Thymeleaf engine in order to take multi-tenancy into account. That will give you what you already have: a _correctly-resolved_ template.

Second, as for fragments, unfortunately 2.1 only uses the fragment itself as specification for building the cache key. It doesn't really add any context about _where that fragment is being invoked from_. That is indeed a limitation causing scenarios like yours, but I'm afraid there would be no easy way for 2.1 to be able to add such context to fragments...

Luckily, I think this will not be an issue in 3.0. If you have a look at https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/engine/TemplateManager.java#L408-L409 you can see how now we build the cache keys for our fragments with much more information, among which you can see the `ownerTemplate`. And that `ownerTemplate` is the name of the template the fragment is being invoked from. Name that, in your case, would have been modified by your _Spring view resolver_ (not by the _template resolver_, which shouldn't change template names during resolution because cache wouldn't work).

Third, you need a _template resolver_ that is able to resolve standalone fragments (i.e. fragments in a different file) for a specific template _knowing what is the calling template_, so that it can detect the multi-tenancy-related items in that template name and act in consequence when resolving the fragment's resource. And that is something that we don't have in 3.0 yet. So I think it should be added.

I'm therefore leaving this as an item in the 3.0 backlog. Unfortunately this third item is not developed yet, so you won't be able to make it work with our current snapshots (or `3.0.0.ALPHA02`), but I hope we might have this done soon.

**Comment by yacota** [comment]
Thanks for the feedback!!

I am going to elaborate my suggestion a little bit more because I do not see what you see :)

As far as I know TemplateRepository is the one that uses the template caching mechanism, in 
    public Template getTemplate(final TemplateProcessingParameters templateProcessingParameters)

In that method a list/set of ITemplateResolver s is retrieved, my templateResolver is retrieved first and has a specialized method

   protected String computeResourceName(final TemplateProcessingParameters templateProcessingParameters)

in this method I can get the parent template name and also the parent template path as follows 

```
final String parentTemplateName = ((org.thymeleaf.Arguments)templateProcessingParameters.getProcessingContext()).getDocument().getDocumentName();
final String parentResourcePath = ((org.thymeleaf.Arguments)templateProcessingParameters.getProcessingContext()).getTemplateResolution().getResourceName();
```

in this method I also check that templateProcessingParameters.getProcessingContext() is an instance of Arguments, if not I call super.computeResourceName. 
The only thing to mention is that TemplateResolver's computeResourceName should call getPrefix() method instead of accessing prefix attribute directly, thus letting customized TemplateResolver like mine do the trick explained below

Now I can compute the real resource name by using parent's resource path plus a customized getPrefix(), this method should not be marked as final in TemplateResolver and thus could access a thread-local tenant aware attribute that will give me the chance to use a specialized view per tenant although the returned controller's view name does not change from request to request.

By using the parent's resource path I am assuming that all templates/fragments will be relative to the parent template, which I think is a safe assumption, maybe not :)

Back to TemplateRepository ... the TemplateResolution instance returned by TemplateResolver will return a computed tenant aware resourceName that could be used to generate the key of the cache

```
resourceName = templateResolution.getResourceName();
if (this.templateCache != null) {
    final Template cached = this.templateCache.get(buildCacheKey(templateName, resourceName));
    if (cached != null) {
        return cached.createDuplicate();
    }
}
```

The only thing left here is to use again this resourceName when creating the cache key at the end of the method.

The process of computing the real resource name is done BEFORE asking the cache for the template, the process is pretty light so I do not think it can affect the overall performance.

Only one thing is left here and is detailed in https://github.com/thymeleaf/thymeleaf/issues/383 , where in order to load the appropiate .properties per template we need to modify StandardMessageResolutionUtils in order to take into account the resourName when building the keys of its cache,  BTW the template resolutions instance is available as follows and it gives us access to the resourceName

```
public static String buildTenantPreKey(final Arguments arguments) {
    return arguments.getTemplateResolution().getResourceName(); 
}

 public static String resolveMessageForTemplate(final Arguments arguments, final String key, final Object[] messageParameters, final Properties defaultMessages) {

    Validate.notNull(arguments, "Arguments cannot be null");
    Validate.notNull(arguments.getContext().getLocale(), "Locale in context cannot be null");
    Validate.notNull(key, "Message key cannot be null");

    final Locale locale = arguments.getContext().getLocale();

    final String templateName = arguments.getTemplateResolution().getTemplateName();
    final String cacheKey = TEMPLATE_CACHE_PREFIX + buildTenantPreKey(arguments) + templateName + '_' + locale.toString();
    ...
}
```

Thanks again for your feedback!

**Comment by danielfernandez** [comment]
Well, finally after a lot of refactoring effort invested on the Template Resolution, Message Resolution and Context APIs (in some cases refactorings on refactorings ;)), I've finally found a way to implement this that was sound enough with the new architecture of the engine in 3.0…

The main problem was, switching the way in which the `TemplateManager` (heir of the `TemplateRepository` in 2.1) performed cache obtention so that resolution was executed _always_, and not only if a _cache miss_ happened, was not really an option. Template resolvers might perform external resolution against files, URLs, databases... any kind of resource. And moving the resolution mechanism to _before_ checking the cache could definitely affect performance a lot in too many scenarios.

So I've finally gone for a map of configuration attributes, the _template resolution attributes_, that can be used for affecting the way in which a Template Resolver actually resolves a template. This map will be passed as an argument to every Template Resolver resolution call, and also will be a part of the template cache key, so collisions shouldn't be a problem in your multi-tenant scenarios.

Everything is explained at #423, and already available in `3.0.0-SNAPSHOT`. Please have a look and check if this new mechanism would solve your issues…

**Comment by yacota** [comment]
Thanks for the effort.  I will give it a try ASAP. 
By the way any chance to get a release candidate instead of working with snapshots ? As far as  I can see Thymleaf 3 seems pretty stable.

**Comment by danielfernandez** [comment]
Yes, we should produce `3.0.0.BETA01` this week.
