### ISSUE TITLE
Recursive fragments not working since (at least) 2.1.2.RELEASE

### ISSUE THREAD

**Issue by marukuru** [thymeleaf/thymeleaf#382]
I tried to do recursive fragment replacement/inclusion for a simple Java POJO-styled tree (item with title and a list of children). The feature was introduced in 2.0.X as mentioned in #2 
I tried the supplied test https://github.com/thymeleaf/thymeleaf-tests/blob/20130702/src/test-common/resources/engine/attrprocessors/include/include13.thtest from #2 with 2.0.19, where it works as expected. However with 2.1.2.RELEASE and newer the test fails to generate the output for levels 1 and deeper.
Working output for 2.0.19 is:

``` html
<div>
    <p>This is some text</p>
    <div>
        <div>
            <p>before</p>
            <div>
                <div>
                    <p>before</p>
                    <div>
                        <div>
                            <p>before</p>

                            <p>after</p>
                        </div>
                    </div>
                    <p>after</p>
                </div>
            </div>
            <p>after</p>
        </div>
    </div>
</div>
```

Output for 2.1.4.RELEASE is:

``` html
<div>
    <p>This is some text</p>
    <div>
        <div>
            <p>before</p>
            <div></div>
            <p>after</p>
        </div>
    </div>
</div>
```

The original test has only been altered in a way, so that the template/fragment could be resolved according to the API of the used Thymeleaf version.

(I did not test 2.1.0.RELEASE and 2.1.1.RELEASE)

Test files 2.0.19:
test.html

``` html
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">
<body>
    <div th:with="index=0">
        <p>This is some text</p>
        <div th:include="@{frag}::f">...</div>
    </div>
</body>
</html>
```

frag.html

``` html
<html lang="en" xmlns:th="http://www.thymeleaf.org">
<body>
    <div th:fragment="f" class="a">
        <div th:with="index=(${index}+1)">
            <p>before</p>
            <div th:if="${index &lt; 3}" th:include="@{frag}::f">...</div>
            <p>after</p>
        </div>
    </div>
</body>
</html>
```

Test files 2.1.4.RELEASE:
test.html

``` html
<html lang="en" xmlns:th="http://www.thymeleaf.org">
<body>
    <div th:with="index=0">
        <p>This is some text</p>
        <div th:include="@{frag}::f">...</div>
    </div>
</body>
</html>
```

frag.html

``` html
<html lang="de" xmlns:th="http://www.thymeleaf.org">
<body>
    <div th:fragment="f" class="a">
        <div th:with="index=(${index}+1)">
            <p>before</p>
            <div th:if="${index &lt; 3}" th:include="this :: f">...</div>
            <p>after</p>
        </div>
    </div>
</body>
</html>
```

**Comment by danielfernandez** [comment]
This is actually the way Thymeleaf 2.1 works, by design. I agree that it might be confusing (in fact, Thymeleaf 3.0 changes this and works in exactly the way you expect), but there is a reason for it.

First, it's not that recursive fragments _stopped_ working in 2.1. It's just that 2.1 introduced the `this` keyword for making reference to the _same_ template, but this _same_ template actually meant _the template that is being executed right now_. There is no way to mean what you expected with 2.1's architecture. And in your example, you are not trying to include a fragment from the template being executed, but from one that is just contributing a fragment. This is not possible in 2.1 using the `this` keyword, but would perfectly work if you used `frag` just as you were doing in `2.0`.

This said, again, Thymeleaf 3.0 fixes this behaviour and you should be able to use `this` inside `frag` meaning `frag` itself, whatever the first-level template including `frag` is.
