### ISSUE TITLE
ThymeLeaf->AngularJS

### ISSUE THREAD

**Issue by neblina-software** [thymeleaf/thymeleaf#393]
Hi there. im Trying to do:

...
< a href="#" th:inline="text" ng-click="blotoggle([[${posts.id}]])">Click Me!</ a >
...

Testing with th:inline="javascript" [[${posts.id}]]

Do not work!

I think it is a bug.

This tag should work, but never inside a tag=""

< a href="#" th:inline="text" >Click Me! [[${posts.id}]]</ a >

Prints

> Click Me! 101

Issue Result

> < a href="" ng-click="blotoggle([[${post.id}]])">< / a >

Note: If anyone response to use /\* */, ="javascript", it doesn't work.

Regards!

**Comment by lukosan** [comment]
```
<a href="#" th:inline="text" ng-click="blotoggle([[${posts.id}]])">Click Me!</ a>
```

will not work. The reason is that th:inline only works on the contents of the node - i.e. the "Click Me!" part. There's no way for Thymeleaf to know that you want it to affect the contents of the ng-click attribute. This isn't a bug, it's very much a feature.

However, you can achieve what you want by using the th:attr attribute (or by creating a custom dialect for angular, if you fancy the challenge!).

**Comment by neblina-software** [comment]
To complex, but it is working for now!

https://github.com/neblina-software/balerocms-enterprise/blob/master/src/main/resources/templates/silbato/blog.html

**Comment by danielfernandez** [comment]
As a side note: Thymeleaf 3.0 allows you to use `th:ng-click="blotoggle([[${posts.id}]])"`, and that will create an `ng-click` attribute with the contents you need.

**Comment by neblina-software** [comment]
Thanks for the fix! Is there a way for using BETA or ALPHA release in spring-boot-thymeleaf?
