### ISSUE TITLE
Question: Markdown in Thymeleaf

### ISSUE THREAD

**Issue by beradrian** [thymeleaf/thymeleaf#439]
What will be the best way to implement Markdown in Thymeleaf?
- template mode
- a new dialect (what processors?)

It would be useful if I can embed markdown in HTML.
I also asked this on SO: http://stackoverflow.com/questions/34115270/markdown-in-thymeleaf.

**Comment by danielfernandez** [comment]
What do you mean with _implementing Markdown in Thymeleaf_? Tuning thymeleaf to turn it into some kind of markdown processor (which I wouldn't recommend at all), or rather create some kind of additional processors that would let you run a markdown processor for a piece of markup like e.g. the body of a `<code>` (or any other)?

I will suppose it is the latter, and you want to process a body of a HTML tag as Markdown. In such case, What I would do is:
- Create an attribute processor (element processor in 3.0 terminology) that detects an attribute such as `markdown:enable` or similar, and in such case sets a local variable that can later be identified from a _text processor_ in order to know that the body text should be considered markdown and thus processed.
- Create a text processor (processors in charge of processing text, i.e. bodies of tags, when in `HTML` mode). That checks if such _markdown enablement_ local variable is set and, in such case, gets the tag body and passes it on to the Markdown processor, setting the result as the new tag body.

So I would basically go for a dialect with two processors: an _markdown enabler_ and a _markdown executor_.

**Comment by beradrian** [comment]
Yep, that's what I meant. Thanks!

**Comment by beradrian** [comment]
From what I understood from Javadoc, I will have to implement first the _markdown enabler_ as an `AbstractAttributeModelProcessor` and use `structureHandler.setLocalVariable` to set that variable. Then I have to implement the _markdown executor_ as an `AbstractTextProcessor` and in the `doProcess` method to test the variable using `context.getVariable` and if set to replace the text with a new model

```
structureHandler.replaceWith(imodelFactory.parse(templateData, transformMarkdown(itext.getText())), true);
```

Is that right?
Markdown can contain HTML tags. How can I ensure that those are not parsed and transformed into events before the method `transformMarkdown` is called?

When will the inline expressions be evaluated?

**Comment by danielfernandez** [comment]
> From what I understood from Javadoc, I will have to implement first the _markdown enabler_ as an `AbstractAttributeModelProcessor` and use `structureHandler.setLocalVariable` to set that variable. Then I have to implement the _markdown executor_ as an `AbstractTextProcessor` and in the `doProcess` method to test the variable using `context.getVariable` and if set to replace the text with a new model
> 
>    structureHandler.replaceWith(imodelFactory.parse(templateData, transformMarkdown(itext.getText())), true);
> 
> Is that right?

That sounds right, except you don't really need that call to `structureHandler.replaceWith` at the text processor. You could simply get the `text` element and do `text.setText(transformMarkdown(..))`.

> Markdown can contain HTML tags. How can I ensure that those are not parsed and transformed into events before the method transformMarkdown is called?

OK, that is a problem because you need to avoid the parser to think those HTML tags in Markdown are actually part of your higher-level markup. The only tags that the thymeleaf parser (as of 3.0) will consider `CDATA` and therefore not parse what is inside are `<style>` and `<script>` (which is what the HTML specification says).

So your options are either escape your HTML tags in markdown (which will make it valid HTML but modify your markdown syntax a bit), enclose your markdown in `<script>` tags, or simply use a `<[CDATA[...]]>` section and then create a _CDATA Section processor_ exactly the same as your text processor (or calling the same external logic).

> When will the inline expressions be evaluated?

Hmmm... let me think about this, because inlined expressions are converted to elements with `th:text` at parsing time, and I'm now thinking that this might interfere with your `CDATA`...

**Comment by beradrian** [comment]
Using the `<script>` tag sounds good. There is still the problem with inline expressions.

**Comment by beradrian** [comment]
Ahh, and it would be nice if the transformed text will still be processed after. E,g, if you have a `<img>` tag with `th:src`.

**Comment by danielfernandez** [comment]
OK, your scenario really made me think and pushed me to perform a significant amount of refactoring on the way inlined output expressions are (were) processed.

The problem is (was) that, until now the Standard Dialects were preprocessing inlined output expressions at parsing time. Which was very convenient because it allowed text nodes to be cached with inlining already resolved and converted into things like `<th:block th:text="${inlined_expression}" />`.

This helped performance because it meant that text nodes did not have to be scanned at template processing time for inlined expressions (and scanning text char-by-char might eat precious nanoseconds). But at the same time it meant that, in your scenario, there would be no way thymeleaf could be serving you text nodes in the way you expected them, but instead divided into several pieces with `<th:block>`'s in the middle. Very inconvenient for something like a Markdown processor (or any other kind of text processor, actually).

So what I did was to make Thymeleaf apply the mechanism explained above only when the Template Engine has only one registered _text processor_ (the inlining one from the Standard Dialect). If there are more, this is not applied and texts will be actually scanned at template processing time looking for inlined expressions.

In fact, in order to make this not affect performance negatively, the fact that a text node _might contain inlined expressions_ is actually resolved (i.e. scanned) into a flag at parsing time, and therefore cached. So at template processing time the only texts that need to be scanned are those that have been created during template processing itself. This limits the execution of the _inlining_ mechanism to only those texts that do contain inlined expressions, which helps a lot reducing to the minimum the performance impact of having custom (non-standard) text processors registered.

In your case, you will receive your texts with inlined expressions already resolved if you make your text processor execute after the `StandardInliningTextProcessor`, which is the text processor in charge of resolving these expressions. So you need a precedence `> 1000`.

This is already in `3.0.0-SNAPSHOT`
