### ISSUE TITLE
th:content rendering fails after 3.0 migration

### ISSUE THREAD

**Issue by juanitocalero** [thymeleaf/thymeleaf#444]
I found an issue migrating to Thymeleaf 3.0.

The engine throws an `TemplateProcessingException`
[error-thymeleaf.txt](https://github.com/thymeleaf/thymeleaf/files/71702/error-thymeleaf.txt)
if the tempate has an attribute `th:content` inside a `meta` tag. The static `content` attribute works ok.

The value of the attribute is irrelevant. It fails everytime.

It looks like it fails with the `meta` tag and any dynamic property, not only th:content.

**Comment by juanitocalero** [comment]
Also, it would be very helpful if the exception could leave some information of the location of the error.
I had to completely clean my html in order to find the source of the problem.

Great update, anyway. Except this problem, very straightforward and clearly documented.

**Comment by danielfernandez** [comment]
Strangely, this looks like a parsing error... could you please post the specific fragment of template that's provoking this error? Also, I'm interested on the value you are setting for that `th:content`. Thanks

**Comment by danielfernandez** [comment]
And also... was this `3.0.0.BETA01` or `3.0.0-SNAPSHOT`? If it was the former… could you try `3.0.0-SNAPSHOT` and see if the issue is still there? See http://www.thymeleaf.org/faq.html#use-snapshot on how to use a snapshot.

**Comment by danielfernandez** [comment]
Most probably something more complex than a mere `th:content` is happening at your template, I'm afraid. See the tests created in the commit linked above, which perfectly pass both on `3.0.0.BETA01` and `3.0.0-SNAPSHOT`.

The more info you can give us about your failing template the better. Thanks again.

**Comment by danielfernandez** [comment]
More questions: from what I see in your exception trace, the error seems to havey nothing to do with a `th:content`, and instead happens when the engine tries to insert a `Model` (i.e. a fragment of template) which is malformed because it only has one of the _template start_ / _template end_ events (it should either have both or none).

This can only happen in a `th:utext`, `th:insert` or `th:replace` (or the deprecated `th:include` and `th:substituteby`). Or in a custom processor that calls `structureHandler.setBody(model)`, of course. 

So is this your case? do your `error.html` or `pruebas.html` templates contain these processors? if so... can you show what is the shape of what is being inserted and what do these _inclusion_ attributes look like in your host tags? thanks

**Comment by juanitocalero** [comment]
I'm using `3.0.0.BETA01`. And my template uses fragments, as you said. I'm attaching my `pruebas.html`, athough right now I have no time to clean it up to the minimal working example.
In this example I got two same page fragments, the original and the test. The test is an exact copy of the original without the conflicting  `meta` tags. Adding the original to the page fails. Adding the test works. 
Maybe it is not related to the `meta` or `th:content` parts, but I think it's a good hint.
[pruebas.html.txt](https://github.com/thymeleaf/thymeleaf/files/72639/pruebas.html.txt)

**Comment by danielfernandez** [comment]
Bug #445 has been determined to be the cause of this. In your case, most probably the cause are those unneeded `</meta>` close tags (`<meta>` is a void HTML element with no close tag)

**Comment by danielfernandez** [comment]
Fixed and already in `3.0.0-SNAPSHOT`. Thanks.
