### ISSUE TITLE
Add getter to get first level template name

### ISSUE THREAD

**Issue by sorayasl** [thymeleaf/thymeleaf#446]
At https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/expression/ExecutionInfo.java it would be nice having a method to get first level template name instead of calling `getTemplateNames()` to get the first item

**Comment by danielfernandez** [comment]
New methods have been added to `#execInfo`:
- `#execInfo.processedTemplateName` obtains the name of the template at first level, i.e. used for calling the `TemplateEngine` itself.
- `#execInfo.processedTemplateMode` obtains the template mode corresponding to the `processedTemplaetName`.

Besides, the javadoc for the `ExecutionInfo.getTemplateName()` and `ExecutionInfo.getTemplateMode()` methods has been fixed to specify that since Thymeleaf 3.0 they will be returning the name and mode for the _leaf_ templates, i.e. the templates to which the nodes/tags being processed originally belong.

This is already in `3.0.0-SNAPSHOT`
