### ISSUE TITLE
Thymeleaf templates are not working in HTML script elements

### ISSUE THREAD

**Issue by dlvenable** [thymeleaf/thymeleaf#447]
Thymeleaf 2.1 would correctly operate within HTML `<script>` tags. However, upon updating to 3.0.0.BETA1, these replacements are no longer occurring. The generated HTML has the data within the script exactly as it is in the template file.

For example, the following template produces:

```
    <script type="text/ng-template" th:id="${scriptId}+'.html'">
        <span th:text="${name}"/>
        <div th:include="innerScript :: innerScript(id=${scriptId})"/>
    </script>
```

produces:

```
    <script type="text/ng-template" id="665a1c316ae049c8a7a5f7b2d46f92b4.html">
        <span th:text="${name}"/>
        <div th:include="innerScript :: innerScript(id=${scriptId})"/>
    </script>
```

 (where scriptId was just some UUID I made for testing)

**Comment by danielfernandez** [comment]
This was due to the way `<script>` tags are treated in AttoParser 2.0. `<script>` tags are in fact `CDATA` per the HTML5 specification and thus should not be parsed and processed. That's what the new `<template>` tag in HTML5 is for.

However, unfortunately IE has no support for `<template>`, so many frameworks are still using `<script>` tags with _alien_ types such as your `text/ng-template`. So AttoParser modified its behaviour to only consider `CDATA` those `type`s that were recognizable as containing scripts. See attoparser/attoparser#9

Thymeleaf `3.0.0-SNAPSHOT` already uses this fix from AttoParser.

**Comment by dlvenable** [comment]
To clarify, in a build since 3.0.0.BETA1, the `script` tags should be able to have template replacements _if_ the `type` is a custom type, like `text/ng-template`?

**Comment by danielfernandez** [comment]
After `3.0.0.BETA01`. Yes.

See http://www.thymeleaf.org/faq.html#use-snapshot to learn how to use a snapshot, if you want to test it right now.
