### ISSUE TITLE
Pre-processing templates do not process include elements

### ISSUE THREAD

**Issue by dlvenable** [thymeleaf/thymeleaf#450]
I'm working with the new `IPreProcessor` plug-in capabilities. I have found that when I configure an `IPreProcessor` using an `IPreProcessorDialect`, the `ITemplateHandler` is not receiving any handle events for template fragments (`th:include`).

To clarify, the `IPreProcessor` does receive the `handleStandaloneElement` event for the element containing the `th:include`. But, it does not receive any more events until the next element in the top-level template.

**Comment by dlvenable** [comment]
Found in `3.0.0.BETA01`.

**Comment by danielfernandez** [comment]
Confirmed. This is the consequence of a limitation in the current processing mechanisms of the new architecture. Inserted fragments have their events directly injected into the processed template's event queues, instead of conforming separate (nested) execution calls. This significantly helps performance and reduces context-related memory overhead.

An alternative option could be evaluated: have `EngineEventQueue` apply preprocessors itself. But its effects on overall performance --if any-- should be measured first. Also, it should be taken into account how synthetic events (events not coming from the original templates) would be affected.

If negative effects overcome the benefits, this should be left out as an architectural limitation.

**Comment by dlvenable** [comment]
Thanks for the explanation. The basic problem makes sense and I see why it would be difficult to implement. Though I'm not familiar enough with the internals to understand the performance costs. In my opinion, if a Thymeleaf client wants a pre-processor, he would also want and expect that pre-processor to work on an entire template, including fragments.

**Comment by danielfernandez** [comment]
This should be fixed now. The `TemplateManager` has been modified so that pre-processors are not only applied to complete templates being processed, but also to fragments. And in any case _after_ caching so that pre-processors are applied always and what is cached is the result of merely parsing and not of parsing + pre-processing.

Besides, a modification on the general mechanism for pre- and post-processors has been applied in order to solve an issue with post-processors being applied twice to inlined code.

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`

**Comment by danielfernandez** [comment]
By the way, because of the way pre-processors and post-processors work as steps in the chain of handlers applied to templates/fragments (they are implementations of `ITemplateHandler`), and the fact that these chains cannot be _broken_, there will be different chains of pre-processors for a template and each of its inserted fragments. 

Therefore, _pre-processor instances will not be shared among templates and their fragments_. If any kind of information needs to be kept at the pre-processing phase across template and fragments, this information should be kept in the context.
