### ISSUE TITLE
Ampersand is wrongly escaped in href attribute.

### ISSUE THREAD

**Issue by harikk** [thymeleaf/thymeleaf#456]
This is related to #189 
But still not solved.

Thymeleaf seems to be escaping the & character while rendering the th::href attribute

as a comment to this issue @jmiguelsamper said

> Escaping ampersand inside an attribute is correct HTML.

If this is the case, how could I pass the following url?

http://example.com?id=20&somevar=content_with_&amp;rr=29

Here, I have only two parameters: id => 20 and somevar => `content_with_&amp;rr=29`

but according to the reply, it will have three parameters (id => 20, somevar => content_with_, rr =>29)

Also when I tried https://www.google.co.in/search?source=hp&amp;q=thymeleaf instead of https://www.google.co.in/search?source=hp&q=thymeleaf I got the wrong page.
So clearly, & is not same as &amp;  in urls.

So can you tell me how can I add & in urls with Thymeleaf?

**Comment by ultraq** [comment]
Having `&amp;` in the `href` attribute of a link is fine though as the browser will translate it when you hover over it or click it.  For example, view the HTML source of your own post and look at your own links.  GitHub has them as escaped, `<a href="https://www.google.co.in/search?source=hp&amp;q=thymeleaf">`, but on hover or click it appears as a normal &.

**Comment by harikk** [comment]
But when I click on the link you gave, it redirect me to https://www.google.co.in/webhp?source=hp

I am using Chrome 48.0.2564.97 m
Same behavior for Firefox 44

**Comment by ultraq** [comment]
Link I gave?  That was the source code of your own link that on the surface had a `&` but in the source used `&amp;`

Here's another example: http://codepen.io/ultraq/pen/KVxQqN

The underlying source uses an `&amp;`, but the browser translates it as if it were `&`

**Comment by harikk** [comment]
Browser may display it as an & but when you click on the link, browser wont translate &amp; to &.
Please have a look at the screenshot. At the bottom tooltip, it shows `&amp;`

![image](https://cloud.githubusercontent.com/assets/1871282/12814753/89d5bf8a-cb67-11e5-9ce2-ccad17e9be48.png)

**Comment by ultraq** [comment]
No, not the link on your Gmail - that won't work.  Come to this page in GitHub (Gmail is parsing the e-mail and getting the link wrong as that is monospaced code text on GitHub) and you'll get the behaviour I described.

The Pen that I linked you too works for me in Firefox and even Safari on iOS.  Try go to that page in your browser.

**Comment by harikk** [comment]
You are right. 
But I am using Thymeleaf for email templates.

So is there any solution for emails to show '&' instead of '&amp;'?

**Comment by danielfernandez** [comment]
There is no difference in how an URL inside an `href` attribute should be rendered in a web page or in an HTML email. In both cases we are talking about HTML and therefore any `&` characters inside an attribute (be it `href` or any others) should go escaped as `&amp;` (even if all modern browsers will allow unescaped `&` characters in URLs and won't break when they find one).

In this URL you mention:

```
http://example.com?id=20&somevar=content_with_&amp;rr=29
```

There are not two parameters, but three: `id`, `somevar` and `rr`. It doesn't really matter if those `&` separating parameters are escaped or not because, as I explained, browsers accept `&` characters both escaped (as they should) and unescaped.

Note however that both the names and the values of URL parameters must appear _URL-encoded_ in URLs. And URL-encoding is not HTML-escaping. Actually, the URL-encoded version of `&` is `%26`.

So if you need to pass a parameter value of `content_with_&amp;rr=29`, it should appear like this:

```
http://example.com?id=20&somevar=content_with_%26amp%3Brr=29
```

Note how the `;` character also needs to be URL-encoded.

**Comment by harikk** [comment]
But how do I solve the problem with emails?

**Comment by bhaskar-anil** [comment]
@harikk did you solve this? I am having similar issue!

I understand that escaping & into &amp; is correct way and it doesn't really change the actual url, but we use a system which reads the URLs and it doesn't work with escaped characters and I do not have any control over it.
