### ISSUE TITLE
th:switch cannot be combined with th:fragment

### ISSUE THREAD

**Issue by pcroc** [thymeleaf/thymeleaf#475]
The following template code causes an exception, using HTML5 template mode (Thymeleaf 2.1.4):

``` html
<th:block th:fragment="subscription" th:switch="${role}">
  <th:block th:case="'xxxx'"><span>xxxx</span> subscriber</th:block>
  <th:block th:case="'yyyy'"><span>yyyy</span> subscriber</th:block>
  <th:block th:case="'zzzz'"><span>zzzz</span></th:block>
</th:block>
```

**Cannot specify a "th:case" attribute in an environment where no switch operator has been defined before. (subscription.html:3)**

The only way to fix this is to move the th:switch into its own th:block inside the outer block.

If combining th:switch with th:fragment is not allowed, the exception message could be improved.

**Comment by danielfernandez** [comment]
The problem here is not really in the combination of `th:fragment` and `th:switch`, but in the fact that you are probably calling this fragment with a `th:include`.

`th:include` does not insert the entire fragment but only _its body_, i.e. what is inside the highest-level `<th:block>`. Which is why you end up having several tags with `th:case` that are inside anything with a `th:switch` and the exception arises.

You could solve this by using `th:replace` instead of `th:include` or, as you say, having an additional container tag.

Note that Thymeleaf 3.0 provides a new (recommended) attribute for fragment insertion, called `th:insert`, which simply inserts the entire fragment into the host tag (not only its body, and without replacing the host tag).
