### ISSUE TITLE
Custom attribute not being processed in th:block

### ISSUE THREAD

**Issue by juanitocalero** [thymeleaf/thymeleaf#485]
I've created a custom dialect for thymeleaf 3.0 (Using BETA02) with a simple attribute `when`, mixing `th:with` and `th:if` functionality.
It's based in th:with but If the resulting variable evaluates to false, it acts as `if` and removes the content.
It also understands Java 8 Optional, evaluating to the content if it is present.

[WhenTagProcessor.txt](https://github.com/thymeleaf/thymeleaf/files/208369/WhenTagProcessor.txt)

I'm testing it and works fine (is very useful to avoid repetitive nested th:with th:if) But if my custom attribute is placed in a `th:block`, my element processor is never called. The content is rendered and it fails when it encounters a variable.

I don't know if its a problem of my custom element processor. I would need a better understanding of the elements and attributes processing algorithm.

**Comment by outofrange** [comment]
Just wanted to report the same issue I had a while ago.

It also happens when HTML5 mode is used with NekoHTML - `th:if` (and `th:unless`) in `th:block`s is simply ignored.

Thymeleaf v2.1.4 is used with spring-boot v1.3.2 and NekoHTML v1.9.22.

**Comment by danielfernandez** [comment]
I've been unable to reproduce this issue, using your same code. There should be no reason why a custom processor inside a `th:block` is not processed. 

Most probably you have a precedence issue. I see the precedence of your processor is `600`, but if the _dialect precedence_ of your custom dialect makes everything in your dialect execute _after_ everything in the Standard Dialect (the Standard Dialect has _dialect precedence_ of `1000`), then by the time your custom processor should be executed the `<th:block>` itself would have executed its `StandardBlockTagProcessor`, which basically removes the `<th:block>` so that it does not appear on output. See `IProcessorDialect#getDialectProcessorPrecedence()`.

@outofrange your case is different. In Thymeleaf 2.1's `LEGACYHTML5` template mode (which does not exist anymore in Thymeleaf 3) nekoHTML will not correctly process `<th:block>` in some scenarios --depending on the location in the template-- and will auto-close them automatically as a part of its tag-balancing operation, thus making any `th:if` operate on nothing :-(. In those cases, the most adequate solution is to use a different template mode (and so avoid using nekoHTML) or simply try updating to Thymeleaf 3 ('s BETAs)
