### ISSUE TITLE
Removal of classes?

### ISSUE THREAD

**Issue by michael-t-moore** [thymeleaf/thymeleaf#502]
Migrating from 2.1.2 to 3.0.0 removed some classes that were used to manually render thymeleaf templates and store the result in a variable.  Specifically the classes IFragmentSpec and DOMSelectorFragmentSpec.  I could understand deprecating them if they are no longer used, but they are now completely gone from Thymeleaf 3.0.0.  Can you please advise on how this is to be done in 3.0.0?  Here is the code chunk that no longer works:

```
if(args.length > 1) {
    IFragmentSpec iFragmentSpec = new DOMSelectorFragmentSpec(args[1].trim());
    //process the template and return resulting html as string
    return templateEngine.process(args[0].trim(), iContext, iFragmentSpec);
}
```

**Comment by danielfernandez** [comment]
Thymeleaf 3.0 is a complete rewrite of the engine, which adopts a completely different architecture. While  compatibility of the template code is kept to the maximum extent possible, most APIs have changed and therefore many classes and methods have been modified and/or have simply disappeared.

When a new major version is published it is not always possible to go through a deprecation process for every upgraded API because that means basically keeping old code still working, and this might be simply impossible if the architecture has undergone a profound change. We are really sorry for that as we understand it means an inconvenience for some people creating extensions or using internal APIs, but that is precisely the reason why this is Thymeleaf 3.0 and not 2.2.

As for your specific code, the change is quite minor. There is no need to express _fragments_ as a separate object anymore, and you can simply use your _fragment specification_ (_selector_ in v3.0 jargon) as a `String`. Some methods in the `org.thymeleaf.ITemplateEngine` interface allow you to specify a `Set<String> templateSelectors`, which seems to be what you need:

``` java
if (args.length > 1) {
    //process the template and return resulting html as string
    return templateEngine.process(args[0], Collections.singleton(args[1]), iContext);
}
```

Please refer to the javadoc of the `ITemplateEngine` interface for more info: http://www.thymeleaf.org/apidocs/thymeleaf/3.0.0.RELEASE/
