### ISSUE TITLE
Variables defined in th:each not accessible

### ISSUE THREAD

**Issue by hbprotoss** [thymeleaf/thymeleaf#505]
I'm new to Thymeleaf, and I'm learning the example provided by official site [https://github.com/thymeleaf/thymeleafexamples-stsm.git](https://github.com/thymeleaf/thymeleafexamples-stsm.git)

A piece of template code in file `webapp/WEB-INF/seedstartermng.html`, line 118 to 131:

```
<tr th:each="row,rowStat : *{rows}">
  <td th:text="${rowStat.count}">1</td>
  <td>
    <select th:field="*{rows[__${rowStat.index}__].variety}">
      <option th:each="var : ${allVarieties}" th:value="${var.id}" th:text="${var.name}">Thymus Thymi</option>
    </select>
  </td>
  <td>
    <input type="text" th:field="*{rows[__${rowStat.index}__].seedsPerCell}" th:errorclass="fieldError" />
  </td>
  <td>
    <button type="submit" name="removeRow" th:value="${rowStat.index}" th:text="#{seedstarter.row.remove}">Remove row</button>
  </td>
</tr>
```

If I change the expression `*{rows[__${rowStat.index}__].variety}` to `${row.variety}`, it reports

```
 Neither BindingResult nor plain target object for bean name 'row' available as request attribute
```

and page rendering failed.

Is there any difference between the two expressions?

**Comment by danielfernandez** [comment]
The difference is, the `rows` variable was added to the Spring model in _controller time_, i.e. before the view layer was executed. This meant Spring created for it underneath a `BindingResult` object which basically allowed such object (`rows`) to be used for binding fields in a form (i.e. to be used as a _form-backing bean_).

However, `row` is not a variable created before calling the view layer. Instead, it was created by the view layer itself while executing the template. This means that Spring never created a `BindingResult` for it and thus is not able to perform _form-binding_ operations for this variable. That's why the _original_ `rows` is being referenced there.
