### ISSUE TITLE
bind fragment to dialect processor

### ISSUE THREAD

**Issue by hbprotoss** [thymeleaf/thymeleaf#506]
For example, a reusable `<header>` fragment for other pages to include. I want to show user info in the header after they log in. For now, I have to get user info from backend in every controller(or put the operations in a base controller to extend).

I'd like to ask if it is possible to bind a fragment to a dialect processor so that I can retrieve info in the processor to render page. Pages that include the `<header>` fragment never care about how to retrieve user info and how to render page. The only thing they have to do is to include the fragment.

From the examples provided by official site, I learn that `IModelFactory` can create html dom by java code, but how to load and render a template directly? Front end developer don't want to touch java code :-(

**Comment by danielfernandez** [comment]
If I'm understanding correctly, what you need is to create a _processor_ (triggered by a specific tag or attribute) in a new dialect so that whenever that processor is called, and that injects into the template a piece of HTML that includes data (user info) obtained from somewhere in your application.

However, both the process of creating a Thymeleaf processor _and_ the process of retrieving your user info are _Java code_, so I don't see how this could be done without touching java code. You are actually creating a piece of controller + view, not client-side code.

If you still want to create a processor, a good strategy could be doing something similar to what the `StandardConditionalCommentProcessor` does (which in turn is a somewhat similar, but hugely simplified version of what `th:insert` or `th:replace` do):
1. Parsing your template fragment into a `TemplateModel`: https://github.com/thymeleaf/thymeleaf/blob/24d9c3d76c0c2424650a33fc814c62e70a9858f2/src/main/java/org/thymeleaf/standard/processor/StandardConditionalCommentProcessor.java#L78-L83
2. Processing the model with an `IContext` containing your _user info_: https://github.com/thymeleaf/thymeleaf/blob/24d9c3d76c0c2424650a33fc814c62e70a9858f2/src/main/java/org/thymeleaf/standard/processor/StandardConditionalCommentProcessor.java#L98
3. Returning the result to be injected: https://github.com/thymeleaf/thymeleaf/blob/24d9c3d76c0c2424650a33fc814c62e70a9858f2/src/main/java/org/thymeleaf/standard/processor/StandardConditionalCommentProcessor.java#L110

That would allow you a lot of node creation with the `IModelFactory` and actually allow you to have your _common header_ HTML code as a separate template file in your classpath or maybe as a mere `String` constant somewhere.

And of course, the much simpler solution to all of this, if you are using Spring, is simply adding your _user info_ in your controllers with `@ModelAttribute`-annotated methods so that they are added to the model for all your controller methods. Something like https://github.com/thymeleaf/thymeleafexamples-stsm/blob/04f16ade4db7a42a0d219753d0a0de4e601a0d16/src/main/java/thymeleafexamples/stsm/web/controller/SeedStarterMngController.java#L61-L79

**Comment by hbprotoss** [comment]
@danielfernandez How can I add a variable to the context for templateManager to process?

**Comment by danielfernandez** [comment]
In your case I think your best option is to simply use the same `context` object you are receiving at the `process` method, similar to what `StandardConditionalCommentProcessor` does, but casting to `IEngineContext` (at that point, context will always be an _engine context_):

``` java
((IEngineContext)context).setVariable(name, value);
```

**Comment by hbprotoss** [comment]
I've made it work, thx :)
