### ISSUE TITLE
about binding List<String> value to textarea

### ISSUE THREAD

**Issue by lmtoo** [thymeleaf/thymeleaf#509]
I want to binding  List<String> value to textarea，one line one String element，so I use 
`<textarea  class="form-control" th:rows="${rows}" th:id="${id}" th:name="${id}" th:placeholder="${placeholder}" th:text="${#strings.listJoin(text,'\n')}"/>`
but the result is split by string "\n" not lineseparator,so I try to put this join logic to model object ,add a getter,and the result is right,so I think there is bug in the framework

**Comment by danielfernandez** [comment]
The `'...'` syntax in Thymeleaf expressions does not correspond to the meaning of `'...'` in Java. While in Java single quotes are meant to specify a _character_, in Thymeleaf expressions they are meant to specify a _text literal_ (like `'whatever you want to put here'`).

So what you are telling the expression engine there is that you actually want to join your strings using the _(backslash, letter n)_ literal. That's why you are receiving that output.

So you need to _actually write a line feed as the second parameter of that method_. I would recommend using the HTML-escaped version: `${#strings.listJoin(text, '&#10;')}`
