### ISSUE TITLE
document translate

### ISSUE THREAD

**Issue by qinliming** [thymeleaf/thymeleaf#510]
I want to translate the doc of thymeleaf to chinese
https://qinliming.gitbooks.io/thymeleaf_zh/content/

**Comment by danielfernandez** [comment]
Hello @qinliming 

I understand that you are volunteering for performing the translation of some Thymeleaf documentation to Chinese, right? Do you mean the tutorials? (what I can see in that link seems like the first paragraphs of the _Using Thymeleaf_ tutorial).

If so, please give us some time to update these docs to Thymeleaf 3.0 (two of the three tutorials are still based on 2.1) and then please contact us again so that we can establish a process for such work.

Thanks so much.

**Comment by qinliming** [comment]
@danielfernandez OK,i will wait for the  Thymeleaf 3.0 tutorials
