### ISSUE TITLE
Why is owner template part of the cache key?

### ISSUE THREAD

**Issue by tobiasflohre** [thymeleaf/thymeleaf#515]
If we reference one template from many templates we noticed that it's put into the cache for each template it is referenced from because the owner template is different. At least in our case that's not necessary and fills the cache unwanted. Why is that the case? Would it be safe to eliminate the owner template from the cache key (let's say in a cache repo facade for all reading and writing access)?

**Comment by danielfernandez** [comment]
In 3.0, the template resolution process (represented by `ITemplateResolver` and its implementations) was made more flexible.

Two main actions were taken: 1. Add a `Map` of template resolution attributes which could be used for _configuring_ template resolution for a specific template execution, and 2. Add the concept of `ownerTemplate` so that fragments could be resolved in a different way depending on the template from which the resolution order had originated.

This made resolution scenarios like _template multi-tenancy_ (disjoint sets of templates with equivalent structures served by the same application — e.g. some kind of blog/shop farm) possible, and also allowed for the correct resolution –and subsequent creation of _models_– of templates that were not really external templates, but `Strings` (this is the reason why the old `templateName` parameter name is now simply `template`) — `String` templates are not only those resolved by the `StringTemplateResolver`, but also the texts handled by `th:utext` and some others, which need to be converted to different `IText` model events depending not only on the template they are created (_owner_), but even the line+column offset in case they are called more than once in the same template.

So the reason why `ITemplateResolver` now includes the `ownerTemplate` is solving a lack of flexibility needed for some complex resolution scenarios and also allowing the engine (and its new event-based model) to use templates that are not really template resources, but actually the template contents themselves as `String`s.

And why does the `CacheKey` contain these (both the `ownerTemplate` and the `templateResolutionAttributes`)? Precisely because the cache key should contain all the parameters passed to the `ITemplateResolver` in order to make sure that the results of these resolutions –the templates– are univocally identified at the cache.

As for your question on removing this info at the cache implementation… hmmm… well, I suppose it should work, yes. At first thought I cannot find a reason why not. As long as the conversion of keys from the standard _owner-enabled_ implementations to your own _owner-disabled_ ones is deterministic so that _cache gets_ can always find what the _cache put_ set there…

**Comment by tobiasflohre** [comment]
Thanks!

**Comment by wwwqyhme** [comment]
Can you provide some examples ,It is hard to understand  @danielfernandez
