### ISSUE TITLE
Improper escaping of text ressource in TEXT templateMode.

### ISSUE THREAD

**Issue by prusik** [thymeleaf/thymeleaf#524]
In version Thymeleaf 3.0.0.RELEASE, using Spring Boot 1.4.0.RELEASE.

In my opinion, multilingual text is being improperly escaped for mode TemplateMode.TEXT. In my template there is a multilingual resource (spring messages.properties) that is escaped while being resolved. 

For example, if messages.properties contains 
    myresource=I'd like this to work 

When resolving #{myresource} in my template, the resulting text is "I&amp;#39;d like this to work". Since we are in textual mode, this string should not be escaped and be returned with a standard apostrophe.

Caused by this code:
class: org.thymeleaf.standard.processor.StandardTextTagProcessor
method: produceEscapedOutput
code:
       switch (templateMode) {
            case TEXT:
                // fall-through
            case HTML:
                return HtmlEscape.escapeHtml4Xml(input);
          ...
       }

Two suggestions
1. either return input string as-is (case TEXT: return input;)
2. or offer the option through a global application property to escape, with a default value keeping the current behaviour.

**Comment by danielfernandez** [comment]
This is intended behaviour. This was designed like that in order to: 1. Support the rendering of HTML templates in `TEXT` mode for performance or style reasons; and 2. Provide backwards-compatibility with `th:inline="text"` markup fragments still allowed in 3.0, and used quite often in Thymeleaf 2.1 setups.

Note that the `TEXT` template mode, like all other textual template modes –and also all inlining modes in markup modes– offers an _unescaped_ variant, which does precisely what you need. So instead of:

```
This is my text: [[#{myresource}]]
```

You should be using:

```
This is my text: [(#{myresource})]
```

And no escaping will be performed at all.

**Comment by prusik** [comment]
Oh, good to know, missed that one! Thanks for the reply.

shaun
