### ISSUE TITLE
th:classappend creates at least 1 whitespace 

### ISSUE THREAD

**Issue by stefluhh** [thymeleaf/thymeleaf#525]
Hi,
this is my code:
`<a th:fragment="href-link" class="link--alpha" href="#" ontouchstart
        th:classappend="${link.iconLink} ? ${'--icon ' + link.iconName}">
</a>`

And this is the output:
`<a class="link--alpha --icon facebook" href="#" ontouchstart></a>`
I suppose there shouldn't be a whitespace beetn link--alpha and --icon facebook, or? I also tried this:

`th:classappend="${link.iconLink}?${'--icon ' + link.iconName}"`

Where does the whitespace come from?

Kind regards,

Stefano

**Comment by danielfernandez** [comment]
This is the intended behaviour. `th:classappend` is supposed to append classes to elements, and it needs a whitespace in order to actually do that without modifying the values already existing at the `class` attribute.

If you want to append in a _raw_ fashion, without this _intelligence_ associated to a `class` attribute, I would recommend using `th:attrappend` and specifyig the `class` attribute as a target.
