### ISSUE TITLE
Parsing Error when declaring an nested array in embeded js inside the page file

### ISSUE THREAD

**Issue by CodePlayer7** [thymeleaf/thymeleaf#528]
as long as the below code is added to the page

```
 <script>
    var i = [[1,2],[1,2]];
 </script>
```

**Comment by danielfernandez** [comment]
This conflicts with Thymeleaf _inlined expression_ syntax, which is active by default since Thymeleaf 3.0. Inlined expressions are specified between double brackets, like `[[...]]`.

In order to overcome this, all you have to do is add a whitespace between your brackets. It is perfectly valid JavaScript syntax, and Thymeleaf's parser will not complain:

``` html
<script>
   var i = [ [1,2],[1,2] ];
</script>
```
