### ISSUE TITLE
Error resolving templates that are empty or just have a Thymeleaf comment

### ISSUE THREAD

**Issue by cja769** [thymeleaf/thymeleaf#529]
In Thymeleaf 2.1.4, if a template resolver returned a valid file location the template was returned regardless if there was any contents in it or not. In Thymeleaf 3 this is not true. If the file returned is empty or if there was only a Thymeleaf comment (i.e. after parsing the file was empty) then an error is thrown saying that the template could not be resolved just as if the file didn't exist even though the file does exist. I found that simply adding a newline in the template file fixes the problem.

**Comment by danielfernandez** [comment]
That is intended behaviour in 3.0, due to a series of required interactions in the way the new _Fragment expressions_ (`~{...}`) work (even if you don't use the `~{...}` syntax, your `th:include`, `th:insert` and `th:replace` attribute value will be considered a fragment expression).

Given fragments have now been given _first-class citizen_ status, the absence of anything to be inserted is considered a `null` result by the fragment expression and thus will give the result you see (an exception) unless you specifically allow your expression to deal with it.

And how to deal with an empty template in this case? easy, using a _default expression_ (`?:`) and the _empty fragment_ (`~{}`) as default value. The _empty fragment_ `~{}` is now the only fragment allowed to be really _empty_:

``` html
<div th:insert="~{mytemplate :: myfragment} ?: ~{}">...</div>
```

**Comment by cja769** [comment]
Ok just making sure that it was intended. I was actually running into this because we have this idea of overriding templates. Take for an example a template named `layout/partials/preFooterContent`. We have a default template resolver that returns just an empty template. If some other module or piece of extended code wants to put something there then their template resolver would have a higher precedence and would have to just implement `layout/partials/preFooterContent`. I know it seems odd but that's how we have it. Thanks for clarifying. I just added a new line with more comments explaining why there's a new line.
