### ISSUE TITLE
customizable escaping functions would be nice

### ISSUE THREAD

**Issue by anschnapp** [thymeleaf/thymeleaf#531]
I need some special escaping for my html templates.
In fact they are angularjs templates and so my code is potential vulnerable for client site template injections in angular. (yes maybe mixing server templates with client site templates is not a good idea but there is no fast way to change it in the related codebase)

I've make a very special escaping for handle this problem. But for now it's really invasive to change the escaping for standard processors like th:text. (i have to write a own one with the same logic but another escaping).

It will be much more convenient if the escaping functions for the different template modes are customizable (use of a strategy pattern approach).

I think there will be more cases where it is meaningful to use another escaping as the default escaping (f.e. a sanitizer which uses a tag-whitelist for utext in html)

**Comment by danielfernandez** [comment]
`th:text` currently applies the escaping mechanisms that correspond to each of the different template modes: HTML, XML, JAVASCRIPT, etc.

Being `th:text` a core tag in the Standard Dialect, and its already-existing adaptation to each of the template modes, I would not agree to making its behaviour modifiable by means of configuration, as the result of that would IMHO be that `th:text` would no longer apply the escaping mechanism corresponding to its template mode, or at least would do it in a non-predictable way which would make Thymeleaf code less immediately understandable.

So, in my opinion, this is a clear scenario for a custom processor, just like the one you created.

Anyway, this said, I'm interested in what you comment on your template code being vulnerable to client-side injection because of the mix of server- and client-side code. Could you elaborate a bit more on this, please? Maybe you are including AngularJS code as context variables and creating parts of your templates with `th:utext`?

**Comment by anschnapp** [comment]
Yes you are right, the th:text with template mode html should have the standard escaping for html.

My code is vulnerable for client side template injections with just "normal" use of th:text.
Here is a snippet just for illustration:

```
<html ng-app="app">
...
<div th:text=#{keyOfNotFullTrustedMessage}/>
...
```

If the resolved message has a value 

```
{{'1' === '1' : '1' ? '2'}}
```

The expression will be interpreted by angular and the displayed result is 1.
Normal escaping f.e. of the character '{' will not help here cause the html entity encodings are already interpreted before angular is going to evaluate the expression.

This is a real good article about client side template injection with angularJS and the possibility to break out from the angularjs expression sandbox mechanism:
http://blog.portswigger.net/2016/01/xss-without-html-client-side-template.html

My escaping function is trying to figure out if there is a angular expression and wrapped the code with with a tag with an ng-non-bindable attribute.

For illustrating this is the result after thymeleaf processing:

```
<span ng-non-bindable>{{'1' === '1' : '1' ? '2'}}</span>
```

Then the browser would display {{'1' === '1' : '1' ? '2'}}

I think there are in general two ways to handle this problem. First one is to say that server and client side templates are not allowed to be mixed. But the usage of mixing them are not uncommon as far as i know.
Second one is to try to apply a valid "escaping" mechanism. Then it would be great if a server template engine like thymeleaf has the possibility to add a special template type with escaping behavior for the related client side template language. In my case this could be something like "AngularTemplate"

**Comment by danielfernandez** [comment]
I understand.

> I think there are in general two ways to handle this problem. First one is to say that server and client side templates are not allowed to be mixed. But the usage of mixing them are not uncommon as far as i know.

In my opinion the mix of server- and client-side templates is not the real issue here, as you could be experiencing this same code injection scenario in client-side-only templates with, for instance, values coming from user input as request parameters (precisely, that's what the article you link explains).

I think mixing server- and client-side templates is actually a very useful tool, and that a low-HTML-intrusion template engine such as Thymeleaf adds value in terms of the flexibility needed to do this successfully.

> Second one is to try to apply a valid "escaping" mechanism. Then it would be great if a server template engine like thymeleaf has the possibility to add a special template type with escaping behavior for the related client side template language. In my case this could be something like "AngularTemplate"

In this case I would definitely recommend to create a Thymeleaf custom dialect with, either an expression utility object allowing things like `#angular.escape(...)` which could be used in regular `th:text`/`th:utext`, or specific attributes such as `angular:text="..."` that would perform angular-specific escaping (or automatic wrapping of output in `<span ng-non-bindable>...</span>` elements). I think I prefer the latter option for the sake of clarity, but I also see advantages in the former.

Many thanks for all the interesting explanations. For now, I think I can close this as a Thymeleaf support ticket. Please don't hesitate re-opening it in case you think there is anything else that should be done at the Thymeleaf side.

**Comment by anschnapp** [comment]
I agree that a custom expression or a own dialect is a proper solution here and i will use this approach.

But personaly I would prefer a way to handle it as an Template Mode cause in my opinion it is anoher type of template and it would be great to reuse the standard dialogs and such already implemented mechanism like lazy escaping. But I also see that the API is not designed to provide an easy way to add new template modes (without changing the core implementions).

> In my opinion the mix of server- and client-side templates is not the real issue here, as you could be experiencing this same code injection scenario in client-side-only templates with, for instance, values coming from user input as request parameters (precisely, that's what the article you link explains).

In my opinion it is a issue of server and client side template mix. Request parameters which are handled inside of a client template don't (normaly, there can be exceptions in special cases) write template code. Instead they are handled by the client side template engine and could be placed inside the view (possible danger here is normal XSS but not client side template injections, and XSS is normaly prevented by the client side templae engine).

The example in the link describes a server side PHP processing (server side "templating") which created the angular template. And at this step an angular expression can be injected. On client site template processing the expression will be evaluated from angularjs and there the sandbox exploit will take effect.
