### ISSUE TITLE
th:if Closing tag isnt removed

### ISSUE THREAD

**Issue by benkuly** [thymeleaf/thymeleaf#535]
I use Thymeleaf (3.0.1.RELEASE) with Spring Boot (4.0.1.RELEASE). The th:if attribute (e.g. `<hr th:if="${false}"></hr>` and `<input th:if="${false}"></input>`) does not remove the closing tag when false (e.g. `</hr> and </input>` in processed html). I tried this with autoconfigured Spring Boot and manualy:
`engine = new TemplateEngine();
engine.clearDialects();
StandardDialect std = new StandardDialect();
engine.addDialect("q", std);
StringTemplateResolver templateResolver = new StringTemplateResolver();
templateResolver.setTemplateMode(TemplateMode.HTML);
engine.setTemplateResolver(templateResolver);`

**Comment by danielfernandez** [comment]
This is correct behaviour when Thymeleaf 3 works in HTML mode. 

According to the HTML specification, both `<th>` and `<input>` are _void_ tags, they have no body. The _elements_ on which your `th:if`s are applied end in the `>` character of the tags they live in.

So `</input>` and `</hr>` do not really exist and are not considered related to `<input>` or `<hr>`. Instead, they are considered _unmatched close tags_, invalid markup.

Note this behaviour would have worked like you describe in 2.1 because 2.1 used XML parsers, and therefore it was not possible to respect these HTML specificities.
