### ISSUE TITLE
Local variables in th:object attributes

### ISSUE THREAD

**Issue by ruszki** [thymeleaf/thymeleaf#540]
When a selection (*{}) is used in an expression (e.g. th:field="*{something}"), it's resolution will be the content of th:object concatenated with selection's value (e.g. if th:object="${object.objectField}", then th:field="*{field}" will be resolved to "${object.objectField.field}"). If a local variable is used in the object definition, then it won't be resolved properly. Example:

``` html
<div th:with="variable=${object}">
    <form th:object="${variable.field}">
        <input type="text" th:field="*{innerField}" />
    </form>
</div>
```

Then th:field's value will incorrectly be transformed into "$(variable.field.innerField)", which will be thrown an exception, because "variable" isn't available.

**Comment by danielfernandez** [comment]
This is expected behaviour. In order to properly use a context variable as a form-backing bean, such variable must be added to the `ModelMap` so that Spring is able to recognize it.

In your case, however, `th:with` is creating a _local variable_ that is only available inside your `<div>` tag, a thymeleaf-specific feature that is not later accessible by Spring when performing the real binding (Spring's model does not know about variable _locality_ during template processing).
