### ISSUE TITLE
`<p>` with `<form>` inside + `th:if` is rendered when it should not be

### ISSUE THREAD

**Issue by damienbeaufils** [thymeleaf/thymeleaf#543]
Hello,

I am still migrating my web application from Thymeleaf 2.x to 3.0.2, and I encountered another issue with one of my templates: I had a `<p th:if="${someCondition}"><form>xxx</form></p>` which is rendered even when `${someCondition}` is `false`. If I change the `<p>` to a `<div>` or a `<th:block>`, it works fine.

Here is an example to reproduce it (tested with Thymeleaf 3.0.2):

Template:

```
<div class="content">
  <div>some text before</div>
  <th:block th:if="${false}">
    <form th:action="@{/some-url}" method="post">this form inside th:block should not be visible</form>
  </th:block>
  <div th:if="${false}">
    <form th:action="@{/some-url}" method="post">this form inside div should not be visible</form>
  </div>
  <p th:if="${false}">
    <form th:action="@{/some-url}" method="post">this form inside p should not be visible</form>
  </p>
  <div>some text after</div>
</div>
```

Result:

```
<div class="content">
  <div>some text before</div>
  <form action="https://localhost:9090/some-url" method="post">this form inside p should not be visible</form>
  </p>
  <div>some text after</div>
</div>
```

Expected:

```
<div class="content">
  <div>some text before</div>
  <div>some text after</div>
</div>
```

or a `ParseException`

Let me know if I can provide you any additional information.
Thank you!

**Comment by danielfernandez** [comment]
Actually, this is expected and correct behaviour. And I'll explain:

According to the HTML specification, a `<form>` tag cannot live inside a `<p>` element. So what Thymeleaf's HTML parser is doing is to _auto-close_ your `<p>` element as soon as it encounters `<form>`. So this code:

``` html
  <p th:if="${false}">
    <form th:action="@{/some-url}" method="post">this form inside p should not be visible</form>
  </p>
```

…actually looks like this to Thymeleaf:

``` html
  <p th:if="${false}">
    </p><form th:action="@{/some-url}" method="post">this form inside p should not be visible</form>
  </p> <!-- This is just an unmatched close tag, closing nothing -->
```

And that is precisely why you see that behaviour, because `th:if` is only applying on the _real_ `<p>` element. Which ends just before `<form>` starts.

**Comment by ultraq** [comment]
Gah, you beat me to it @danielfernandez 😛 

Reference: https://html.spec.whatwg.org/multipage/semantics.html#the-p-element

> A `p` element's end tag can be omitted if the p element is immediately followed by an [...] `form` [...]

**Comment by damienbeaufils** [comment]
Thanks for your quick answers and explanations! That's what I was afraid of. ;-)
It seems that Thymeleaf 2.x didn't care about this, and it can be a breaking change for users like me who had invalid HTML inside their templates.

**Comment by danielfernandez** [comment]
Yes, Thymeleaf 2.1 didn't actually have the possibility to understand things like these, because it was based on an XML parser (as were all previous versions of Thymeleaf). For Thymeleaf 3.0, we developed AttoParser in order to have a _real_ HTML parser to do the job, with complete HTML5 support. So this is actually more a _fix_ than a change in behaviour…
