### ISSUE TITLE
How to properly use dialect precedence?

### ISSUE THREAD

**Issue by sedooe** [thymeleaf/thymeleaf#547]
Hello,

I'm creating a custom dialect and I want an upperside HTML element to be processed after a downside HTML element. Let's say I want **head** tag to be processed after **div** tag. How can I do this?...or is this possible at all?

I assumed that for the same dialect it is impossible and created a second dialect which have higher precedence so I expected its processors to be executed first but I was wrong.

**Comment by danielfernandez** [comment]
Please note the _precedence_ mechanism affects the order in which processors are executed inside a specific host tag, not in the template as a whole. So the order and hierarchy in which tags appear in the template has more influence than any of this.

Actually, Thymeleaf by default works as if it were a _stream_, so by the time your `<div>` gets processed it is actually possible that your `<head>` tag has already been output and even reached the browser.

If we are talking about Thymeleaf 3.0, the way you have to do what you want is to create a _Model Processor_ (not a _Tag Processor_) for some element that contains both your `<head>` and your `<div>` –though I'm afraid it looks like it would have to be the `<html>` itself–. Model Processors actually _cache_ the entire model of the matching elements (in this case `<html>`, so it would cache almost the entire template) and offers it to you as an argument of the processor's `process` method so that you can look for all the information you need at whichever level of hierarchy.

**Comment by sedooe** [comment]
Thanks Daniel.
