### ISSUE TITLE
Inline expression write a error th:block tag

### ISSUE THREAD

**Issue by JeryZeng** [thymeleaf/thymeleaf#549]
thymeleaf transform a inline expression as a th:block tag ,but this tag write as a incorrety text,such as `[[${title}]]`:
`<th:blockth:text="${title}">`
but should be:
`<th:block th:text="${title}">`

**Comment by danielfernandez** [comment]
That is expected behaviour. Those `<th:block>` are synthetically generated at parsing time, and will disappear at processing time, so they should never get to template output. The only way you will see this `<th:blockth:text="${title}">` is if you take one of these tags and do `.toString()` on them inside a processor or pre-processor.

But this doesn't mean the event is not correctly formed: the tag has its `th:block` name, and the `th:text` attribute is there and will work OK. The reason there is no white space _in the string representation_ of these elements between the tag name and the attribute is because inner white spaces are a _display-only_ structures, and given these elements are never meant to be displayed, Thymeleaf simply saves some structural complexity by simply not adding white space to this _synthetic_ elements.

**Comment by JeryZeng** [comment]
Yeah ... but I think it's still a problem.The Engine should always transofrm any expression correctly.that's right?

**Comment by danielfernandez** [comment]
The expression is being correctly transformed into an `IStandaloneElement` object of name `th:block` that correctly contains a `th:text` attribute with value `${title}`.

What you observe is just the lack of a white space internal structure, which will only show if you execute `toString()` on it during the processing phase, before the element is removed (which is always its fate). This lack of white space was done on purpose, and simply saves a bit of complexity in an element structure that, at this point of processing, has no use at all for white space. 

However, I might be missing your point here: could you please explain how is this harming you?

**Comment by JeryZeng** [comment]
OK.I just have a little bit confusion ,because my requirement is reading some block and write to another files to be some new template module.But i just change my implements.So let it go.
Thanks for ur explanation
