### ISSUE TITLE
BEM and Thymeleaf don't play nicely together

### ISSUE THREAD

**Issue by yvanavermaet** [thymeleaf/thymeleaf#550]
Dear

Thymeleaf version: 2.1.4 and 3.0.2

The following html will throw an error due to __ being used.

``` html
<div th:classappend="${true ? 'my__bem--class' : 'my__bem--otherclass'}">
    My Div
</div>
```

I've read a similar issue that was closed as "won't fix", however it should be fixed imo. Thymeleaf is a templating engine and should be able to deal with the BEM standard (or any other standard for that matter). 
I know __ is used for preprocessing, however it shouldn't matter when it appears inside a string as shown in the example above.

Kind regards,
Yannick

**Comment by danielfernandez** [comment]
IMO there is actually nothing to fix here. The reason is, the syntax for Thymeleaf Standard Expressions considers `__` the marker for pre-processing, but offers an escape sequence for it: `\_\_`. Your code will work perfectly if you apply the escape sequence to the value of your `th:classappend` attribute:

``` html
<div th:classappend="${true ? 'my\_\_bem--class' : 'my\_\_bem--otherclass'}">
    My Div
</div>
```

The result will be:

``` html
<div class="my__bem--class">
    My Div
</div>
```

**Comment by yvanavermaet** [comment]
Hi Daniel

I'm aware of the solution as we are currently using this.

I do feel like this is a bug with the specific example. The HTML example below doesn't have a problem with __, however when it's in a condition (as shown in my previous example) it's a problem. In both cases the __ is present in a string.

``` html
<div th:classappend="${'my__bem--class'}">
    My Div
</div>
```

There is another reason why this is annoying. It's just harder to find a certain file. Often you check a class in the console and if it contains a '__' (which all classes contain), it's annoying to search for "my__bem--class" first and then search for 'my\_\_bem--class"

This might sound normal/as regular behaviour for you as a backend/core-developer, but to a frontend developer, this is bananas.

Thanks for your reply btw

Kind regards,
Yannick

**Comment by danielfernandez** [comment]
> I do feel like this is a bug with the specific example. The HTML example below doesn't have a problem with __, however when it's in a condition (as shown in my previous example) it's a problem. In both cases the __ is present in a string.

The difference is in the amount of times `__` appears. Pre-processing expressions are _delimited_ by `__`. In your conditional, the `__` appears twice, so the parser feels there is a _delimitation of something_. However, in your example without a conditional there is no _delimitation_, and therefore it works without the need to escape. The specific fact that there is a conditional doesn't affect at all, because pre-processing structures are identified (and executed) before parsing the Thymeleaf Standard Expressions underneath, so by the time Thymeleaf identifies your `th:classappend` value as a pre-processing expression it doesn't know there is a conditional yet.

> There is another reason why this is annoying. It's just harder to find a certain file. Often you check a class in the console and if it contains a '__' (which all classes contain), it's annoying to search for "my__bem--class" first and then search for 'my__bem--class"

I'm sorry for that, but note that in this case we are talking about `th:classappend` attributes, which are Thymeleaf-specific and their value has to adhere to the syntax of Thymeleaf Standard Expressions (including pre-processing). Note standard HTML `class` attributes are not affected by this because they are not parsed by Thymeleaf.

The syntax of Thymeleaf Standard Expressions is defined in a way that it tries to have the greatest compatibility level with the host HTML language, but of course there can always appear some kinds of collisions with other syntaxes defined by the hundreds of technologies that can be applied on top of HTML. And the way to solve these collisions is by means of escaping. 

Just like JavaScript or CSS will make you escape their `</` sequences in `<script>` and `<style>` tags, or in the same way HTML-escaping is needed in HTML texts for representing HTML-significative characters, Thymeleaf will ask you to escape this sequence, which is _Thymeleaf-significative_, when used inside Thymeleaf-specific constructs (like `th:classappend`). 

So even if I do understand how this might be a bit annoying for your specific workflow in the way you describe it, in all honesty I believe Thymeleaf's behaviour is actually quite fair.
