### ISSUE TITLE
th:utext html overflow inside

### ISSUE THREAD

**Issue by mrdear** [thymeleaf/thymeleaf#556]
when I use this like 
`<p th:id="${comment.getId()}+'content'" th:utext="${comment.content}" >`

but parse

```
<p id="2content">简单运行下就好了
</p>
<pre><code>
 try {
		    return sdfyhm.parse(source);
	    } catch (ParseException e) {
		    e.printStackTrace();
		    return new Date();
	    }
</code></pre><p></p>
```

`${comment.content}` include html language

**Comment by danielfernandez** [comment]
Sorry, I'm not sure I understand your issue here… what is exactly what you are obtaining that you think you shouldn't? could you please elaborate a bit?

**Comment by mrdear** [comment]
sorry,I use it this way `<p th:id="${comment.getId()}+'content'" th:utext="${comment.content}" ></p>`
I want to get results like the following(the  ${comment.content} parsed Inside the p tag)

```
<p id="2content">
简单运行下就好了
<pre><code>
 try {
            return sdfyhm.parse(source);
        } catch (ParseException e) {
            e.printStackTrace();
            return new Date();
        }
</code></pre><p></p>
</p>
```

but it is actually parsed like this(The content is outside the p tag)

```
<p id="2content">简单运行下就好了
</p>
<pre><code>
 try {
            return sdfyhm.parse(source);
        } catch (ParseException e) {
            e.printStackTrace();
            return new Date();
        }
</code></pre><p></p>
```

my database saved  like Following
This is also the data for $ {comment.content}

```
简单运行下就好了
<pre><code>
 try {
            return sdfyhm.parse(source);
        } catch (ParseException e) {
            e.printStackTrace();
            return new Date();
        }
</code></pre>
```

**Comment by danielfernandez** [comment]
OK. I'm quite sure Thymeleaf is not causing this at all (at least its core and standard dialects). With your code and your database values, Thymeleaf's output should look like:

``` html
<p id="2content">简单运行下就好了
<pre><code>
 try {
            return sdfyhm.parse(source);
        } catch (ParseException e) {
            e.printStackTrace();
            return new Date();
        }
</code></pre></p>
```

However, once this is produced something in your application seems to be applying a _tag balancer_ or some kind of _HTML validator_. 

And this tag balancer/validator is detecting that your code is not valid HTML because a `<pre>` tag cannot live inside a `<p>` one, so it is auto-closing your `<p>` before the `<pre>`, and then auto-opening a new `<p>` after `</pre>` so that it matches your existing `</p>`.

The only way I see this happening through Thymeleaf is that you are applying it _twice_, the second time on the result of the first one, and additionallt that you are using the `LEGACTYHTML5` template mode (which will apply a tag balancer _before_ Thymeleaf executes the second time).

**Comment by mrdear** [comment]
Thanks for the solution.
you are right,It is caused by my browser . When I use chrome or firefox, there will be problems, but the use of Microsoft Edge on the normal resolution.
