### ISSUE TITLE
Ampersand from Context is encoded as "&amp;" when TemplateMode is set to TEXT

### ISSUE THREAD

**Issue by trurli** [thymeleaf/thymeleaf#569]
When using Thymeleaf 3.0.0 with a TemplateResolver set to TemplateMode.TEXT, a variable value from a Context that contains "&" appears as "& a m p ;" instead of "&" in the processed output.

I would expect that HTML entities are not treated for the TEXT template mode.

Found this, when I used the sample template from http://www.thymeleaf.org/doc/articles/springmail.html and added "fun & games" as my hobby.

Keep up the good work!

**Comment by danielfernandez** [comment]
This is actually expected behaviour, as explained at http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#escaped-element-attributes

The idea is that `TEXT` mode could be used in some specific scenarios to create HTML output, without needing the engine to parse the HTML and process it as such (losing quite a lot of features in doing so, of course).

However, note that you can perform unescaped output in `TEXT` mode, simply by using the bracket-parenthesis syntax: `[(${whatever})]`

**Comment by danielfernandez** [comment]
I've added tickets for the sample application and also the doc, so that the example that you used as a base is fixed. It should be using unescaped output.
