### ISSUE TITLE
Spring Session alias inclusion for link URL expressions

### ISSUE THREAD

**Issue by yglodt** [thymeleaf/thymeleaf#571]
Spring Session takes care of adding the current session alias if the jstl c-taglib (c:url) is used, with help of  HttpServletResponse#encodeURL().

Example:

```
<a href='<c:url value="/link.jsp" />'>Link</a>
```
will output:

```
<a href="/link.jsp?_s=1">Link</a>`
```

You can read more about how it's done here: http://docs.spring.io/spring-session/docs/current/reference/html5/#httpsession-multi

Thymeleaf does not seem to support that when url expressions like 

> @{/path}

 are used.

It would be nice it that would be added :-)

**Comment by danielfernandez** [comment]
Thymeleaf does indeed call the `HttpServletResponse#encodeURL()` mechanism before outputting an URL, see https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/linkbuilder/StandardLinkBuilder.java#L521-L530

But note that in order to do this, it has to have access to such `HttpServletResponse`, which it does by means of the context being an implementation of `IWebContext`. If you are using Thymeleaf as a Spring MVC view this happens automatically, but if you are calling Thymeleaf programmatically from your code this might not be the case. Could you please confirm if this is your case?

**Comment by yglodt** [comment]
The project in which I noticed that the session alias is not included is Spring-Boot 1.5.1 based.

I am not sure a Spring Boot application has a "normal" web context...

My own code does not call Thymeleaf programmatically, but maybe Spring Boot does.

**Comment by danielfernandez** [comment]
Spring Boot does indeed call Thymeleaf as a Spring View. So the `HttpServletResponse#encodeURL()` mechanism is most certainly being called for you.

Perhaps you could debug on the line I pointed just to be sure, and make sure Spring Session's configuration is actually making it inject the behaviour you are expecting into the URL encoding mechanism.

**Comment by yglodt** [comment]
Ok, I will try to debug it the weekend.

**Comment by danielfernandez** [comment]
Any news?

**Comment by danielfernandez** [comment]
Closing this for now as *non reproducible*. Please don't hesitate to reopen it in the future if you are able to get further information on it.
