### ISSUE TITLE
Malformed markup: Attribute "" appears more than once in element

### ISSUE THREAD

**Issue by fredhdroz** [thymeleaf/thymeleaf#572]
I try to include an html text in my page using th:utext (Thymeleaf 3), but the parser detect duplicate attributes and throw an exception. Unfortunately I've got no possibility to validate the th:utext value before.

> Exception :
> org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/template.html]")
> 	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:241) ~[thymeleaf-3.0.3.RELEASE.jar:3.0.3.RELEASE]
> 	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parseStandalone(AbstractMarkupTemplateParser.java:100) ~[thymeleaf-3.0.3.RELEASE.jar:3.0.3.RELEASE]
> 	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:667) ~[thymeleaf-3.0.3.RELEASE.jar:3.0.3.RELEASE]
> 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098) ~[thymeleaf-3.0.3.RELEASE.jar:3.0.3.RELEASE]
> 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1072) ~[thymeleaf-3.0.3.RELEASE.jar:3.0.3.RELEASE]
> 	at org.thymeleaf.spring4.view.ThymeleafView.renderFragment(ThymeleafView.java:335) ~[thymeleaf-spring4-3.0.3.RELEASE.jar:3.0.3.RELEASE]
> 	at org.thymeleaf.spring4.view.ThymeleafView.render(ThymeleafView.java:189) ~[thymeleaf-spring4-3.0.3.RELEASE.jar:3.0.3.RELEASE]

> Caused by: org.attoparser.ParseException Malformed markup: Attribute "..." appears more than once in element
> 

I've seen the org.thymeleaf.templateparser.markup.HTMLTemplateParser has a default ParseConfiguration

`MARKUP_PARSING_CONFIGURATION.setUniqueAttributesInElementRequired(true);`

How can I override this behaviour specifically for th:utext ?

**Comment by danielfernandez** [comment]
This is expected behaviour. When you output something as *unescaped* via `th:utext`, the parser should still apply on the inserted code in order to give a chance to possible *postprocessors* to hook on the newly created markup events.

Customizing the parser being used is not currently possible in Thymeleaf 3. Even if AttoParser does indeed allow to disable the restriction for the unicity of attributes, doing this could be an issue for Thymeleaf, leading to unexpected results in the execution of processors.

In your case, there is a way in which you can work around the parser's checks. Note however that disabling the parser is *dangerous* in the sense that the HTML markup that you would be inserting could break your entire document structure, so I'd strongly advise instead for a previous *sanitization* of the code you are inserting, done apart (actually, at storage time, if this comes from a data store).

Anyway, the idea to disable the parser would be to tell Thymeleaf to enable inlining into `TEXT` mode for a specific tag, and then inside the body of that tag use an *unescaped inlined output expression* `[(...)]` which, being in `TEXT` mode, will not apply any parsers:

```html
<div th:inline="text">[(${mycontent})]</div>
```

**Comment by daggerok** [comment]
Hello there

@danielfernandez , facing with same issue. thymeleaf failing with message: 

```
Caused by: org.attoparser.ParseException: (Line = 18410, Column = 51) Malformed markup: Attribute "data-v-4ac5acc0" appears more than once in element
```

![image](https://user-images.githubusercontent.com/2445604/71201104-04df2280-22a2-11ea-88ab-dd17a703708e.png)

can you please tell me how I can workaround this. some of my html gets generated and I have to deal somehow with duplicated data-xxx attributes.

Thanks

---
Regards,
Maksim

**Comment by mahmud624683** [comment]
Did find any solution for this?

**Comment by ferdibulus** [comment]
The exception will give the line # in the html where the error is occurring... in any case, the actual problem is here:

<div class="container" class="row">
Thymeleaf won't allow an element to have two attributes with the same name (Attribute "class" appears more than once in element). Just change it to:

<div class="container row">

**Comment by ferdibulus** [comment]
The exception will give the line # in the html where the error is occurring... in any case, the actual problem is here:

`<div class="container" class="row">`
Thymeleaf won't allow an element to have two attributes with the same name (Attribute "class" appears more than once in element). Just change it to:

`<div class="container row">`

**Comment by mohamedHedi1990** [comment]
this error is most likely due to an unclosed attribute and as a result it generated a problem in the whole html template. So, check your html file.
