### ISSUE TITLE
About 'th:onclick' add a function with an parameter

### ISSUE THREAD

**Issue by Idiot-Alex** [thymeleaf/thymeleaf#574]
recently, I used the thyeamleaf for developing my project, I want to add a function for ‘a’ label and with an parameter, but it doesn't work. just like this:
>html code
```
<nav th:each="item : ${list}">
    <li><h2 th:text="*{item.title}">基本元素</h2></li>
    <section th:each="data : *{item.list}">
        <li class="site-tree-noicon layui-this">
            <a th:href="*{data.path}" th:onclick="'loadContent('+ *{data.path} +')'">
           <cite th:text="*{data.title}">idiot</cite></a>
        </li>
    </section>
</nav>
```
>javascript code
```
<script type="text/javascript">
            function loadContent(url) {
                console.log(url)
            }
</script>
```
this is form the chrome's console, but the result is like this:
```
<a href="pages/test.html" onclick="loadContent(pages/test.html)"><cite>字符串</cite></a>
```
it can't exec the function and throw an error
it's for me , seems lose the ''(quotation marks)  
I mean that the parameter shuld be a string
and I used some other ways to resolve this problem, but failed
if you has answer, please tell me ,tks very much

**Comment by danielfernandez** [comment]
A couple of things:

  - The iteration variable created inside a `th:each` can be accessed with `${...}`, no need to use `*{...}`. In your case it works exactly the same because there your expressions are not inside the scope of a `th:object`, but if they were you'd be experiencing unexpected results.

  - It seems all you need is to escape the quotes you need for turning your JS function's argument into a real JavaScript literal, like: `th:onclick="'loadContent(\''+ ${data.path} +'\')'"` or, alternatively avoid the String concatenation and use `th:onclick="|loadContent('${data.path}')|"`

**Comment by Idiot-Alex** [comment]
omg, it's all i want
tks

**Comment by StanleyJPC** [comment]
onclick="window.location.href='createReports.html'" 这个怎么改啊？

**Comment by AdrienViala** [comment]
For anyone landing on this page with a higher Thymeleaf version, I think one should do as described here : 
https://github.com/thymeleaf/thymeleaf/issues/705
