### ISSUE TITLE
unescape attribute of the element

### ISSUE THREAD

**Issue by chenxb2015** [thymeleaf/thymeleaf#577]
currently I have only got  th:utext for the output of element, but if i would like to get the unescaped attribute value , how would i do it ?
for example,  I have a  `<meta property="description" th:content="|mywebsite ${content} |">`.  how to get the unescaped  content ?

**Comment by danielfernandez** [comment]
Thymeleaf, when working in a *markup* template mode (`HTML` or `XML`), will not allow you to create unescaped attributes, as this goes against the HTML and XML specifications.

In order to force this behaviour, therefore, you will need to process your template (or fragment) using the `TEXT` template mode. Note however that this will make you lose many HTML-specificities Thymeleaf offers.

**Comment by chenxb2015** [comment]
thank you for explain
