### ISSUE TITLE
Adding a custom value to "selected" attribute is not possible

### ISSUE THREAD

**Issue by david-dogneton** [thymeleaf/thymeleaf#578]
I am using Polymer's [paper-tabs](https://www.webcomponents.org/element/PolymerElements/paper-tabs/paper-tabs). 

It uses the `selected` attribute to choose the default tab to display. 
It could be a string or a number (the tab index). 

I want to change the `selected` attribute value through Thymeleaf but it always set the value to `"selected"`, probably to comply with the `<option>` [selected attribute](https://www.w3schools.com/tags/att_option_selected.asp). 

Is it possible to have a custom value like `<paper-tabs selected="2">` ?
Currently, `th:selected="2"` leads to `<paper-tabs selected="selected">`

**Comment by danielfernandez** [comment]
You are right, `th:selected` is meant to model the HTML `selected` attribute, which according to the HTML spec is a *boolean* attribute. This means that it can either be present or not, but no value is expected for it. The `selected="selected"` is the standard value given in order to be friendly to XHTML processors, and together with the empty string is the only value allowed for an HTML *boolean* attribute. That's why Thymeleaf is automatically *fixing* your value.

However in this case the `selected` you need is not HTML's, but an attribute with the same (*unfortunately chosen?*) name used by a Polymer component in an HTML environment.

In order to work around the collision, and assuming you are using Thymeleaf 3.0, you'll have to switch the *template mode* for that template or fragment: either go for `XML` (which would make you lose some HTML-oriented goodies in Thymeleaf — anyway might not be an issue) or directly to `TEXT`, which would make it work more like JSP or FreeMarker, and not mind at all about your code being HTML or not. Actually, according to the code samples in the page you link this might be a safer option given that code isn't actually valid HTML5 (those custom tag and attribute names do not follow the HTML5 spec…)

I'll be closing this for now. Please reopen if you have any further issues with this.

**Comment by danielfernandez** [comment]
> Actually, according to the code samples in the page you link this might be a safer option given that code isn't actually valid HTML5 (those custom tag and attribute names do not follow the HTML5 spec…)

Oops! I'm going to correct myself here: I wasn't noticing the *hyphen* in those tag names. So yes, they do adhere to the HTML5 spec. But the name collision will anyway be an issue for Thymeleaf there…

**Comment by danielfernandez** [comment]
Please note #579. It might be possible to improve this behaviour in future versions.
