### ISSUE TITLE
Pass fragment parameter as th:object

### ISSUE THREAD

**Issue by AaricChenLegacy** [thymeleaf/thymeleaf#583]
I have fragment definition like below:
```
<div th:fragment="container(formObject, action, components)">
    <form th:object="${formObject}" th:action="${action}" method="post">
        <th:block th:replace="${components}"></th:block>
    </form>
</div>
```
when I use following fragment replace
```
<div id="form" th:replace="fragment/form :: container(${user}, '/api/user', ~{:: #form//div})">
    <div>Form Content ...</div>
</div>
```

Got following exception
```
java.lang.IllegalStateException: Neither BindingResult nor plain target object for bean name 'formObject' available as request attribute”?
```

could you please tell me how to do this ? thanks in advance :)

**Comment by danielfernandez** [comment]
This is an effect of how Spring MVC works: it will only add `BindingResult` objects for objects in the `Model` (*context*) at first level, in the moment the controller is executed and the control is passed on to the view (in this case, Thymeleaf).

The problem is, during your call to a fragment you are actually changing the name of the *form-backing bean* you want to use, and it happens that Spring MVC has not initially added a `BindingResult` for that new name (because it didn't exist at the model after the controller executed). So you cannot use it to support your form.

In order to work around this situation I would try to *not rename* such object, making the name used in the fragment match that given at the controller for that object.

**Comment by lourish** [comment]
For the benefit of anyone who stumbles across this looking to do the same, the answer is to use the `__${}__` preprocessor to pass in the name of the form object:

```
<div th:fragment="container(beanName, action, components)">
    <form th:object="${__${beanName}__}" th:action="${action}" method="post">
        <th:block th:replace="${components}"></th:block>
    </form>
</div>
```

**Comment by RiZKiT** [comment]
Thanks @lourish, I was fiddling already with preprocessing but without success. I had a slightly different issue, but got it solved now, with your approach. 
I simplified the code here, I have several input element templates and I needed different field values, `th:field="${fieldname}"` doesn't work for obvious reasons, but this does:
```
<input th:fragment="password(fieldname)" th:field="*{__${fieldname}__}" type="password"/>
```
