### ISSUE TITLE
New line with span loop

### ISSUE THREAD

**Issue by pachoyan** [thymeleaf/thymeleaf#586]
Due this question [No space between elements in a Thymeleaf each loop](http://stackoverflow.com/questions/43077387/no-space-between-elements-in-a-thymeleaf-each-loop/43078003#43078003) I've done some tests.

- Version: 2.1

So if you want to use a loop using a `<span>` tag, for example, just like the question:

`<span th:each="item : ${X}">1</span>`

You'll get the <span> with breaklines. It would be next output:

```
<span>1</span>
<span>1</span>
```
This is displayed by the browser with spaces due the breakline:

> 1 1

But, you cannot choose if you want an space or not. It will be displayed due the breakline.

For example:

`<span>1</span><span>1</span>`

Will be displayed:

> 11

But if you want an space you could be able to put it:

`<span>1 </span><span>1</span>`

> 1 1

So, IMHO I think you would be able to choose if you want this space or not:

For example:

If you want the space you'll write:
`<span th:each="item : ${X}">1 </span>`

And thymeleaf will process `<span>1 </span><span>1 </span>`

But instead if you want to use it without spaces:
`<span th:each="item : ${X}">1</span>` 

Thymeleaf will process `<span>1</span><span>1</span>`

So, It could be better in the case of inline tags thymeleaf process they without a new line.

Otherwise, with other tags this behavior is the best option to improve readability as it does (https://github.com/thymeleaf/thymeleaf/issues/113). For example a list:

```
<ul>
    <li>1</li>
    <li>1</li>
</ul>

```
----

Useful info:

List of inline elements: 

- https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements

**Comment by danielfernandez** [comment]
In Thymeleaf 3.0, a `th:each` will work in the way you detail when added to a `<span>` tag.

Spacing around iterated elements is actually a quite complex feature in the Thymeleaf engine, much more complex than it can probably seem to be (esp. in 3.0 where iteration is engineered deep into the template engine core itself in order to improve streaming performance for large iterations).

Despite the complexity, in v3.0 there was a possibility to make the behaviour of this iteration spacing dependent on the specific tag being used, and we did it (so `<span>` does not add line feeds whereas `<td>` or `<li>` do); but this would not be an easy task in 2.1's engine, which is completely different in this regard. Now that 3.0 is almost one year old, I honestly see no reason to add this kind of complexity to the old 2.1 engine.

Thanks for reporting this.

**Comment by OrangeDog** [comment]
While this was "fixed", how do you get the old behaviour back (whitespace between iterated spans)?
