### ISSUE TITLE
Javascript inline breaks in 3.0.4

### ISSUE THREAD

**Issue by xtianus** [thymeleaf/thymeleaf#588]
I just updated the libraries to v3.0.4 and javascript inlining stopped working properly.

The following code

```
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<body>
	Hello
	<script type="text/javascript" th:inline="javascript">
		   function startCheckSessionTimer() {
			   return setInterval(function() {
		        	console.log([[@{'/someUrl'}]]);
		        }, [[60*1000]]);
		   }
	</script>
</body>
</html>
```

produces the following wrong output:

```
<!DOCTYPE html>
<html>
<body>
	Hello
	<script type="text/javascript">
		   function startCheckSessionTimer() {
			   return setInterval(function() {
		        	console.log([[@{'/someUrl'}]]);
		        }, 60000);
		   }
	</script>
</body>
</html>
```

where the console.log line has not been inlined correctly.

My dependency tree:
```
|    +--- org.thymeleaf:thymeleaf-spring4:3.+ -> 3.0.4.RELEASE
|    |    +--- org.thymeleaf:thymeleaf:3.0.4.RELEASE
|    |    |    +--- ognl:ognl:3.1.12
|    |    |    |    \--- org.javassist:javassist:3.20.0-GA
|    |    |    +--- org.attoparser:attoparser:2.0.3.RELEASE
|    |    |    +--- org.unbescape:unbescape:1.1.4.RELEASE
|    |    |    \--- org.slf4j:slf4j-api:1.6.6 -> 1.7.25
|    |    \--- org.slf4j:slf4j-api:1.6.6 -> 1.7.25
|    +--- org.thymeleaf.extras:thymeleaf-extras-springsecurity4:3.+ -> 3.0.2.RELEASE
|    |    \--- org.slf4j:slf4j-api:1.6.6 -> 1.7.25
```

**Comment by xtianus** [comment]
Just by reverting back to 3.0.3 the problem is fixed:
```
<!DOCTYPE html>
<html>
<body>
	Hello
	<script type="text/javascript">
		   function startCheckSessionTimer() {
			   return setInterval(function() {
		        	console.log("\/someUrl");
		        }, 60000);
		   }
	</script>
</body>
</html>
```

**Comment by danielfernandez** [comment]
This is confirmed. This happens in 3.0.4 when the inlined expression contains a literal, like is your case. Changes in 3.0.4 make the `TextParser` return literals in separate `text` events. In this case, this means an event is generated for all text until `"...log([[@{"`, another one for `"'/someUrl'"`, and finally a third one for `"}]]);..."`

This prevents the inliner, which kicks in afterwards, to correctly identify the whole as an *inlineable* expression, so the expression keeps unchanged.

Sadly we didn't have a test case for this precise scenario, which is really unfortunate given this use of inlining is quite common in order to apply *URL rewriting* to URLs used in JavaScript fragments, which would now be impossible (or require all URLs to be first set into variables, which would be an important inconvenience).

I'm afraid we will have to scrap `3.0.4.RELEASE` and go straight for `3.0.5.RELEASE`, as this is a quite bad regression 😞

**Comment by danielfernandez** [comment]
Already fixed in `3.0.5-SNAPSHOT`

**Comment by danielfernandez** [comment]
The artifacts for `3.0.5.RELEASE` have just been pushed to Maven Central and Bintray. Thanks for reporting this so quickly and allowing us to have a quick fix.

**Comment by xtianus** [comment]
Sorry but 3.0.5.RELEASE still has a problem: it breaks with 

```
Caused by: org.thymeleaf.templateparser.text.TextParseException: (Line = 1, Column = 1) Incomplete structure: "
		// '  
	"
	at org.thymeleaf.templateparser.text.TextParser.parseDocument(TextParser.java:206)
	at org.thymeleaf.templateparser.text.TextParser.parse(TextParser.java:100)
	at org.thymeleaf.templateparser.text.AbstractTextTemplateParser.parse(AbstractTextTemplateParser.java:169)
```

on the following template:

```
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<body>
	Hello
	<script type="text/javascript" th:inline="javascript">
		// '  
	</script>
</body>
</html>
```

**Comment by danielfernandez** [comment]
I see. It's complaning about you having an unclosed literal, because it's not understanding your `//...\n` as a comment. Easy workaround is to use `/*...*/` or close with an additional quote `'` inside the comment.

Anyway, this is a separate (and much less severe) issue. Would you please be so kind to open a separate ticket for this? Thx!

**Comment by xtianus** [comment]
#589
