### ISSUE TITLE
Unclosed quote in comment breaks parser in 3.0.5

### ISSUE THREAD

**Issue by xtianus** [thymeleaf/thymeleaf#589]
The following code gives a parser exception at runtime:

```
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<body>
	Hello
	<script type="text/javascript" th:inline="javascript">
		// '  
	</script>
</body>
</html>
```

The exception is:
```
Caused by: org.thymeleaf.templateparser.text.TextParseException: (Line = 1, Column = 1) Incomplete structure: "
		// '  
	"
	at org.thymeleaf.templateparser.text.TextParser.parseDocument(TextParser.java:206)
	at org.thymeleaf.templateparser.text.TextParser.parse(TextParser.java:100)
	at org.thymeleaf.templateparser.text.AbstractTextTemplateParser.parse(AbstractTextTemplateParser.java:169)
```

This breaks all comments like

> // I'm doing this for that
> // It's wrong

It works fine in 3.0.3

**Comment by danielfernandez** [comment]
Confirmed as a bug. 

For the record, this is because the new logic introduced to `TextParser` in version `3.0.4.RELEASE` for avoiding issues with `/*` groups inside literals considers those quotes (`'`) to be the start of a JavaScript literal that is not closed afterwards. The parser should not be doing this given these quotes are inside comments (`//...\n`), but the parser is only ignoring the quotes (single or double) inside comments surrounded by `/*...*/`.

The possible workarounds for this are: 1. Switching to `/*...*/` comments for these cases; 2. Adding additional `'` in order to *close* the literals;  or 3. Simply removing the quotes (`I am`, `It is`, etc.).

**Comment by danielfernandez** [comment]
Already in `3.0.6-SNAPSHOT`
