### ISSUE TITLE
Thymeleaf 3.0.5 resolver parses JS as HTML

### ISSUE THREAD

**Issue by kamenik** [thymeleaf/thymeleaf#591]
Hi,

I have updated thymeleaf from 3.0.3 to 3.0.5 and it is crushing with "TemplateInputException: An error happened during template parsing (template: "js/communication/worker_communication.js" - line 1, col 1)" now. Problem occurs in main html template when it is trying to insert javascript.

_<script th:insert="js/communication/worker_communication" id="worker_communication" type="javascript/worker"></script>_

According to stacktrace it seems it is parsing JS as HTML - it goes through HtmlMarkupHandler.handleOpenElementEnd(HtmlMarkupHandler.java:297).

Template resolver for JS is configured as:

_final ClassLoaderTemplateResolver jsResolver = new ClassLoaderTemplateResolver();
jsResolver.setPrefix("/");
jsResolver.setSuffix(".js");
jsResolver.setCharacterEncoding("UTF-8");
jsResolver.setTemplateMode(TemplateMode.JAVASCRIPT);
jsResolver.setOrder(2);
jsResolver.setCacheable(false);_

**Comment by danielfernandez** [comment]
Is this the result of *only* updating 3.0.3 to 3.0.5?

That resolver for JavaScript has order `2`. Is the resolver with order `1` the HTML one? and if so, is it specifying its `viewNames` property to the pattern for the names of the views it will resolve as HTML, or alternatively the `checkExistence` property to `true` so that it actually checks if the template is there before considering it *resolved*? If none of these two are specified, it will consider it can resolve *all* templates, and thus parse your javascript as HTML...

**Comment by kamenik** [comment]
Yes, after return to 3.0.3 it's ok again. Yep, there is HTML one at position 1. This is full definition of resolvers:

templates = new TemplateEngine();

final ClassLoaderTemplateResolver pagesResolver = new ClassLoaderTemplateResolver();
pagesResolver.setPrefix("/pages/");
pagesResolver.setSuffix(".html");
pagesResolver.setCharacterEncoding("UTF-8");
pagesResolver.setTemplateMode(TemplateMode.HTML);
pagesResolver.setOrder(1);
pagesResolver.setCheckExistence(true);
pagesResolver.setCacheable(false);

final ClassLoaderTemplateResolver jsResolver = new ClassLoaderTemplateResolver();
jsResolver.setPrefix("/");
jsResolver.setSuffix(".js");
jsResolver.setCharacterEncoding("UTF-8");
jsResolver.setTemplateMode(TemplateMode.JAVASCRIPT);
jsResolver.setOrder(2);
jsResolver.setCacheable(false);

final Set<ITemplateResolver> resolvers = new HashSet<>(Arrays.asList(pagesResolver, jsResolver));

templates.setTemplateResolvers(resolvers);

**Comment by danielfernandez** [comment]
OK, could you please post a trace of the exception you are getting for `An error happened during template parsing (template: "js/communication/worker_communication.js" - line 1, col 1)`? 

The fact that it goes through the HTML parser can be simply because the containing tempate (the one executing `th:insert`) is HTML, and in the new engine it is the parser who drives the entire execution of the engine, so having the complete trace could show that the error is somewhere else.

**Comment by kamenik** [comment]
[js_as_html_trace.txt](https://github.com/thymeleaf/thymeleaf/files/902299/js_as_html_trace.txt)

**Comment by danielfernandez** [comment]
OK, the issue is in that single quote `'` character in the first line, in the comment that starts in line 1, col 1. This is therefore the same as #589. 

Could you please confirm that `3.0.6-SNAPSHOT` fixes it for you?

**Comment by kamenik** [comment]
3.0.6-SNAPSHOT seems to be OK :).
