### ISSUE TITLE
#strings.abbreviate: trim before adding ellipsis

### ISSUE THREAD

**Issue by saviola777** [thymeleaf/thymeleaf#594]
Just a small suggestion: It would be nice if the abbreviated string was trimmed before adding "..." at the end. At the moment, if the string contains spaces they are included before the ellipsis, e.g.:

```
${#strings.abbreviate('test with spaces', 13)}
```

would result in "test with ..." instead of "test with..." which would (in most / all cases?) be more desirable.

If you think this is unnecessary or keeping the spaces is more desirable, feel free to close this. Keep up the great work!

**Comment by danielfernandez** [comment]
Thanks for your suggestion. I do actually see your point, because it is true that a text ending in something like `" ..."` looks a bit weird.

However, I think performing this previous trim operation would provoke unexpected results, as the idea with `abbreviate` is that texts with a length larger than the specified value will result in a literal with *exactly* the specified length. Returning a literal with less length could lead to strange behaviours, like abbreviating `abbreviate("     abcd", 8)` to `"..."`.

Besides, this specific method is modelled on the `StringUtils.abbreviate(...)` utility from the Apache Commons library, which does not perform any trimming. Making it diverge from the Commons Lang version would be IMHO an unpleasant surprise to some users, so I prefer to leave this like it is now.

Anyway, as I said, thanks a lot for your comment!
