### ISSUE TITLE
th:block not resolved when sourrounded with quotes in JS template

### ISSUE THREAD

**Issue by hthole** [thymeleaf/thymeleaf#598]
Hi there,

since 3.0.5 it seems Thymeleaf is no longer recognizing th:block statements inside quotes in JS mode.
For example an expression like
`myLabels.push("[#th:block th:utext="#{some.text.label}"/]");`
is no longer resolving the text, but just printing out the th-statement. I think this is caused by the multiple quotes on that line, but even using single quotes for the inner or outer statement doesn't work. This code was working with Thymeleaf 3.0.3 -- maybe you can confirm this is an issue. I'd be happy to have some work around as I'm out of options on how to add Strings properly to the JS output.

Thanks!

**Comment by danielfernandez** [comment]
That is correct. It's not exactly an issue, but rather the fact that elements (`[#...]` or in your case the equivalent `[#th:block ...]`) were allowed inside JavaScript and CSS literals was something that versions < 3.0.4 were not ruling out and which was causing syntax collisions that lead to other parsing/evaluation issues.

Elements are not allowed inside literals. But this only means you cannot apply flow logic *inside* JavaScript literals (`th:if`, `th:each`, etc.) which anyway IMHO you shouldn't really be doing.

What you need is not only still allowed, but you even have several ways of doing it:

1. Using an **inlined output expression** (these *are* allowed inside JS literals), specifically an *unescaped one* (`[(...)]`) so that it is equivalent to your `th:utext` (but you'll still need the surrounding quotes):
```javascript
myLabels.push("[(#{some.text.label})]");
```

2. Using an **inlined output expression, but an escaped one** (`[[...]]`). *Escaped* inlined output expressions in `JAVASCRIPT` template or inlining modes automatically surround their result with quotes, and also apply JavaScript escaping to the result, so that it is a valid JS literal. This might be something you don't want (is that why you are using `th:utext`?) but note that in such case you'd need to have your `#{some.text.label}` already returning correctly JS-escaped text:
```javascript
myLabels.push([[#{some.text.label}]]);
```

3. Using an **element with a th:text** (`[#.../]`). Just like yours, but letting Thymeleaf do the JS escaping and adding the quotes. Note the `th:block` is optional, so I'll omit it for conciseness:
```javascript
myLabels.push([# th:text="#{some.text.label}"/]);
```

4. Using an **element with a th:utext** (`[#.../]`). This won't apply any JS-escaping (maybe that's what you want?) but it will require you to manually add the quotes:
```javascript
myLabels.push([# th:utext="'\"'+ #{some.text.label} + '\"'"/]);
```
So many single and double quotes together are confusing, so we can improve the expression above by using a literal substitution (`|...|`)
```javascript
myLabels.push([# th:utext="|\"#{some.text.label}\"|"/]);
```
...and I'm sure there would be more options. But those are the ones that I can think of off the top of my head.

**Comment by hthole** [comment]
Hi Daniel, thanks for the fast answer. I'll give it a try. I really appreciate your work!
