### ISSUE TITLE
Master template + injection of content part is a must-have feature

### ISSUE THREAD

**Issue by javac9** [thymeleaf/thymeleaf#599]
Are there plans for Thymeleaf to support creation of master template file (complete DOM tree), where we would have a defined injection point for content part? (for those familiar with ASP.Net MVC and Razor view files - something like that)

Should you object that this is not the right place for making such a proposal, please do advise me on how to properly submit it.

**Comment by danielfernandez** [comment]
Yes, this is a perfectly fine place for such a comment :)

The answer is *no*, there are currently no plans to add a *hierarchical* layout mechanism to the core of Thymeleaf, because there already are alternatives.

The *Thymeleaf Layout Dialect*, which is not official but is very widely used is one of them, and it offers exactly what you seem to be looking for. Also, if you are still using version 2.1 of Thymeleaf you can use the official Thymeleaf + Apache Tiles 2 integration package, which does not exist for Thymeleaf 3 (though in the mid-term roadmap there's the creation of an equivalent to Thymeleaf 3.0 and Apache Tiles 3).
