### ISSUE TITLE
Thymeleaf3 does not support th: field tag?

### ISSUE THREAD

**Issue by tianmingxing** [thymeleaf/thymeleaf#600]
I did not see the "th: field" field in the XML constraint, nor did I see the tag on the document because it had a substitute?
```
xmlns:th="http://www.thymeleaf.org"
```

**Comment by danielfernandez** [comment]
Sorry, could you please clarify your question a bit? what do you mean with *"XML constraint"*, and what tag did you not see on which document?

**Comment by tianmingxing** [comment]
Editor can not identify the "th: field" tag, I think it is due to xmlns not defined in the lead. But I can not see the document, so I can not.

**Comment by danielfernandez** [comment]
With *editor* you mean an IDE? If so, which IDE? note thymeleaf only offers an *official* plugin for Eclipse, and other editors implement their Thymeleaf support on their own.

Also, normally the `xmlns:th` attribute is added to the `<html>` tag in order to make IDEs not raise warnings about the `th:*` attributes (i.e. so that they recognise the `th:` prefix is actually something you *intend* to write, not an error. But whether they recognise or not the specific `th:field` attribute, well, that is an IDE-specific thing…

I'm closing this as this is not a Thymeleaf core issue in itself. If you think there is a bug in the eclipse plugin, please add a ticket at the `thymeleaf-extras-eclipse-plugin` repository.
