### ISSUE TITLE
setting attribute values for datatables does not work

### ISSUE THREAD

**Issue by wilsib** [thymeleaf/thymeleaf#610]
Trying to create a dynamic table from a HashMap (as return by jdbcTemplate.queryForList) results in a TemplateProcessingException: Could not parse as assignation sequence: "dt:property=${col}" 

The template looks like:
`th:attr="dt:property=${col}"`

Changing this to:
`th:attr="property=${col}"`
results in a valid html page, but with a not-working datatable.
It seems that the : causes this problem

**Comment by danielfernandez** [comment]
I assume `dt:property` is an attribute that should be processed by a custom dialect, so I'm not sure why you are using `th:attr` to set it, instead of directly using the attribute as such: `<div dt:property="${col}">`.

If this is because the dialect that implements `dt:property` does not understand Thymeleaf Standard Expressions such as `${col}`, in such case you could run your code simply by surrounding your attribute name with single quotes to make it a valid literal (if it has no quotes, it should be a token, and tokens cannot include the `:` character): `<div th:attr="'dt:property'=${col}">`

**Comment by wilsib** [comment]
Hi
sorry for this stupid issue. It worked immediately as proposed. I already had this, but it seems that I mad some other errors.
Thx a lot for your fast support
