### ISSUE TITLE
RFE: Allow th:replace to conditionally render fragment

### ISSUE THREAD

**Issue by mmoayyed** [thymeleaf/thymeleaf#620]
I want to propose support for the following semantic:

```html
<div th:replace="fragments/something" th:if="${booleanValue} />
```

Or if it matters:

```html
<span th:replace="fragments/something" th:if="${booleanValue}" />
```

As far as I can experiment, this behavior isn't supported and regardless of the condition, the `something` fragment is rendered. The present workaround is to remove the `if` clause from the parent containing fragment and move it into the `something` fragment:

Parent fragment:

```html
<span th:replace="fragments/something" />
```

Fragment `something.html`:

```html
<span th:if="${booleanValue}">
    <!-- Do stuff -->
</span>
```

Ran into this with https://github.com/apereo/cas which uses Thymeleaf `3.0.6.RELEASE`.

**Comment by danielfernandez** [comment]
This combination of attributes (`th:replace` and `th:if`) work like that because of how precedence goes. Fragment insertion attributes are the ones with the highest precedence, so when in the same tag, `th:replace` will always execute before `th:if` which, you are right, in this case makes that `th:if` useless.

However, yours is not an unsupported scenario. The key here is that *fragment expressions* are very powerful, so the effect you try to achieve can actually be obtained within `th:replace` itself by just executing your condition inside it:

```html
<div th:replace="${booleanValue} ? ~{fragments/something} : ~{}" />
```

Note how we are using the *empty fragment* here (`~{}`) as an *else* branch, because that would have the same effect as your `th:if` (if condition doesn't meet, remove the host tag).

So I believe this would solve your scenario, right? Or am I missing anything?

**Comment by mmoayyed** [comment]
Yes that's perfect, thank you! That will do the job, but I might humbly suggest that the syntax is less than intuitive. Some sugar might be ideal, though certainly not required.

Feel free to close,  and thanks again.

**Comment by danielfernandez** [comment]
As a more detailed explanation of the syntax above: note how this is just a *conditional* expression, with the same shape that you can use in any other place: `th:text`, `th:href`, etc.

Also, the idea is that `th:replace` and `th:insert` require a *fragment* to perform the insertion. So said in a different way, they need their values to be *expressions that return fragments*. And which expressions return *fragments*? Fragment expressions: `~{...}`

So that's the idea: a normal conditional, on which outcome one of two fragment expressions will execute, returning the fragment that will be used.

Also note that the *old syntax* from Thymeleaf 2.1 is now considered precisely *syntactic sugar* for this, so that: 
```
th:replace="temp :: frag"
```
is in 3.0 a valid, abbreviated version of a simple fragment expression: 
```
th:replace="~{temp :: frag}"
```
