### ISSUE TITLE
Infinite loop caused by Fragment Expressions if reference to itself

### ISSUE THREAD

**Issue by gavenkoa** [thymeleaf/thymeleaf#625]
I was amazed by Thymeleaf 3 fragment expression but it is hard to generalize templates due to complex syntax and a number of concepts behind the scene.

Simple task: add navigation to page:

    <body>
        XXX
    </body>

I made fragment:

    <body th:fragment="body(content)">
        <nav></nav>
        <th:block th:replace="${content} ?: ~{}" />
    </body>

and hoped that below inclusion would work:

    <body th:replace="thymeleaf/layout/default :: body(~{::body})">
        XXX
    </body>

Page was rendered into infinite sequence of `<nav></nav>`.

I can resolve issue if I change reference to inner element:

    <body th:replace="thymeleaf/layout/default :: body(~{::body/div})">
        <div>
             XXX
        </div>
    </body>

Introducing inner element doesn't look an elegant solution to break infinite loop.

Alternatively I should define fragment on `html` level.

As an exercise I added link to outer scope as reference: `~{::html}` and enjoyed looking to browser / Servlet server agony ))

Moral of this story - reference to itself or outer scope inside Fragment Expression may cause infinite loop in page rendering.

I don't know if it is necessary to detect infinite loops or better to have StackOverflowError

**Comment by danielfernandez** [comment]
As you described, the fragment expression you created forms an infinite loop, as a `~{::body}` will select the `<body>` tag itself, and that means along with its `th:replace`. I think it actually makes good sense that this situation provokes a loop. In some situations this is a very desired behaviour in order to allow for dinamically-bound recursion — though of course in such cases the expression would include some kind of *guard* against looping infinitely.

In your case, I think selecting the `<body>` tag itself would not be what you need even if the `th:replace` didn't apply recursively, as that would make you end up with a `<body>` nested inside another `<body>` by means of that `<th:block th:replace="${content}">`.

So if you want to pass as a fragment parameter only the *content* (the *body*, in fact) of your `<body>` tag, you can use the `/content()` modifier like this:

```html
<body th:replace="thymeleaf/layout/default :: body(~{::body/content()})">
    XXX
</body>
```

Note `/content()` was added in version 2.0.3 of AttoParser, which is used since Thymeleaf 3.0.4, so you'd need to update to at least that version (I'd recommend going for 3.0.6 directly). You can read the complete syntax reference for AttoParser markup selectors here: http://www.attoparser.org/apidocs/attoparser/2.0.4.RELEASE/org/attoparser/select/package-summary.html

**Comment by gavenkoa** [comment]
Wow! `content()` is interesting feature. I recently asked question https://stackoverflow.com/questions/45188552/why-thinclude-is-no-longer-recommended-since-thymeleaf-3-0/ and now I got answer ))

Though official docs doesn't tell even about `text()` (except some examples):

http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#appendix-c-markup-selector-syntax

it was missing in http://www.attoparser.org/apidocs/attoparser/2.0.0.RELEASE/org/attoparser/select/package-summary.html which I consulted for "advanced" features. Of course http://www.attoparser.org/apidocs/attoparser/2.0.3.RELEASE/org/attoparser/select/package-summary.html has `content()` description.

**Comment by danielfernandez** [comment]
Yes, I just fixed that in the tutorial so that it now links to the AttoParser documentation in version 2.0.4, which includes the latest additions. The Thymeleaf tutorial list the complete set of features because actually markup selectors are AttoParser's.

So I will close this for now if that's right, as I understand your scenario should be covered.
