### ISSUE TITLE
th:replace doesn't work when set spring.thymeleaf.mode=LEGACYHTML5

### ISSUE THREAD

**Issue by fullstackyang** [thymeleaf/thymeleaf#634]
here is my two HTMLs:
```
<!-- index.html -->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8" />
    <title>Title</title>
    <head th:replace="header :: header" />
</head>
<body>
<h1 class="text-danger">Hello World!</h1>
</body>
</html>
```
```
<!-- header.html -->
 <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml"
          xmlns:th="http://www.thymeleaf.org">
    <head th:fragment="header">
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"/>

        <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
    </body>
    </html>
```
if the header fragment has been replace into the index.html, the text "Hello World" would be displayed in red according to boostrap, but it is black actually, while I remove "spring.thymeleaf.mode=LEGACYHTML5" in application.properties, th:replace tag indeed do work.

**Comment by danielfernandez** [comment]
It's not exactly that it does *not* work. The thing is that the `LEGACYHTML5` template mode applies, prior to template parsing, a *tag balancer*. And this tag balancer (called nekoHTML) examines the structure of the HTML and might close, modify or even remove tags and other elements that do not adhere to the specification for a well-formed HTML documents.

In your case, you are including a `<head>` tag inside another, which is forbidden by the spec. So very probably the tag balancer is simply removing your tag before parsing and Thymeleaf never sees it. I recommend you to have a look at the resulting HTML to see how a lot of tag balancing took place under the scene.

In order to avoid this, you can use the `HTML5` template mode in Thymeleaf 2.1 (which requires your code to be XML-well-formed), or simply update to Thymeleaf 3 which includes an `HTML` template mode that allows HTML in templates to not be XML-well-formed.
