### ISSUE TITLE
How to implement redirect in thymeleaf template?Can it?

### ISSUE THREAD

**Issue by ghost** [thymeleaf/thymeleaf#635]

**Comment by danielfernandez** [comment]
You mean a template that only redirects to another one? or you mean redirect as the result of some action in the UI? if it's the former, why would you want to do that?, and if it's the latter, that should be a piece of JavaScript as usual...

**Comment by ghost** [comment]
Only redirects to another one.I using spring security the form login Login page

**Comment by danielfernandez** [comment]
There is no way to make a Thymeleaf template only redirect to another one (and not contain anything else, no HTML, no JS, nothing).

Anyway, I'm still confused about why you'd want to do that in a Thymeleaf template... any reason why you would not perform a redirection (or a forward) at your controller instead? If you are using Spring, returning a view name with the `redirect:` prefix should be enough... but nothing to be added in any Thymeleaf templates themselves.

**Comment by destan** [comment]
although would not be a best practice following might be something you're looking for:

```
  <th:block sec:authorize="isAuthenticated()">
    <meta http-equiv="refresh" content="0;url=/"/>
  </th:block>
```

**Comment by ghost** [comment]
@danielfernandez See the reference :[Creating a Custom Login Form](https://docs.spring.io/spring-security/site/docs/current/guides/html5/form-javaconfig.html) ,`/login` is ViewController，so if I logined I access `/login` the view should not show login form.

**Comment by danielfernandez** [comment]
If I understand correctly, you mean that your issue is that you don't want that a user that is already authenticated sees the login form if they access the `/login` URL, right?

If this is correct, that's definitely a check (and a redirect) you should be doing at the controller, not the view. So your controller for `/login` should check if the user is already authenticated and, if so, instruct Spring MVC to do a redirect to the URL of your choice (for example, by returning `redirect:/someotherpage`).

**Comment by ghost** [comment]
Yes you are right. I should learn `thymeleaf` more and understand it.Thank you for your advice .
