### ISSUE TITLE
Possibility to specify timezone for #dates / #calendars formatting

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#64]
In order to better show dates and calendars in templates, it would be useful to allow the setting of the timezone to be used in either of two ways (investigate which would be the correct one):
- Adding the timezone as a parameter in `#dates` and `#calendars`
- Ability to set a timezone at the context object

See http://forum.thymeleaf.org/dates-format-and-TimeZone-td3735317.html

**Comment by petergeneric** [comment]
This would be really useful

**Comment by danielfernandez** [comment]
This has been implemented in 2.1 by means of the following features:
- Fixed handling of time zone in `#dates.format(...)` and `#calendars.format(...)` expression utility methods. Time zone was being ignored until now.
- Fixed handling of locale in calendar/date creation methods in `#dates` and `#calendars`. Now the request's current locale is will be used. Even if locale has little influence on `java.util.Calendar` methods (basically, only for determining which is the first day of the week), it was being ignored until now.
- New `createNowForTimeZone(timeZone)` and `createTodayForTimeZone(timeZone)` methods at both the `#dates` and the `#calendars` expression utility objects.
- New versions of all the `create(...)` methods in `#calendars` with name `createForTimeZone(..., timeZone)`, adding timezone to the already existing parameter combinations (as a last parameter).

**Comment by mchiareli** [comment]
how to perform a format using a specific timezone using this fix?

**Comment by michael-simons** [comment]
@mchiareli +1

**Comment by srang** [comment]
So is this actually possible now? I'm looking at the documentation and at the commit and I don't see how to actually pass in the timezone to the #dates.format function

**Comment by ultraq** [comment]
Seems like the docs are out of date for this.  Raised a new issue to update them: https://github.com/thymeleaf/thymeleaf-docs/issues/32

The new timezone-specifying methods are as per Daniel's comment:

> - New `createNowForTimeZone(timeZone)` and `createTodayForTimeZone(timeZone)` methods at both the `#dates` and the `#calendars` expression utility objects.
> - New versions of all the `create(...)` methods in `#calendars` with name `createForTimeZone(..., timeZone)`, adding timezone to the already existing parameter combinations (as a last parameter).

**Comment by srang** [comment]
Good call @ultraq. Also from playing around with it and looking at this [post](http://forum.thymeleaf.org/dates-format-and-TimeZone-td3735317.html) I think there could be more done around the handling of timezones. I tried doing what Blejzer said to do `#dates.format(#calendars.createForTimeZone(#calendars.year(ticket.ticketDate), #calendars.month(ticket.ticketDate), #calendars.day(ticket.ticketDate), #calendars.hour(ticket.ticketDate), #calendars.minute(ticket.ticketDate),'PST'))` and that actually offset it in the wrong direction, at least in the sense of what Blejzer is trying to do. What seems to be happening is that it assumes that the timezone param is your 'source' timezone rather than 'destination'.
It could be that I'm missing what the goal of this feature was but I thought it was to add the ability to set 'destination' timezone similar to setting timezone for a DateFormat object. Our team would like that functionality and we are looking at what it would take to add it here, so if this is the right issue to reopen or if I should open a new issue for that let me know.
