### ISSUE TITLE
using javascript inline expression in  a Chinese character set

### ISSUE THREAD

**Issue by lizhiyuan09** [thymeleaf/thymeleaf#645]
I have a problem when using javascript inline expression in GBK ( a Chinese character set)encoding environment. thymeleaf version is 3.0.7，jackson verson is 2.5.0
```
<script th:inline="javascript">
var user = [[${sessCtx.username}]];
</script>
```
sessCtx.username contain some chinese characters . like "张三". but what I got is : 
`var user = "\u82CF\u5DDE";`
I can transform in front end, but this is not a normal way. What can I do to get a right string in back end.

**Comment by danielfernandez** [comment]
That `[[${sessCtx.username}]]` is an *escaped* expression, which will take the form of a literal when output as JavaScript. This will always escape non-ASCII characters into their corresponding unicode escapes, such as the `\u82CF\u5DDE` you are obtaining.

Could you please clarify if `\u82CF\u5DDE` is not the *escaped* output you were expecting, and why?

**Comment by mangodai** [comment]
@danielfernandez 
Most of the time, we need a chinese string in javascript of code, it can be remind user's input is error. For example :
```
var str = '中文';
alert(str);
```

**Comment by danielfernandez** [comment]
Yes, I understand that, but the escaped string is exactly equivalent to the one directly containing the Chinese characters. It should display exactly the same, but thanks to being escaped it won't require the HTML/JavaScript to use non-ASCII characters. That's why I'm asking why specifically the user needed the Chinese characters, or whether the escaping was not being properly done.

**Comment by mangodai** [comment]
@danielfernandez 
do you hava better idea to solve the problem?
I try, but i can't

**Comment by danielfernandez** [comment]
The thing is... I don't see any problem here. Escaped strings are perfectly equivalent to their unescaped counterparts. Please try this code:
```javascript
var str = '\u4E2D\u6587';
alert(str);
```

**Comment by mangodai** [comment]
however, we don't need escaped strings in javascrpit. we need chinese in javascript

**Comment by danielfernandez** [comment]
When you say *"we need Chinese in JavaScript"*, could you please help me understand why you *need* it? I mean, why having escaped output does not work for you? Of course I understand any character encoding can be used in an HTML document, but generally escaping operations are performed for security reasons and in order to avoid very common display issues. However, again, if there is a reason why your JavaScript literals *cannot be escaped* in your code, could you please explain this reason so that I can better understand the scenario?

Anyway, you can obtain unescaped output like this (using `[(...)]`):
```html
<script th:inline="javascript">
var user = '[(${sessCtx.username})]';
</script>
```
But please note that you need to take care of the quotes for yourself (`'...'`) and also of manually escaping any single quotes (`'`) that might appear inside your literal in order to not break the literal.

**Comment by mangodai** [comment]
i knew the code is work. but it doesn't friendly to developer.you cann't see the strings of meaning. 
anyway, think you 👍
