### ISSUE TITLE
[suggestion] #strings.abbreviate : use a single unicode ellipsis character (…) instead of three dots (...)

### ISSUE THREAD

**Issue by lovasoa** [thymeleaf/thymeleaf#661]
Currently, `#strings.abbreviate(str,n)` shows only n-3 characters from the string when it is long. It could show up to n-1 characters if instead of using three dots, it used a single '…' character (`U+2026` in unicode, or the `&hellip;` HTML entity).

**Comment by danielfernandez** [comment]
Yes, you are right that using the ellipsis char could save a couple string positions… but that method was created as a mirror of Apache Commons Lang's `StringUtils.abbreviate(...)`, which used back then (and still uses today) three simple dots: https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#abbreviate-java.lang.String-int- . That is a very used method with which many developers are familiar.

The thing is the ellipsis character is non ASCII, so using it could unwillingly force non-ASCII characters into pages that maybe are not meant to have anything non-ASCII. And using an HTML escape entity as an alternative would be valid for HTML pages or even XML if we used the hex escape... but would be an issue for templates in `JAVASCRIPT`,`CSS` or even `TEXT` modes.

So even if your idea makes sense (thanks!), I believe it should not be implemented like that due to the constraints already mentioned. I'm therefore closing this as _declined_.
