### ISSUE TITLE
${attributeName} syntax accesses Request parameter instead of Model attribute (both have the same name)

### ISSUE THREAD

**Issue by YoanaIvanova** [thymeleaf/thymeleaf#665]
I'm using **Thymeleaf 3.0.9.RELEASE** along with **Spring 5.0.2.BUILD-SNAPSHOT** and **Spring Boot 2.0.0.BUILD-SNAPSHOT**.

In my controller, I'm adding a **Page** model attribute which contains information about my page:

```
public class SomeController {

    protected void populateModel(final Model model, final Page<?> page) {
        model.addAttribute("page", page);
    }
}
```

Then in my application, I try to access:
http://localhost:8888/sampleApp/category?q=someFilter&page=1

In my view, when I try to get some property of the "page" model attribute, I get errors of this type:
_"Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'totalElements' cannot be found on object of type 'java.lang.String' - maybe not public"_

And if I try to print out the "page" variable like so:

`<div data-th-text=${page}></div>`

I only see the string "1" printed out.

This leads me to believe that somehow Thymeleaf is taking the value of the request parameter instead of the value of the model attribute. I tested this further with adding a new line in my controller, saying:

`model.addAttribute("someDifferentName", page);`

Then I can actually access the **Page** object in my view by referring to the "someDifferentName" model attribute.

I thought that request parameters are accessed with the **_${param.*}_** syntax (as seen in the documentation: http://www.thymeleaf.org/doc/articles/springmvcaccessdata.html) and the **${*}** syntax is used for accessing model attributes.

Is this expected behaviour or is it a bug in Thymeleaf 3? 

P.S. If needed, I'll put together an elementary test project for this. I just figured it's a straightforward enough case.

**Comment by gochev** [comment]
I have a similar issue.

It looks the "name" evaluation in theymeleaf is **completely broken**.

In a JSTL (jsp) the order for evaluation usually is _pageContext_, _requestScope_, _sessionScope_, _applicationScope_ and **never** **evaluating the param.attribute without params prefix**. It looks in thymeleaf this is not the case right now because of bug or by design ? so having a shared controllers with different view technologie (jsp and thymeleaf) s is basically impossible.

My issue however is even **more absurd** and is the following:

I have a model attribute called "roles" for example that contains all roles.

I have a form object with an property which again is "roles".
The thymeleaf view code is the following

```
<select id="roles" multiple="multiple" data-th-field="*{employeeForm.roles}">
                                                    <option data-th-each="role : ${roles}"
                                                            data-th-value="${role.code}"
                                                            data-th-text="${role.displayName}">Role</option>
                                                </select>
```

Everything works fine on the first request, I iterate on the roles and print the names and the values. However AFTER submitting in case of exceptions it looks "employeeForm.roles" is "**overriding**" the "roles". This means ${roles} becomes equal or evluated to ${employeeForm.roles} even when this was just as part of the request form data send via POST request.

**It looks no metter do we send via POST request or GET request the form data or the parameters are overriding the pageContext attributes or model attributes (in case of Spring MVC).** 

This is wrong on so many levels  :) the workaround for now is never to have the same names for params, model attributes, form fields(properties) or anything like that :)

**Comment by ptahchiev** [comment]
Yep, i hit this too :( ... Would be really nice if a fix or a workaround is provided.

**Comment by danielfernandez** [comment]
@YoanaIvanova The `${page}` expression does not access request parameters, only model/request *attributes*. In order to access a request parameter you need the `param.` prefix, as you already mention.

I'm not able to reproduce your behaviour. With java code like this:

```
public class Page {
    private String something = null;
    public String getSomething() {
        return something;
    }
    public void setSomething(final String something) {
        this.something = something;
    }
}
```

```java
@org.springframework.stereotype.Controller
public class Controller {

    @RequestMapping("/")
    public String main(final Model model, final Page page) {
        page.setSomething("one");
        model.addAttribute("page", page);
        return "index";
    }
```

And a template such as this:

```html
<!DOCTYPE html>
<html lang="en">
<body>
  <div>
      <span th:text="${page}">...</span>
      <span th:text="${page.something}">...</span>
  </div>
</body>
</html>
```

Accessing both `http://localhost:8080/` and `http://localhost:8080?page=1` gives exactly the same result:

```html
<!DOCTYPE html>
<html lang="en">
<body>
  <div>
      <span>test.Page@1f5a0b9a</span>
      <span>one</span>
  </div>
</body>
</html>
```
...which looks perfectly OK.

So I'm guessing... maybe some other part of your application is automatically setting all request parameters into model attributes? note that in Spring servlet-based web applications *request attributes* are equivalent to *model attributes* from the view perspective, so maybe those parameters are automatically filtered or dealt with somehow and added to the request as *attributes*?

It would be very useful if you could provide test code (ideally a test project) replicating this behaviour...

---
@gochev please open a different ticket if you want a better explanation on what you are experiencing, but note that Thymeleaf does not perform form binding or model attribute management, and your case does look much more related to how form binding and attributes are being managed at the Spring side. Most probably you have some kind of collision between the names of fields in your form and other relevant attributes, perhaps with non-request scopes. Again, if you could put together a more detailed example of code, or ideally a test project for your case, it could help see what is your specific case.

**Comment by YoanaIvanova** [comment]
@danielfernandez Ah, yes, my bad, you guessed correctly. After some debugging, I found out that there really is some logic inside the application which sets all _request parameters_ into _model attributes_ - exactly as you said. After commenting that logic out, everything works as expected.

Thank you for the feedback!
