### ISSUE TITLE
How to change value of Variable after declare it in Thymeleaf ?

### ISSUE THREAD

**Issue by knavadiya** [thymeleaf/thymeleaf#666]
# How to change value of Variable after declare it in Thymeleaf ?

here I have declared variable with name someVariable and assign default value 10 after that I am changing value of variable but I am geting error

How to change value of Variable after declare it in Thymeleaf ?

```
<p th:with ="someVariable=10">
              <p th:text ="someVariable=${someVariable}+${someVariable}"> </p>
              <p th:text ="${someVariable}"> </p>
</p>
```

**Comment by ultraq** [comment]
Declaring and setting variables is done using `th:with`.  However, variables are only set within the scope of the element where the change was made (scope in this case means the element where the variable was set, and all its child elements).

Here's an example of this:

```html
<div th:with="test=10">
  <p th:with="test=${test + test}" th:text="${test}">This will be 20</p>
  <p th:text="${test}">This will be 10</p>
</div>
```

Even when we set `test` to be 20 in the first paragraph, because that happens outside the scope of the second paragraph, when we use `test` again it's back to its old value of 10.

**Comment by knavadiya** [comment]
But I want result 20 also outside the <p> tag how can I do it ?

and I also wants to iterate loop and in the loop make addition of products price in sum variable and out of loop I want to print sum of price of all products 


here is my code 

```
<table th:with="totalPrice=0">
                <tr th:each="count,iterator: ${product.paidService}">
                    <td th:text="${iterator.index+1}"></td>
                    <td th:text="${count.name}"></td>
                    <td>Paid</td>
                    <td th:text="${count.price}"></td>  
                    <p th:with="totalPrice=${totalPrice + count.price}"> </p>           
                </tr>

        <span th:text="${totalPrice}"></span>
</table>
```

I am geeting 0 as output but I want sum of all products price as output

How to make variable global and solve my problem ?

**Comment by ultraq** [comment]
Since making variables are scoped to the element, you might not be able to get a total value using `th:with`, so you'll need to look elsewhere.

One alternative solution would be to process the result in your controller, store the result to a model attribute, then use that result in the view.  For example, in Spring:

```java
public String yourControllerEndpoint(Model model) {
  int total = // get the total of your list
  model.addAttribute("total", total);
  return "your-template";
}
```

```html
<table>
  <!-- Your looping display code here -->
  ...
  <span th:text="${total}">Total will go here</span>
</table>
```

Another solution might be to create your own utility class and methods (like the built-in `#strings` and `#numbers` utilities) that can calculate the total for you in your template.  It requires a bit more work since you'll need to read up on how to create your own custom dialects with expression objects (which we have docs for here: http://www.thymeleaf.org/doc/tutorials/3.0/extendingthymeleaf.html#expression-object-dialects-iexpressionobjectdialect).  In the end though, you don't need to do any processing in your controller method, and instead can call your utility method straight from your template.  eg, if you called your utility class `#products`:

```html
<table>
  <!-- Your looping display code here -->
  ...
  <span th:text="${#products.calculateTotal(products)}">Total will go here</span>
</table>
```

**Comment by danielfernandez** [comment]
Closing this as it is already answered in detail by @ultraq

**Comment by damonhnz** [comment]
It is possible to do this purely in the template without adding methods to Java classes. e.g.

declare
`th:with="totalPrice=${new org.apache.commons.lang3.mutable.MutableFloat()}"`
add
`[[${totalPrice.add(count.price)}]]`
get total
`th:text="${totalPrice.get()}"`

My scenario was adding an icon to a legend if the icon had been used inside some nested loops:

```
<body th:with="usesWarning=${new org.apache.commons.lang3.mutable.MutableBoolean()}">
...
      <th:block th:if="${some condition}">
        <img src="./warning.svg"/>
        [[${usesWarning.setTrue()}]]
      </th:block>
...
  <tr th:if="${usesWarning.get()}">
    <td><img src="./warning.svg"/></td>
    <td>text description of icon</td>
  </tr>
```
