### ISSUE TITLE
Question: Define Variables and Namespace in Decoupled Logic (IntelliJ)

### ISSUE THREAD

**Issue by MatSe91** [thymeleaf/thymeleaf#669]
Hello guys,

i have a question and could not find an acceptable answer in www.

In normal Thymeleaf html logic you can / have to define the namespace at the beginning of the document, so autocomplete works like a charm:

```
<html xmlns:th="http://www.thymeleaf.org"
      xmlns="http://www.w3.org/1999/xhtml">
```
In addition to that, if you define server-side variables in Thymeleaf you can even use its fields and it will not marked as an error. 

```
<!--/*@thymesVar id="path" type="java.lang.String"*/-->
<!--/*@thymesVar id="object" type="someComplexObject"*/-->`
```
```
<div th:text="${path}"></div>
<div th:text="${object.someDefinedAttributeInModel}"></div>
```

So my question is:
is something like this possible in Decoupled Logic template which are xml files?

At the moment every thymeleaf namespace (th:) is marked as an error (except if i remove XML Code inspections in IntelliJ settings, code completions works more or less good)

What grinds my gears is that ${object} does not provide any code completions hints for its attributes, because i can't define (or do not know how) these variables in xml.
So now i have to remember / look up all attributes which i want to set...

Can i achieve something like variable definitions in these th.xml files?

I think that decoupled logic in this form is a step backward. =(

I am using:
Java 8
thymeleaf 3.0.2
Spring boot

Thank you

**Comment by ultraq** [comment]
Right now, I don't think anything like this is possible.  This is an IDE enhancement so you'll be better off raising this feature enhancement over on JetBrains' issue tracker for IntelliJ / their Thymeleaf integration: https://youtrack.jetbrains.com/issues/IDEA

Being able to add code assist isn't something Thymeleaf can do by itself.  Even the code assist that comes by adding the XML namespace was only added into IntelliJ a few major versions ago, so it's entirely up to IDE authors to give you that convenience.

If you do end up raising it, could you add a link to the issue here so that other people who come across this can add their vote to the issue?  Highly-voted things eventually make their way into IntelliJ!  (That was how Thymeleaf support got there in the first place!)

**Comment by MatSe91** [comment]
Raised a Feature Request on JetBrains' IntteliJ. Please vote up.

https://youtrack.jetbrains.com/issue/IDEA-186913

Thanks =)
