### ISSUE TITLE
Missing support for html entities

### ISSUE THREAD

**Issue by yhojann-cl** [thymeleaf/thymeleaf#670]
Thymeleaf does not make full use of the HTML standard dictated by the W3C since for example it is not possible to use `&copy;` to represent a copyright, a unicode value will not always have the same visual representation in different character encodings, for example in latin-iso templates v/s utf-8, the solution of the standar is the html entitie, same problem with `&ntilde;` `&aacute;` represent `ñ` and `á`, latin characters.

By example:

![screenshot1]

[screenshot1]: https://78.media.tumblr.com/a99f46b54a31bc7a0ae4dd81dd62b0db/tumblr_p4dpv5j5xT1uzz9lco1_400.png

In the `messages_es.properties` declare the placeholder for password input, in spanish is `contraseña` and `administration` is `administración`, the `ñ` and `ó` characters are represented by `?` simbol. I try use escaped value `&ntilde;` but is escaped.

Thymeleaf add a specific atribute for explicit values, for example `th:utext` but it is absent in others such as `th:placeholder` on inputs or `th:title` on images.

Please, add a full compatibility with escaped characters using html entities by example `th:placeholder="#{unescaped_text}/u"` adding modificators like as a regex modificator.

Related problem: https://github.com/thymeleaf/thymeleaf/issues/189

More info:

- https://www.w3.org/International/questions/qa-escapes
- https://www.w3schools.com/charsets/ref_utf_basic_latin.asp
- https://www.w3schools.com/charsets/ref_utf_latin1_supplement.asp
- https://www.w3schools.com/charsets/ref_utf_latin_extended_a.asp
- https://www.w3schools.com/charsets/ref_utf_latin_extended_b.asp
- https://dev.w3.org/html5/html-author/charref
- https://tools.ietf.org/html/rfc1502

**Comment by danielfernandez** [comment]
Thanks a lot for all the very detailed info and suggestions. Thymeleaf does perfectly support HTML character entities as detailed in the specs.

Thymeleaf will automatically apply HTML escaping to non-ASCII characters in two situations:

   * When rendering attributes (`th:placeholder` -> `placeholder`, for example). The HTML specification expects some basic characters to be escaped inside attributes (like `&` or `"`) and allows for any others to also be. That's why your `&ntilde;` inside an attribute value gets escaped into `&amp;ntilde;`.
   * When rendering text inside the bodies of HTML elements (`<tag>body</tag>`) with `th:text`. In this case, the escaping operation can be avoided if needed by using `th:utext`.

This said, note that the escaping operation Thymeleaf will perform there is a *minimal one*, what Unbescape (the underlying escaping library) defines as *"Level 1"*. This means only _markup significant characters_ will be escaped: `<`, `>`, `&` , `"` and `'`. This is done so in order to minimize the disruption on HTML output. Most users do not want or need their HTML output to be ASCII-only as it would severely reduce the legibility of their output at the code level, and this is no issue for representation at the browsers if the `Content-Type` header is correctly set.

So your issue does not seem to be because of Thymeleaf being incorrectly doing anything or lacking any support, but due to an encoding problem in your application itself. Without knowing the internals of your application, I see two most plausible causes:

   * There is an encoding issue reading your messages from your `.properties` files. Remember that per the Java specification `.properties` files must be in Latin1 whatever the OS unless the JVM is specifically set a system property to override this, or the `.properties` file is explicitly read with a `Reader` specifying a different encoding (and Thymeleaf does not do this by default).

   * There is an issue specifying the encoding at the `Content-Type` header in your HTTP responses, or maybe a mismatch between your `Content-Type` HTTP header, and a `<meta http-equiv="content-type" ...>` in your HTML document that might be confusing your browser.

**Comment by yhojann-cl** [comment]
Thank you very much for considering my point of view.

Reading the source directly from the W3C https://www.w3.org/TR/html401/sgml/entities.html we can notice that it is **recommended** the use of entities for the writing of Latin special characters under coding iso `8859-1` as it is in my case. It also describes that there is a great difference between writing its value represented in a numerical value and the entity created especially for that character (`&divide;` v/s `&#247;`), so there is clearly a problem in writing direct and flat Latin characters about code HTML and therefore it is **recommended under the Standard** to make use of the corresponding HTML entities.

Therefore, not giving support to escape Latin characters can be considered a lack of compatibility to the use of character escape sequence via HTML (html entities).

In my case I use the Eclipse Oxygen editor under the Spring Boot Framework and it is very difficult to maintain a harmony between the different character encodings of each file. I could review my entire project and probably find a solution, but this does not mean that Thymeleaf natively supports the use of HTML entities in the cases where it was designed to make use of it, for example within a `placeholder` attribute.

**Comment by danielfernandez** [comment]
> Therefore, not giving support to escape Latin characters can be considered a lack of compatibility to the use of character escape sequence via HTML (html entities).

I strongly disagree here. Thymeleaf performs escaping in a way perfectly compatible with the HTML specification, and according to the needs of the most part of its users. The fact that it doesn't do it in your preferred way cannot be considered a *lack of compatibility*. Anyway, please note that it is something that can be changed by users by creating their own dialects, which would perform escaping in the way they prefer.

> I could review my entire project and probably find a solution, but this does not mean that Thymeleaf natively supports the use of HTML entities in the cases where it was designed to make use of it, for example within a `placeholder` attribute.

I don't understand this part. As I said above, there are two possible points of error in your application regarding the encoding of those messages. If it is the first one (your `.properties` are not being read correctly), no changes in Thymeleaf's behaviour would make your texts display correctly, as it would be the `String` objects themselves in memory who would contain the wrong `char`s. If it is the second one (wrong `Content-Type` being set), a change in Thymeleaf`s behaviour would only be a patch that would keep you from needing to actually solve the issue until it shows up somewhere else. In no case this is a lack of support of any kind, and much less a *lack of compatibility with the HTML standards*.
