### ISSUE TITLE
Will throw ParseException for references that are not defined in the context !

### ISSUE THREAD

**Issue by robbiepl** [thymeleaf/thymeleaf#673]
thymeleaf 2.1.6-RELEASE

sample template:

`<html>`
`<body>`
`<span th:text="${reference_in_context}">reference_in_context</span>`
`<span th:text="${reference_not_in_context}">reference_not_in_context</span>`
`</body>`
`</html>`

sample model-context:

`Map<String, Object> model = new HashMap<>();`
`            model.put("reference_in_context", "hello world!");`
`           someDefaultProcessor.merge("a", Locale.getDefault(), model)`

**thymeleaf generates empty values by default**

*it's very problematic in the migration of velocity*

[velocity strict-reference-setting](http://velocity.apache.org/engine/1.7/developer-guide.html#strict-reference-setting)

**Comment by danielfernandez** [comment]
I assume what you suggest is that Thymeleaf should raise an error whenever a non-existing variable is accessed in an expression. The `th:text` processor in the Thymeleaf Standard Dialect does indeed write an empty string when such thing happens, though this is not the behaviour for every processor (for instance, fragment inclusion processors do fail in such case).

This behaviour in `th:text` was established from the beginning in order to allow for easy use of null variables (or their absence). It is not a configurable behaviour for `th:text`, but users can create their own processors (with their own behaviour on non-existing variables) by developing custom Thymeleaf dialects.

I'm therefore closing this as _declined_, as obviously changing the behaviour of `th:text` as such would break a large amount of existing code.
