### ISSUE TITLE
Escaping Attribute Values of IStandaloneElementTag

### ISSUE THREAD

**Issue by jmitash** [thymeleaf/thymeleaf#683]
We have a hidden form being built dynamically using `IStandaloneElementTag`s. We noticed some of the form submissions were different from the `value` we were creating the `input` with. This turned out to be because of some HTML entities that were being put in the values and were causing a checksum to fail. For example, Putting in `Test &amp; value` as the `value` attribute was submitting the form as `Test & value`. If we were using user input as the `value`, this might have introduced a way to inject HTML into the page.

For the time being, we've escaped the attributes ourselves, though I am a little curious if this was intentional. Does it make sense to allow unescaped HTML in the attribute values? Or is it (by design) the programmer's responsibility to escape them?

This was on 3.0.9

**Comment by danielfernandez** [comment]
I'm not completely sure I understand your question, or at least not your example with `Test &amp; value`, sorry 😳… do you mean whether it was by design that *processors* had to include their own code for escaping tag attributes instead of having this automatically done by e.g. the *structure handler*?

If so, yes, this was made on purpose. Thymeleaf 2.1 had the template writer automatically escape all attributes present in DOM elements for each tag, but in 3.0 more control was given to the processors to determine *whether to escape* and *how* to do that. 

There are several reasons why this was done, but one of the most commons issues with the approach in v2.1 was with processors that read existing non-`th:*` attributes in tags (existing in the original templates). In order not to doubt whether those attribute values had to be unescaped or not for processing (e.g. adding an additional class to a `class` attribute with `th:classappend`), the standard had to be adopted that, given attributes were being *escaped* at the template writer, they would be *unescaped* at the parser. So all attributes in the DOM in v2.1 would be unescaped. But this had two important issues: first, that a huge amount of CPU cycles and memory was being wasted in unescaping+escaping attributes that would go untouched to output anyway; and second, that a lot of information about the original template was being lost too, because if a developer wanted some attributes to be escaped in a specific way, Thymeleaf was forcing its own escaping mechanism to those attributes in output anyway and the original values were being lost (plus some other things like the in-tag line feeds, etc. but that's a different story ;)).

There were many other reasons of course… but yes, in the end the idea was to leave every tag from the original parsed template untouched unless really needed, and give full power to processors to decide if attributes should be escaped or not and, if so, how.

**Comment by jmitash** [comment]
>  do you mean whether it was by design that processors had to include their own code for escaping tag attributes instead of having this automatically done by e.g. the structure handler?

Yeah, sorry, that was my question.

That all makes sense. I guess I was a little bit narrow minded there thinking what sort of use cases would you want the ability to put `" otherattribute="othervalue` as an attribute value to end up with something like 

```
<input type="hidden" originalattribute="" otherattribute="othervalue"/>
```

but I see now that's (probably) not the intent, instead it's for flexibility and performance.

Thanks for the help Daniel!
