### ISSUE TITLE
TEXT mode: the tag itself output one line

### ISSUE THREAD

**Issue by zhilu** [thymeleaf/thymeleaf#689]
the template is like this:
--------------------------------------
>BEGIN:
>[# th:each="item : ${items}"]
>   xxx-[(${item})]
>[/]
>END.
--------------------------------------------
this output is this:
--------------------------------------------
>BEGIN:
>
>  xxx-item1
>  xxx-item2
>  xxx-item3
>
>END.
-------------------------------------------
the tag [# th:each="item : ${items}"] and [/] also output two empty line

**Comment by danielfernandez** [comment]
This is in fact the expected behaviour in `TEXT` mode, as there actually is a line feed between the `[# th:each=..]` and the `xxx`, and another one between that and the `[/]`. Thymeleaf does not makes assumptions about removing lines that only contain one tag, as this is the usual behaviour in other text-based template engines (e.g. JSP).

**Comment by thomasturrell** [comment]
The [documentation ](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#textual-syntax) states that:

```
Dear [(${customer.name})],

This is the list of our products:

[# th:each="prod : ${products}"]
   - [(${prod.name})]. Price: [(${prod.price})] EUR/kg
[/]

Thanks,
  The Thymeleaf Shop
```
 will result in something like:
```

Dear Mary Ann Blueberry,

This is the list of our products:

   - Apricots. Price: 1.12 EUR/kg
   - Bananas. Price: 1.78 EUR/kg
   - Apples. Price: 0.85 EUR/kg
   - Watermelon. Price: 1.91 EUR/kg

Thanks,
  The Thymeleaf Shop
```

When in fact the result would be:
```

Dear Mary Ann Blueberry,

This is the list of our products:


   - Apricots. Price: 1.12 EUR/kg
   - Bananas. Price: 1.78 EUR/kg
   - Apples. Price: 0.85 EUR/kg
   - Watermelon. Price: 1.91 EUR/kg


Thanks,
  The Thymeleaf Shop
```

JSP removes lines that only contain one tag when the server isn't in development mode. When in develoment mode JSP retains the lines to aid with debugging. By default tomcat is in development mode.

Ideally Thymeleaf would have a configuration parameter to allow templates to remove lines that only contain one tag, otherwise the templates become a lot less readable.
