### ISSUE TITLE
Create th:replace as a synonym for th:substituteby

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#69]
Create a new attribute called `th:replace` as a complete synonym for `th:substituteby`.

The plan is to completely replace `th:substituteby` by `th:replace` in a couple of versions, so with 2.1 `replace`should be added to the documentation instead of every appearance of `substituteby`, and a mention to `substituteby` should appear stating that although having exactly the same effect, it is no longer the preferred option.

`th:substituteby` should NOT appear as _deprecated_ in 2.1

**Comment by danielfernandez** [comment]
@ultraq you are a native English speaker... what do you think of this? Do you feel `th:replace` is a better word than `th:substituteby`? Maybe we could just keep both, but only document `th:replace` in the future...

**Comment by ultraq** [comment]
I think 'replace' is better than 'substituteby', simply because it's a single word like most of the other processors, and so feels more like a part of the processor family that's been created.  All the other two-word processors are there to convey additional meaning and distinguish themselves from their single-word counterparts, eg: `th:classappend` and `th:class`, the 'append' part shows that it does more than the standard 'class' processor.
