### ISSUE TITLE
Does't display currency symbol in Thymeleaf Template

### ISSUE THREAD

**Issue by knavadiya** [thymeleaf/thymeleaf#691]
I am using Jhipster With Spring boot, I am preparing Quotation of products for multiple countries So I want to display currency symbols accounting to country. I am using currency symbols unicode from this website  [(https://www.ip2currency.com/currency-symbol )]. Unicode values are in (HEX) of the Currency Symbol 

I have written `<span th:utext="${currencySymbol}"/>` in my HTML page to display currency symbol but it is not working, here currencySymbol is my thymeleaf variable and it's value is `&#x20b9;` and I am using Spring Boot

Please Help me, How to dispay currency symbol in thymeleaf template using Unicode.

**Comment by danielfernandez** [comment]
The steps you follow look alright to me. If your variable has exactly that `&#x20b9;` value, then using `th:utext` would be the right thing to do and your template should include exactly that hexadecimal escape sequence when reaching the browser.

So I think your issue here is the font being used by the browser. Most probably it does not contain a character (a *glyph*) for that unicode codepoint… check the source code reaching the browser (as simple as right click -> View Source Code and, if `&#x20b9;` is there, then it is a font issue.

**Comment by SandeepGanesana** [comment]
> I am using Jhipster With Spring boot, I am preparing Quotation of products for multiple countries So I want to display currency symbols accounting to country. I am using currency symbols unicode from this website [(https://www.ip2currency.com/currency-symbol )]. Unicode values are in (HEX) of the Currency Symbol
> 
> I have written `<span th:utext="${currencySymbol}"/>` in my HTML page to display currency symbol but it is not working, here currencySymbol is my thymeleaf variable and it's value is `&#x20b9;` and I am using Spring Boot
> 
> Please Help me, How to dispay currency symbol in thymeleaf template using Unicode.

I got stuck at this issues, Can you help me out in displaying Rupee symbol using Thymeleaf. Thanks in advance.

**Comment by jobscluster** [comment]
Hey Sandeep.
You can use indian currency like as [(${lineItem.currency})] instead of th:text="${lineItem.currency}".
Where lineItem is you dto that have currency HEXA code.
