### ISSUE TITLE
Issue migrating to thymeleaf 3.0 (from 2.1)

### ISSUE THREAD

**Issue by ghost** [thymeleaf/thymeleaf#692]
I am having issues porting some of my thymeleaf stuff from 2.1 to 3.0. Already gone through the tutorials, examples, existing questions in stackoverflow etc but couldn't find the alternate in new thymeleaf for this.

How can I read my template from test/input.html file. Once read then I can play around with the Model using structurehandler i.e. reading/adding/setting attributes node variables etc.

But issue is I am not able to read this small template code.

In 2.1 I was using

templateName is "test/input.html" file which has small fragment

```java
  protected Document getTemplate(String templateName) {
    final Template template = argument.getTemplateRepository().getTemplate(new TemplateProcessingParameters(argument.getConfiguration(), templateName, context));
    return template.getDocument();
  }
```

Any help would be highly appreciated. Any direction or any method in IModel (as I believe this will be used in thymeleaf 3.0) which can read my html file?

**Comment by ultraq** [comment]
I seem to have done the following for a method in the layout dialect which needs to get a model for a template, so I wonder if this might be some help:

```groovy
private TemplateModel find(String templateName, String selector = null) {

  return context.configuration.templateManager.parseStandalone(context,
    templateName, selector ? [selector] as Set : null, context.templateMode, true, true)
}
```

https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/source/nz/net/ultraq/thymeleaf/models/TemplateModelFinder.groovy#L45-L58

`context` is an `ITemplateContext`, which I believe you get inside any processor's `process` method.  That gets you access to a TemplateManager which you can then use one of the `parseStandalone` or `parseString` methods on to get a `TemplateModel` back.  (https://www.thymeleaf.org/apidocs/thymeleaf/3.0.9.RELEASE/org/thymeleaf/engine/TemplateManager.html)

There's a lot of undocumented option parameters there but it looks like you can give it the following:
 - `context`: the same context you used to access the template manager
 - `templateName`: name of your template, which combined with any configured prefix/suffix will be a path to the template
 - `selector`: looks like it can be `null` which probably means the whole template rather than a small part of it
 - `templateMode`: feed it `context.templateMode`
 - `useCache`: up to you
 - `failIfNotExists`: up to you

**Comment by ghost** [comment]
Thanks @ultraq for the prompt reply. Really appreciate that. I will try those options and will update.

**Comment by ghost** [comment]
Works like charm. Thanks again for your help.
