### ISSUE TITLE
documentation improvement

### ISSUE THREAD

**Issue by tibistibi** [thymeleaf/thymeleaf#696]
I wanted to implement a Page Layout so i googled and found this:
https://www.thymeleaf.org/doc/articles/layouts.html
it gives a nice example like this:

    <div th:replace="fragments/header :: header">

with an template file header.html in the folder fragments but when i run it it will not find the file.
changing it to this works:

    <div th:replace="fragments/header.html :: header">

so for others after me please update the documentation.

**Comment by ultraq** [comment]
Hi there, the example code will work depending on the settings in your own application.  In this particular case, there is an accompanying project that follows the examples the author has written about, and that example project is written in Spring and has chosen to omit `.html` extensions in their own configuration (see: https://github.com/thymeleaf/thymeleafexamples-layouts/blob/master/src/main/java/thymeleafexamples/layouts/config/WebMvcConfig.java#L55).

If this were one of Thymeleaf's tutorial docs that are still introducing concepts like the optional suffix property to devs, I'd choose to include the `.html` suffix.  But because of the accompanying example project contributed to us by the author, I'm gonna leave that example as is so that the docs and code remain in sync.

**Comment by tibistibi** [comment]
thanks for the explanation. and i can agree with it. although i hope others will see it faster than i did :smile:
