### ISSUE TITLE
AbstractDialect final method problem

### ISSUE THREAD

**Issue by yyi** [thymeleaf/thymeleaf#708]
Customed dialect extends AbstractDialect  , when it's a  spring bean proxied by cglib, the getPrefix method return null and getDialectProcessorPrecedence method return 0,so how about you get rid of the final keyword from AbstractDialect  'get'  method signature?

**Comment by danielfernandez** [comment]
JDK proxies should work here.

Spring will create JDK proxies (instead of CGLIB ones) for any bean you declare that requires proxying –because it has `@Cacheable` methods, for instance– and that implements at least one interface, as long as you make use of –i.e. _inject_– such bean using one of those interfaces as type.

For instance, if you create a `CustomDialect extends AbstractProcessorDialect` class, given `AbstractProcessorDialect` implements both `IDialect` and `IProcessorDialect`, you should be able to inject your bean as `IDialect dialect` or `IProcessorDialect dialect`.

If you need to use methods defined in the `CustomDialect` class (i.e. not present in the interfaces) from the injection target classes, I'd recommend extracting an `ICustomDialect extends IDialect, IProcessorDialect` interface including those methods and simply changing your definition to:
```java
public class CustomDialect extends AbstractProcessorDialect implements ICustomDialect
```

This would allow Spring to proxy your bean using JDK proxies instead of CGLIB. Then your bean would be injected as `ICustomDialect dialect` and the proxy would work fine.

Note JDK proxies are the default and _preferred_ option in Spring applications.

So using a JDK proxy for this class should work for you unless you are forcing CGLIB on every class in the application with something like `@EnableCaching(proxyTargetClass = true)` for some reason.

If `CustomDialect` is not a class under your control because it comes from an external library (and still requires proxying), then I suggest extending it with a subclass that does implement that `ICustomDialect` I mentioned. The only case I can think of where JDK proxying would not be an option is if your `CustomDialect` is already being injected as a concrete class –i.e. `CustomDialect`, not `ICustomDialect`– in code you cannot control, and still you need those beans to be proxied when used through that injection point. But to be honest, in such case I would have to consider not using interfaces bad software development practice that should be fixed in the dialect or application code, not in Thymeleaf.

Those methods in `AbstractDialect` make sense as `final`, and unfortunately writing library code so that everything could be CGLIB-proxied in any scenario would be extremely intrusive, so I don't think important core classes such as `AbstractDialect` should be modified because of very specific CGLIB use cases. The CGLIB proxying mechanism as such is useful, but it is a mechanism that is not default, not preferred, and almost always has a feasible alternative in Spring applications.
