### ISSUE TITLE
Add CSS outside WebContext

### ISSUE THREAD

**Issue by stephane-dereppe** [thymeleaf/thymeleaf#709]
Hi,

I'm using thymeleaf to generate PDF in background processes (batch) using Spring Boot 2...

To add some style to my PDF's I would like to add some CSS using this.
```
<link rel="stylesheet" href="static/css/CDM.css" th:href="@{/static/css/CDM.css}"/>
```
Then I got the following exception :

```
org.thymeleaf.exceptions.TemplateProcessingException: Link base "/static/css/CDM.css" cannot be context relative (/...) unless the context used for executing the engine implements the org.thymeleaf.context.IWebContext interface 
```
I've seen this issue on github but I don't get how I could get a WebContext in a batch process?

How could I load my CSS files so that they are applied in my PDF?

I've seen [this issue](https://github.com/thymeleaf/thymeleafexamples-springmail/issues/2). But I don't get how to make it work outside a WebContext...

**Comment by ultraq** [comment]
Hi @schtrym, sorry for not getting back to you sooner, but is this still an issue for you?  If so, the problem you're running up against is that you can't use `@{...}` expressions outside of a web context because that particular expression looks up some information on the running web server to fill out things like the scheme, protocol, domain, port, etc...  These, obviously, don't exist in a batch process.

However, do you know where your CSS files will live relative to the output template that you're creating?  If so, you can drop the `th:href="@{...}"` and instead fill in the standard `href` attribute to contain the relative path to the CSS file, eg: `href="../static/css/CSM.css"`.  Or if your CSS file lives on a web server that you know the address of, you can fill in the `href` with that address, eg: `href="http://localhost:8080/static/css/CDM.css"`

**Comment by stephane-dereppe** [comment]
Hi @ultraq 

Thanks for you help.

For now as a workaround, I've put my css inline inside my template file :-(

The CSS files are inside my Spring boot archive.. I already tried such

```href="../static/css/CSM.css"```


or 

```
href="static/css/CSM.css"
```

or ..

But it never worked... (CSS were never applied to my template).

**Comment by ultraq** [comment]
Oh, the CSS is inside a JAR file?  Is the HTML inside it too?  There might be some strange thing you have to do like extract the entire JAR contents so that the CSS file lives at the relative path to your HTML as per the `href="..."` value, but I'm not sure how to go about doing that 😕

Sounds like inlining the CSS is a "good" workaround for now.

**Comment by stephane-dereppe** [comment]
Yes. The CSS is inside my Spring boot **fat** Jar archive. The HTML is also inside this fat jar... same for my java code.

**Comment by danielfernandez** [comment]
Very late for a response, but the thing is, a context-relative URL can only be resolved when the template is being executed as a part of a web application running _as such_ in a web server… because it's web servers who create web contexts, that serve as a root for such URLs.

So this means your template needs to be executed by means of the normal Spring Boot web mechanisms (i.e. as a Spring _view_) in order to get to execute that kind of links. As opposed to, for instance, having your own `TemplateEngine` instance and executing it on your own.

However, most PDF-producing mechanism I know actually do this: start a web server, make it render a page, perform an HTTP request, and then render the result into the PDF… and this _rendering_ phase is needed precisely because you are applying styles, so maybe you should be setting a separate web server for your PDF exporter?

Given this is a quite old ticket and you mentioned you already had a workaround I will be closing it now. But plese don't hesitate opening if there is anything else you needed to add.

**Comment by gustavo-9189** [comment]
En definitiva, si o si, hay que dejar los estilos dentro del html? no se puede entonces acceder a /static/css/file.css, desde el html porque el mismo no está dentro del contexto web?

**Comment by sanecrab** [comment]
Is possible reach the static files using Thymeleaf or without using it...

**With thymeleaf:**
Having the file "_src/main/resources/static/css/errors.css_"
```
<html xmlns:th="http://www.thymeleaf.org">
<head>
...
<link rel="stylesheet" type="text/css" th:href="@{/css/errors.css}">
</head>
...
</html>
```

**Without thymeleaf:**
Having the file "_src/main/resources/static/css/errors.css_"
```
<html>
<head>
...
<link rel="stylesheet" type="text/css" href="/css/errors.css">
</head>
...
</html>
```

Note the "/" before the static route, this will make that the processor look for the file under the different directories defined for static resources...
In addition if you want make something before the custom error page/s shows up, you create a controller class implementing the ErrorController interface...

You can get more info in:
[Spring-boot docs](https://docs.spring.io/spring-boot/docs/2.1.13.RELEASE/reference/html/boot-features-developing-web-applications.html#boot-features-spring-mvc-static-content)
