### ISSUE TITLE
Evaluate "if" before "replace"

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf#712]
I'm using 3.0.9.RELEASE with Spring Boot.

I used this expression in a template, intending it to mean "do this replacement if this attribute is provided":

```
<div data-th-if="${message}" data-th-replace="|auth/message/${message}|" />
```

However, this throws an exception saying that `auth/message/null` is not found. Apparently, the `replace` is operating at a higher precedence than the `if`, and I would expect for a "turn this whole tag off" instruction like `if` or `unless` to take precedence.

**Comment by danielfernandez** [comment]
This was a design decision. It was ordered that way due to the precedence relation needed to make `th:insert`, `th:each` and `th:if` work well together. `th:if` makes more sense _after_ `th:each`, and `th:each` makes more sense after `th:insert`. And then `th:replace` is of the same nature as `th:insert`, so it made sense they were at the same precedence level.

But your scenario is not unsupported, because `th:replace` can contain much richer expressions (in 3.0) than simply names of templates or fragments. So you could solve your scenario with a single attribute:
```html
<div data-th-replace="${message} ? |auth/message/${message}| : ~{}" />
 ```
