### ISSUE TITLE
UTF-8 rendering problem

### ISSUE THREAD

**Issue by SergejFrank** [thymeleaf/thymeleaf#713]
Hello,

I have a very strange behavier that I can not quite understand. I thought for a while that it was not Thymeleaf problem but due to further investigation there is no other possibility.

The problem:
We try to issue German special characters "äöüß". These are however replaced by "????".
The strange thing is that it only happens on the server. Localy it works great. They are not just misinterpreted wrong by the browser but already rendered as a questionmark in the raw response.

Have already tried everything possible. Do you guys have any idea what could possibly couse thish issue? I am clueless and desperate.

**Comment by ultraq** [comment]
This one comes up a bit, so I searched through old issues and managed to find this: https://github.com/thymeleaf/thymeleaf/issues/274  Does setting the `contentType` property on the view resolver help?

**Comment by SergejFrank** [comment]
Hey, jeah i already saw that post and tried to set the proposed setting but it doesn't work.

the strage part is that it works localy on different machines.

**Comment by ultraq** [comment]
Hmm, if it's happening only on some machines, then there must be something environmental there that's causing it to go funny.  Are these machines the ones you deploy code to?  If so, then maybe there's something in the build or deployment process that processes those files incorrectly somehow?

Recently at work we had a deployment process that wrote out a unix script that failed on the target test machines because of bad line ends, and in a personal project I accidentally ran static resources like images through a build step that tried to replace tokens with proper values for the target environment which screwed up my images.

**Comment by SergejFrank** [comment]
yeah we had this also in mind and executed the same artifact. 
we use aws beanstalk as our application server. is there a known issue?

**Comment by SergejFrank** [comment]
We managed to narrow the problem down.
It has something to do with the datatables plugin.

The dandelion filter is causing the issue. But we don't have a solution yet.

```  
@Bean
    public FilterRegistrationBean filterRegistrationBean() {
    FilterRegistrationBean filterRegistrationBean = new FilterRegistrationBean();
    //TODO: ruining utf8 chars in template
    DandelionFilter filter = new DandelionFilter();
    filterRegistrationBean.setFilter(filter);
    return filterRegistrationBean;
}
```

**Comment by ultraq** [comment]
That's an interesting find re: DandelionFilter.  I went and looked for the source code and found it, particularly the line that writes to the output stream: https://github.com/dandelion/dandelion/blob/master/dandelion-core/src/main/java/com/github/dandelion/core/web/DandelionFilter.java#L154  I can't see any lines before that setting the character encoding of the response, and the javadocs for the response stream say that the default is `ISO-8859-1` (https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletResponse.html#getCharacterEncoding--), so maybe something like that is missing?  If you're keen to investigate further, you can probably copy that class into your project and play around with it.

**Comment by SergejFrank** [comment]
a quick fix is to set  the environment variable JAVA_TOOLS_OPTIONS to -Dfile.encoding="UTF-8"

the default of AWS Beanstalk is ANSI_X3.4-1968 for whatever reason.

**Comment by danielfernandez** [comment]
This doesn't seem to be a Thymeleaf issue (Dandelion is not a part of the Thymeleaf project). Also, note that different servers / operating systems might have different default encodings and files might be in the OS's default encoding or in a different one –the `file` UNIX comand can help with determining that–, so setting the right encoding to be used for reading template files at the configured `TemplateResolver` is important in order to make sure templates reach the engine adequately converted to `char[]` (`String`).

Remember Java string literals operate in an encoding-independent fashion: a `char` is just the representation of a glyph, and a `String` has no encoding. So input (template reading through the template resolver + request parameter/body reading through the `request` content type) and output (response content type) are the only points to be taken care of.

I'm closing this therefore as it does not seem to be a Thymeleaf issue. Feel free to reopen if new evidence appears.
