### ISSUE TITLE
spring mvc project using javascript set <img> src

### ISSUE THREAD

**Issue by UnicornIsBlack** [thymeleaf/thymeleaf#714]
version:3.0.9

 ```
        <img id="captchaImg" alt="" th:src="@{/captcha/getCaptcha}" 
		style="width: 100px;height: 40px;line-height:40px;" />
        <script>
		$("#captchaImg").click(function(){
			$(this).attr('src','/captcha/getCaptcha');
		});
	</script>
```

I'm coding a spring mvc project. Now I have a problem. When I debug the code on eclipse, the home domain is http://localhost:8080/test/. When I deploy the project as a root project to tomcat, the home domain becomes http://localhost:8080/. When I use javascript to set the src attribute of the img tag, if the home domain is http://localhost:8080/test/, the code is "$(this).attr('src','/test/captcha/getCaptcha');", but if the home domain is http://localhost:8080/, the code becomes "$(this).attr('src','/test/captcha/getCaptcha');". Is there a way to set the src attribute, does not need to be artificially based on the home domain?

**Comment by ultraq** [comment]
There's also a "server-relative" URL so that it doesn't include the application context, if that's what you were looking for?  It starts with `~`, so code you gave would become `th:src="@{~/captcha/getCaptcha}"`  See https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#link-urls and for all the various link types Thymeleaf supports.

**Comment by UnicornIsBlack** [comment]
I want to know how to set the src url using javascript.

**Comment by wwwqyhme** [comment]
```
var imgSrc = '[[@{/captcha}]]'
```
