### ISSUE TITLE
Thymeleaf fails if string contains | (pipe/vertical bar)

### ISSUE THREAD

**Issue by sahil-ag** [thymeleaf/thymeleaf#723]
Version - 3.0.0.RELEASE

I have a string which contains | as well as certain thymeleaf placeholders. I get TemplateInputException when I try to use the same.

```java
        String str = "testString | hello";
        StringTemplateResolver resolver = new StringTemplateResolver();
        resolver.setTemplateMode(TemplateMode.TEXT);
        TemplateEngine engine = new TemplateEngine();
        engine.setTemplateResolver(resolver);
        return engine.process(str, context);

```

**Comment by danielfernandez** [comment]
Could you provide specific `str` or `context` values that reproduce this error? Very similar Strings are present in our tests and they work alright, including `|` chars.

**Comment by sahil-ag** [comment]
```java
    @Test
    public void testPipeString() {
        String test = "${test1}World | ${test2}";
        Context context = new Context();
        context.setVariable("test1", "Hello");
        context.setVariable("test2", "java");
        Assert.assertEquals("HelloWorld | java", resolveString(context, test));
    }

     String resolveString(Context context, String str) {
        TemplateEngine engine;
        StringTemplateResolver resolver = new StringTemplateResolver();
        resolver.setTemplateMode(TemplateMode.TEXT);
        engine = new TemplateEngine();
        engine.setTemplateResolver(resolver);
        StringBuilder sb = new StringBuilder().append("[(|").append(str).append("|)]");
        return engine.process(sb.toString(), context);
    }
```

It would be great if there was another way of using implementing `resolveString`

**Comment by danielfernandez** [comment]
So the template you are executing is: `[(|${test1}World | ${test2}|)]`, which is an invalid Thymeleaf Standard Expression.

With `[(...)]` you are asking Thymeleaf to execute an inlined expression, which in this case is `|${test1}World | ${test2}|`. And `|...|` is the syntax for literal substitutions, so in this case you have `|${test1}World |` as a literal substitution, and then a remaining ` ${test2}|` which is invalid syntax. You cannot use a `|` inside a literal substitution, as it would obviously _close_ it.

So your expression would be better expressed without the surrounding literal substution `[(${test1} + 'World | ' + ${test2})]` or, simply using two inlined expressions instead of one, just like `[(${test1})]World | [(${test2})]`
