### ISSUE TITLE
Unable to Access thymeleaf variable inside Onchange method of Select Option

### ISSUE THREAD

**Issue by gotoark** [thymeleaf/thymeleaf#724]
I am Trying to Add the Onchange functionality 

**My htmlCode**
```html
<body
	th:with="urlVariable=@{/department/save}">
<select th:field="*{districtCode}" onchange="'sayhello('+${urlVariable}+');return false;'">
	<option th:value="'NONE'" th:text="'-----Select District-----'"></option>
	<option th:each="i : ${districtList}" th:value="${i.districtCode}" ="${i.districtName}"></option>
</select>
</<body>
```
**My Script**
```javascript
function sayhello(url){
		alert("Hi"+url);
	}
```
How can I achieve this with thymeleaf  is there us any Possibilities.
Thanks in Advance :)

**Comment by danielfernandez** [comment]
For this you can use `th:onchange`, or if you need to evaluate there variables that return text literal results, for security reasons, you can resolve them in `th:data-*` attributes and then retrieve the values of the resulting `data-*` attributes from a simple `onchange` attribute (instead of `th:onchange`).
