### ISSUE TITLE
Java doc package list changed

### ISSUE THREAD

**Issue by zhanhb** [thymeleaf/thymeleaf#741]
Since 3.0.10.RELEASE, `package-list` is changed to `element-list`. Can I know why this change is made?
https://github.com/thymeleaf/thymeleaf.github.com/blob/master/apidocs/thymeleaf/3.0.9.RELEASE/package-list
https://github.com/thymeleaf/thymeleaf.github.com/blob/master/apidocs/thymeleaf/3.0.11.RELEASE/element-list

**Comment by zhanhb** [comment]
I'm working on a project, which require this file to link java doc. After upgrade to 3.0.11, the link broken.

**Comment by wilkinsona** [comment]
We have the same problem in Spring Boot. It prevents our javadoc (generated with Java 8) from linking to classes in Thymeleaf. I believe the switch from `package-list` to `element-list` is an unwanted side-effect of the javadoc being generated with Java 11 since 3.0.10.RELEASE.

Gradle had a similar problem and worked around it by [copying `element-list` to `package-list`](https://github.com/gradle/gradle/pull/8193). Perhaps a similar change would be appropriate here as well?

**Comment by danielfernandez** [comment]
Fixed by thymeleaf/thymeleaf@e782e22, thymeleaf/thymeleaf-spring@60b8b7a, thymeleaf/thymeleaf-testing@189add9, thymeleaf/thymeleaf-extras-java8time@89c4385 and thymeleaf/thymeleaf-extras-springsecurity@f97b11c.

Also fixed at the javadoc published on the project's website for both 3.0.10.RELEASE and 3.0.11.RELEASE.

**Comment by zhanhb** [comment]
Thanks for fixing.
