### ISSUE TITLE
Insecure User Forums

### ISSUE THREAD

**Issue by OrangeDog** [thymeleaf/thymeleaf#749]
Couldn't fine anywhere else to put this.

The Thymeleaf User Forums (http://forum.thymeleaf.org/) are insecure, so passwords are at risk.
There is content served over https but the certificate is incorrect.

That certificate needs fixing (e.g. use letsencrypt) and the insecure site should redirect, especially when logging/logged in. HSTS would be ideal.

**Comment by wimdeblauwe** [comment]
I see that https://github.com/thymeleaf/thymeleaf/discussions is now available.

**Comment by danielfernandez** [comment]
The old Thymeleaf User Forums at http://forum.thymeleaf.org were locked more than a year ago. We didn't remove the content so that it could still work as documentation for users coming from Google searchs, but no interactions are (should be) allowed any longer since then, at least to the point allowed by the service.

Those forums are managed by an external service called Nabble, and we closed them precisely due to large security issues and basically nonexistent spam control in the service. Also, all references and links to it were removed months ago from the Thymeleaf website.
