### ISSUE TITLE
Is Thymeleaf dead?

### ISSUE THREAD

**Issue by tholu** [thymeleaf/thymeleaf#766]
I don't see any preparations for development on version 3.1, almost no commits since about a year to the core repository. Am I missing something or is this project slowly dying?

**Comment by danielfernandez** [comment]
Nope :) But 3.1 will depend (if everything goes as it should) on other technologies that are being developed (at a slow pace, admittedly) as separate projects.

**Comment by tholu** [comment]
Thanks for the quick answer! Can you elaborate on what other technologies you are talking about? Can the community help?

**Comment by danielfernandez** [comment]
One of the main ideas is to bring Thymeleaf closer to a true reactive approach in order to take better advantage of reactive scenarios. But that requires severe refactorings on several areas, like of course the processing core, but also non-blocking caches and an entirely new expression language (SpringEL compatible) that can work as a valid (lighter, simpler, reactive-friendly) replacement for the default OGNL.

**Comment by marccollin** [comment]
thymeleaf forum is closed
Is there any schedule or planing feature then contributor can check?
