### ISSUE TITLE
id and name attribute not the same for th:field with checkbox

### ISSUE THREAD

**Issue by wimdeblauwe** [thymeleaf/thymeleaf#790]
I have a form bean like this:

```
public class CustomerFormData {
  private VehicleFormData[] vehicles;
  // getters and setters
}

public class VehicleFormData {
  private String type;
  private boolean insured;
  // getters and setters
```

In my Thymeleaf template, I am using:
```
        <input type="checkbox"
               th:field="*{vehicles[__${index}__].insured}"
               class="form-checkbox">
        <label th:for="${#ids.next('vehicles[__${index}__].insured')}"
               class="font-medium text-black"
               th:text="#{vehicle.insured}">Car insured</label>
```

The resulting HTML is:

```
<div class="sm:col-span-6">
        <input type="checkbox" class="form-checkbox" id="vehicles0.insured1" name="vehicles[0].insured1" value="true" checked="checked">
        <input type="hidden" name="_vehicles[0].insured" value="on">
        <label for="vehicles[0].insured1" class="font-medium text-black">Car insured</label>
    </div>
```

Note the id being `vehicles0.insured1`, while the name is `vehicles[0].insured1` (as I expect it to be). As a consequence clicking on the label does not toggle the checkbox since the `for` attribute of the label does not match with the `id` of the checkbox.

Why is the `id` generated like that and is there a workaround for it?

**Comment by danielfernandez** [comment]
This is done for compatibility with the way Spring generated this attributes in its JSP taglibraries. See https://github.com/spring-projects/spring-framework/blob/f88344db03bcc6e40cc434bda00434acb0e8f0c6/spring-webmvc/src/main/java/org/springframework/web/servlet/tags/form/AbstractDataBoundFormElementTag.java#L126-L151

The underlying reason is that ID has quite strict rules on allowed characters in HTML4. These were relaxed in HTML5, but using things like `[]` can potentially cause issues with CSS selectors.
