### ISSUE TITLE
Provide more control over restricted expression evaluation mode

### ISSUE THREAD

**Issue by S-Gaertner** [thymeleaf/thymeleaf#791]
Changes introduced in version 3.0.9 and 3.0.10 (#648, #649 , #705) lead to errors in templates using special variable names (like `param`) in `th:include` and other fragment inclusion attributes. Error example:

> Caused by: ognl.OgnlException: Access to variable "param" is forbidden in this context. Note some restrictions apply to variable access. For example, accessing request parameters is forbidden in preprocessing and unescaped expressions, and also in fragment inclusion specifications.

Please reconsider this behavior or at least allow more control over the usage of the restricted evaluation mode. This great library is not only used in web context and/or with untrusted input.

Further, please consider announcing backwards-incompatible changes more prominently and do not introduce them in a patch version. Thank you!

**Comment by danielfernandez** [comment]
I honestly understand this comments, but these backwards-incompatible changes are due to security vulnerabilities being reported by security auditors. Unfortunately performing major version leaps whenever this happens would not be feasible.

In the same way, allowing for the _disabling_ of these security features would not be allowed by these security auditors. In general, these are people that do not understand the context in which a software technology is used, nor the technology itself, nor are interested in the details or specifics. If there is any kind of remote chance that some kind of usage scenario of the technology could be used as an exploit, it will be reported as a vulnerability and the result will be a lot of users receiving a warning in their security reports telling them they shouldn't be using that library. There are huge amounts of companies that do not mind about whether the libraries in their software are actually used in a way that might make them vulnerable or not, or the specifics of whether vulnerabilities actually affect them -- they just want those CVEs out of their security reports, period. Unfortunately this is how software security audit works these days.
