### ISSUE TITLE
Browser moves th:block element

### ISSUE THREAD

**Issue by thuri** [thymeleaf/thymeleaf#794]
I created an application that enables the user to display an manipulate a thymeleaf template in the browser (actutally it's displayed in an iframe). When a specific button in the application is clicked, the content of the iframe is sent to the backend to save it.

But i do have an issue now with one of the templates which uses a th:block element within a table similar to the following snippet, which i greatly simplified. (I know that I could put the th:each on the <tr> here but not in my actual template; the snippet is only to show what happens)

```html
  <table>
    <tbody>
      <th:block th:each="item : ${items}">
        <tr><td><span>after table</span></td></tr>
      </th:block>
    </tbody>
  </table>
```
When the browser renders this (tested in Firefox and Chromium) the th:block element is moved before the table element and it's contents are moved to it's original position. So when looking into the DOM with the Developer Tools of Firefox it looks like this:

```html
  <th:block th:each="item : ${items}"></th:block>
  <table>
    <tbody>
       <tr><td><span>after table</span></td></tr>
    </tbody>
  </table>
```
That's not a problem if you only look at the HTML in the browser. But as i need to read the content with JavaScript and POST it back to the backend, my template is broken afterwards.

I think browsers are doing this because the contents of the HTML elements in a table are very restricted and the block element is incorrect at this place from the view of the browser.

I think I'll need to "escape" the th:block within tables somehow. First idea is to write a processor which wraps those blocks into comments when the browser want's to read them and unwraps them on save. 

So i have two questions: 
* Would it be possible to make thymeleaf use blocks in comments if they have some special "marker" like a special attribute or something?
* Would it be possible to write a custom dialect which deals with that?

PS: thanks for the awesome work. I really like the approach!!!

**Comment by ultraq** [comment]
> I think browsers are doing this because the contents of the HTML elements in a table are very restricted and the block element is incorrect at this place from the view of the browser.

One thing that comes to mind: does your iframe of these editable templates have a doctype declaration?  I know when browsers are in "quirks mode" (no doctype defined) they do really weird tag balancing tricks and elements end up in the wrong place, etc.  I wonder if something like that is at play here.

But yeah, I wouldn't be too surprised it the browser is choosing to eject the `<th:block>` element from the table because it doesn't belong in there 😕 

> * Would it be possible to make thymeleaf use blocks in comments if they have some special "marker" like a special attribute or something?

Your question made me think of this chapter in the docs: https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#comments-and-blocks  Thymeleaf supports a bunch of comment syntaxes and I wonder if any of those might work in this situation?  The docs state how Thymeleaf will see them, but you'll have to test them out for how the browser and JS code will see them.

**Comment by thuri** [comment]
Thanks @ultraq That's definitely what i wanted. 
Simply should have had a look at the chapters above when i read the docs about th:block 😖
