### ISSUE TITLE
Custom dialect missing attributes

### ISSUE THREAD

**Issue by zaizac** [thymeleaf/thymeleaf#805]
Hi, I am creating a custom tags using thymeleaf 3. Initially it is created in thymeleaf 2, but since we are upgrading to versioin 3 we need to rewrite our current custom tags.

We had some issue related to th:field attributes (and other th:* commands). Upon  accessing the custom element itself the supposed generated name and value field from th:field is not there or even a th:field itself. Our custom tag has higher precedence than the th:* tags as we would like to retrieve the generated value. Below is from our logs:

**HTML**
`<extra:file th:document="${document}" th:field="*{regFile}" class="form-control" th:text="${docId}"></extra:file>`

**LOGS**
```
_This part is retrieved from the ITemplateContext.getElementStack -_
FileTagProcessor.doProcess:101 - getElementCompleteName---------------------------->extra:file
FileTagProcessor.doProcess:106 - getAttributeMap: {th:document=${document}, th:field=*{regFile}, class=form-control, th:text=${docId}} 

_This is retrieved from IProcessableElementTag_
FileTagProcessor.doProcess:109 - getAttributeMap: {document={&quot;docTypeId&quot;:180,&quot;docDesc&quot;:{&quot;en&quot;:&quot;Upload File&quot;},&quot;order&quot;:1,&quot;type&quot;:&quot;image/gif, image/jpeg, image/png, application/pdf&quot;,&quot;size&quot;:1000000,&quot;compulsary&quot;:true,&quot;dimensionCompulsary&quot;:false}, class=form-control} - {} 
FileTagProcessor.doProcess:112 - IAttribute---------------------------->document="{&quot;docTypeId&quot;:180,&quot;docDesc&quot;:{&quot;en&quot;:&quot;Upload File&quot;},&quot;order&quot;:1,&quot;type&quot;:&quot;image/gif, image/jpeg, image/png, application/pdf&quot;,&quot;size&quot;:1000000,&quot;compulsary&quot;:true,&quot;dimensionCompulsary&quot;:false}"
FileTagProcessor.doProcess:112 - IAttribute---------------------------->class="form-control"
FileTagProcessor.doProcess:116 - label: {"docTypeId":180,"docDesc":{"en":"Upload File"},"order":1,"type":"image/gif, image/jpeg, image/png, application/pdf","size":1000000,"compulsary":true,"dimensionCompulsary":false}
FileTagProcessor.doProcess:120 - label: 180
```

Extra Dialect precedence is 100000
File Tag precedence is 2147483647

**Comment by ultraq** [comment]
Hi there, so my understanding of `th:field` is that it will generate attributes into the current element based on specific identifiers, like if the current element is `<input>` or `<select>` and then often check the `type` attribute, before doing anything (as seen in the docs here where `th:field` is introduced but then emits different kinds of HTML based on the input: https://www.thymeleaf.org/doc/tutorials/3.0/thymeleafspring.html#inputs).  If `th:field` doesn't match any known HTML input elements, then it will do nothing.

In this case, `<extra:file>` is not a known HTML input element.

Given that, one way I can think of getting the result of `th:field` is, in your custom element processor, take the value of it, which is an expression, then execute the expression yourself.  Executing expressions can be done with:

```java
Object result = StandardExpressions.getExpressionParser(context.getConfiguration())
  .parseExpression(context, expression)
  .execute(context);
```

**Comment by zaizac** [comment]
Hi, Thank you for your response. Actually, my expectation is it will generate the corresponding attribute id and name generated by th:field. Or I can pass the same attribute to the tag that I'm adding during the processor.

**Comment by ultraq** [comment]
> my expectation is it will generate the corresponding attribute id and name generated by th:field

So `th:field` will do that, but it'll have to be on an HTML input element that it knows about, not a custom one like `<extra:file>`.

Given this, one option to try is to change from using a custom element to a custom attribute, use an HTML input element so that `th:field` can add the id and name as it normally would, then your attribute processor can read those values from the element after, eg:

```html
<input type="file" th:field="*{regFile}" ... extra:file>
```

(I can't remember if you can have custom attributes without values.  If not, then making it `extra:file=""` should fix that up.)

`th:field` will recognize `<input type="file">` and add the appropriate `id` and `name` attributes, then your `extra:file` attribute processor can read them from the input element.

**Comment by zaizac** [comment]
Ok then. Thank you for your suggestion.

**Comment by xtianus** [comment]
> Given that, one way I can think of getting the result of `th:field` is, in your custom element processor, take the value of it, which is an expression, then execute the expression yourself. 

@ultraq I have the same exact issue and the question is: how do I get the th:field value from inside my tag processor that extends `AbstractElementModelProcessor`?
When executing my 

    doProcess(ITemplateContext context, IModel model, IElementModelStructureHandler structureHandler)

the th: attributes have already been stripped from the model.

I need to give my dialect a higher (later) precedence than the standard dialect because I want to use all the th:each and similar stuff on my custom tags, but when doing so I apparently lose access to the th: attributes.

I have a [SO question](https://stackoverflow.com/questions/68852032/thymeleaf-custom-dialect-with-fragments-how-to-keep-th-attributes/68951873) already.

**Comment by ultraq** [comment]
Ah, yes having a higher precedence than the standard dialect will mean you miss out on seeing things like `th:field` in its raw state 🤔

Some workarounds that I can think of:
 - create a separate dialect with a lower value than the standard dialect, which then that contains the processor you want to see the `th:field` value
 - create another processor that can be included on a parent HTML element, like the `<form>`, and then search through all of its input elements to find the `th:field` attributes you want to work with
