### ISSUE TITLE
Use Jackson for Javascript inlining of JSON

### ISSUE THREAD

**Issue by usethe4ce** [thymeleaf/thymeleaf#81]
Provide some way for users to switch to using Jackson (or Gson) for JSON serialization in JavaScript inlining.

Thymeleaf currently rolls its own miniature JSON serializer, but for projects that already use <a href="https://github.com/FasterXML/jackson-databind">Jackson</a>, it would be more consistent and generally preferable to use Jackson instead (or likewise, Gson), especially since the results are not always interchangeable. 

Issue #12 raises the option of passing a JSON string created manually, but this is not an ideal solution.

**Comment by danielfernandez** [comment]
This could probably be a part of a refactoring in the text inlining interfaces that allows plugging different implementation of TextInliners as a part of TemplateEngine / Dialect configuration.

**Comment by petergeneric** [comment]
This would be a really useful feature

**Comment by ultraq** [comment]
@danielfernandez, let me know if we're thinking of this one for 3.0 - I might like to give it a go.

**Comment by Antibrumm** [comment]
In a Spring environment Thymeleaf could probably rely on the message converters?

**Comment by BrynCooke** [comment]
This feature would be very useful. I am using Gson with a customized type adapters to allow serialization of JOOQ generated entities. The Thymeleaf JSON serialization falls over when it hits one of these as they contain many getters that should be ignored.

**Comment by dagnelies** [comment]
+1

**Comment by ruslanys** [comment]
+1

**Comment by petergeneric** [comment]
@danielfernandez in `StandardScriptInliningUtils` for 3.0, would it make sense for `formatEvaluationResult` to ask the `IProcessingContext` for a formatter from it (somehow) rather than having a switch on lang directly in StandardScriptInliningUtils? I'd like to be able to swap out just the call to `StandardJavaScriptUtils.print` with a call to the appropriate JSON library rather than having to worry about the specifics of finding inlining sites.

I don't know enough about the internals to know how best to have such a formatter in `IProcessingContext`, if this sounds like a sensible approach but you don't have time to implement this yourself could you provide some pointers? I would happily implement a draft and create a pull request.

**Comment by f0def** [comment]
+1

**Comment by pere5** [comment]
+1 I'm very sad to just find out that my inlined JSON contains 70% null values because Thymeleaf ignores my `@JsonInclude(JsonInclude.Include.NON_NULL)`

http://stackoverflow.com/questions/33821081/thymeleaf-inline-javascript-ignore-null

**Comment by danielfernandez** [comment]
This has been implemented as specified in #435. It is already in `3.0.0-SNAPSHOT`

**Comment by Gunthervg** [comment]
@danielfernandez Wouldn't it be more logic that in a Spring (boot) environment where there is a configured ObjectMapper bean, this instance will be used instead of creating a new ObjectMapper? JacksonStandardJavaScriptSerializer -> this.mapper = new ObjectMapper();

Currently the configured Spring ObjectMapper is ignored which could make it quit confusing.
