### ISSUE TITLE
Provide support for Servlet 5.0

### ISSUE THREAD

**Issue by chkal** [thymeleaf/thymeleaf#811]
Thymeleaf depends on the Servlet API 2.5 at the moment. Servlet 5.0, which will be part of the Jakarta EE 9 release, migrated the `javax.*` to the new `jakarta.*` package namespace. It would be great to see a Thymeleaf version that supports this new package namespace.

Are there any plans for this at the moment?

**Comment by danielfernandez** [comment]
This is a major breaking change, so there would no way to support e.g. dealing with `HttpServletRequest` objects both with the old and the new namespace. So any changes in this respect at Thymeleaf should be made in sync with major scenarios such as Spring Boot. See https://github.com/spring-projects/spring-boot/issues/16111

**Comment by chkal** [comment]
I agree that this is a major breaking change. And many Java libraries and frameworks have to deal with it in one or the other way. I just wanted to make sure that this issue is considered for the next major release.

**Comment by chkal** [comment]
BTW: spring-projects/spring-boot#16111 is actually just about switching to the official Jakarta EE 8 dependencies (which still use the `javax.*` packages and are compatible with Java EE8). My comment is more about the Jakarta EE 9, which introduces the package namespace update. Please note that Tomcat 10 for example will not support `javax.*` anymore.

**Comment by chkal** [comment]
Let me know if there is anything I can do to help with getting this done. Thymeleaf is the most popular third party view engine for Jakarta MVC. So it would be great if we could ship it as part of the upcoming 2.0 release.

**Comment by federicoromeo** [comment]
@danielfernandez 
In the new version jakarta, is thymeleaf supported? 
If yes, can someone send me the maven dependencie for an intellij Idea project?

**Comment by chkal** [comment]
@federicoromeo I'm not sure if I fully understand your question. Thymeleaf supports Jakarta EE 8 (which is essentially the same as Java EE 8). But Jakarta EE 9, which has just been released a few days ago, is not supported yet.

**Comment by federicoromeo** [comment]
@chkal  Sorry for the wrong nomenclature. I am developing a WebProfile Intellij Idea project, with Java EE 8 (Jakarta EE 8), but i'm facing an issue on resolving the Thymeleaf dependency using that technology, since some methods are expecting "javax. ...".

**Comment by federicoromeo** [comment]
@chkal  Sorry for the wrong nomenclature. I am developing a WebProfile Intellij Idea project, with Java EE 8 (Jakarta EE 8), but i'm facing an issue on resolving the Thymeleaf dependency using that technology, since some methods are expecting "javax. ...".
So what dependency should i use? On MVNrepository of thymeleaf (https://mvnrepository.com/artifact/org.thymeleaf.extras/thymeleaf-extras-java8time) i found this one from Thymeleaf Extras Java8time (in addition the another nomal one from org.thymeleaf):


`<dependency>
    <groupId>org.thymeleaf.extras</groupId>
    <artifactId>thymeleaf-extras-java8time</artifactId>
    <version>3.0.4.RELEASE</version>
</dependency>`

example of error that i'm getting:

`ServletContext servletContext = getServletContext();                                                         
ServletContextTemplateResolver templateResolver = new ServletContextTemplateResolver(servletContext);`

using jakarta the first method would return a jakarta.servlet.servletcontext, while the second is expecting a javax.servlet.servletcontext

**Comment by chkal** [comment]
The current version of Thymeleaf should work fine with Jave/Jakarta EE 8. I guess your problem is caused by something else. Perhaps you should file a new issue and include all the information you have. Including the exact error message. Thanks.

**Comment by federicoromeo** [comment]
All right, i'm doing it, thanks!

**Comment by wilkinsona** [comment]
Just FYI, work has now begun in earnest on Spring Framework 6 where the switch to Jakarta EE 9 dependencies [has been made](https://github.com/spring-projects/spring-framework/commit/d84ca2ba90d27a7c63d7b35a6259b5b9cf341118). Spring Boot will follow suit in due course. As things stand we will remove support for auto-configuring Thymeleaf. Hopefully this will only be a temporary situation. If there's anything that we can do to help with producing Servlet 5-compatible Thymeleaf binaries, please let us know.

**Comment by danielfernandez** [comment]
Understood, thanks @wilkinsona

**Comment by wilkinsona** [comment]
Hi, @danielfernandez. Just to let you know that Spring Boot 3.0 snapshots are now available. As described above, we've removed Thymeleaf support. We'd love for this to be a temporary situation so please do let us know if there's anything at all that we can do to help with Jakarta EE 9 and Spring Framework 6 compatibility.

**Comment by danielfernandez** [comment]
Please note this is now in progress. First snapshots of `3.1.0-SNAPSHOT` are already published, but note thorough testing is still ongoing.

Test applications "GTVG" in repo `thymeleafexamples-gtvg` [`3.1-master-javax`,`3.1-master-jakarta`] and "STSM" in repo `thymeleafexamples-stsm` [`3.1-spring5`,`3.1-spring6`] have already been adapted and tested to work with the new snapshots.

Thymeleaf 3.1 will provide support for both `javax.*` and `jakarta.*` namespaces, and also integration with Spring 5 and Spring 6. Java minimum version has been raised to JDK 8 except for the `thymeleaf-spring6` module which requires JDK 17 per Spring 6 requirement.

**Comment by wilkinsona** [comment]
That's great news. Thanks very much, @danielfernandez. I'll experiment a bit with the Thymeleaf 3.1 snapshots and Boot 3.0's snapshots and let you know how it goes.

**Comment by wilkinsona** [comment]
Thanks again, @danielfernandez. Things are looking good from Spring Boot's perspective with 3.1.0-SNAPSHOT. The one notable change that I've had to make is to remove support for the Spring Security dialect. Other than that, we appear to have parity with Thymeleaf 3 and Servlet 4.

**Comment by danielfernandez** [comment]
Thank you @wilkinsona. Spring Security support will happen very soon, @rwinch is helping a lot with that — as he's also been doing with Jakarta EE and Spring 6 support.

**Comment by danielfernandez** [comment]
The first milestone of Thymeleaf 3.1.0 has just been released.

The following artifacts have been published to Maven Central:

   * `org.thymeleaf`:`thymeleaf`:`3.1.0.M1`
   * `org.thymeleaf`:`thymeleaf-spring5`:`3.1.0.M1`
   * `org.thymeleaf`:`thymeleaf-spring6`:`3.1.0.M1`
   * `org.thymeleaf.extras`:`thymeleaf-extras-springsecurity5`:`3.1.0.M1`
   * `org.thymeleaf.extras`:`thymeleaf-extras-springsecurity6`:`3.1.0.M1`
   * `org.thymeleaf`:`thymeleaf-testing`:`3.1.0.M1`
   * `org.thymeleaf`:`thymeleaf-testing-spring5`:`3.1.0.M1`
   * `org.thymeleaf`:`thymeleaf-testing-spring6`:`3.1.0.M1`

In Spring-based applications, Spring structures (e.g. `ThymeleafView`) should hide most/all of the complexity of the switch to the new version. Non-Spring-based applications will need a couple of adaptations in order to work with the new abstraction structures that allow Thymeleaf to work in several web environments (`javax` Servlets, `jakarta` Servlets, Spring WebFlux). Release notes will be published later today explaining the relevant changes.

Example applications (`thymeleafexamples-*`) are also being updated to the new version and new structures by creating new branches for them. e.g. `3.1-master`, `3.1-master-jakarta`, `3.1-master-spring6`…

**Comment by wilkinsona** [comment]
Thanks very much, @danielfernandez. I've reinstated Thymeleaf support in Spring Boot's main branch and it'll be part of this week's 3.0.0-M1 release.

**Comment by danielfernandez** [comment]
That sounds awesome. Thanks @wilkinsona.
