### ISSUE TITLE
Comments in HTML (<!-- [[${xxx}]] -->) causr "Could not parse as expression" 

### ISSUE THREAD

**Issue by linearizability** [thymeleaf/thymeleaf#838]
## Sorry, my english is not very good, so I use pictures to show 

~~~markdown
OS: Windows 10 Home
IDE: IDEA 2020.3.4 (Ultimate Edition)
JDK: java version "1.8.0_291"(Oracle JDK)
SpringBoot: 2.5.1
thymeleaf: 2.5.1
~~~

![0](https://user-images.githubusercontent.com/59158756/122766171-cf225c00-d2d3-11eb-8f15-96ba1b8daaef.png)
![1](https://user-images.githubusercontent.com/59158756/122766182-d2b5e300-d2d3-11eb-8fd5-75ebac359773.png)
![2](https://user-images.githubusercontent.com/59158756/122766190-d47fa680-d2d3-11eb-97f1-91a65c6fbf0b.png)
![3](https://user-images.githubusercontent.com/59158756/122766214-da758780-d2d3-11eb-8678-1325993aeb64.png)
![4](https://user-images.githubusercontent.com/59158756/122766223-dd707800-d2d3-11eb-9e88-82482ced2e35.png)
![5](https://user-images.githubusercontent.com/59158756/122766235-e06b6880-d2d3-11eb-9424-710f0bc7e74c.png)
![6](https://user-images.githubusercontent.com/59158756/122766242-e2cdc280-d2d3-11eb-9fc5-dfe4ef660899.png)
![7](https://user-images.githubusercontent.com/59158756/122766255-e5301c80-d2d3-11eb-9367-63f6c3645225.png)
![8](https://user-images.githubusercontent.com/59158756/122766259-e82b0d00-d2d3-11eb-86d2-fea20636e10d.png)
![9](https://user-images.githubusercontent.com/59158756/122766264-ea8d6700-d2d3-11eb-9ab9-9125ba2ebf30.png)
![10](https://user-images.githubusercontent.com/59158756/122766276-ecefc100-d2d3-11eb-9e83-5864b06d8943.png)
![11](https://user-images.githubusercontent.com/59158756/122766285-eeb98480-d2d3-11eb-8350-58866ba18fa0.png)
![12](https://user-images.githubusercontent.com/59158756/122766300-f11bde80-d2d3-11eb-983b-775e79aa3da1.png)
![13](https://user-images.githubusercontent.com/59158756/122766315-f416cf00-d2d3-11eb-87e4-0180b267e579.png)
![14](https://user-images.githubusercontent.com/59158756/122766325-f711bf80-d2d3-11eb-8e29-de06ef0548d1.png)
![15](https://user-images.githubusercontent.com/59158756/122766329-f8db8300-d2d3-11eb-8b21-20a646d0d614.png)

**Comment by ultraq** [comment]
Hi there 👋  It looks like you've encountered a special feature of Thymeleaf called expression inlining, and it's a feature that lets you create expressions (`${...}`) inside text blocks by using `[[` `]]` brackets.  The feature is described in the docs here: https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#inlining

By having `[[${xxx}}]]`, Thymeleaf saw the `[[...]]`, so thought to try turn the inside into an expression.  The inside is `${xxx}}`, but because of that extra `}` bracket there was an error turning that into an expression.

The Disabling inlining part of the docs (https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#disabling-inlining) describes how to disable this feature, which is by adding `th:inline="none"` to some outer HTML element.  In your case, that can be the `<body>` element.

**Comment by trinhnx** [comment]
Yes, as below comment, you can disable inline to hint Thymeleaf avoid evaluating those expressions in comment sections
