### ISSUE TITLE
Should be a able to get the first value from request parameter's values without the bracket syntax?

### ISSUE THREAD

**Issue by hussachai** [thymeleaf/thymeleaf#85]
From this thread: http://forum.thymeleaf.org/Request-parameter-td3325136.html#none
I understand your point but it's not convenient to use that way. 
Is it possible to do this? If the parser doesn't find a bracket, it will do the null check 
and retrieve the first parameter from parameter values. If you implement this it will
save a lot of typing and make code cleaner.

``` HTML
My current link:
<a th:href="@{/admin/user/user}+'?sort=status&amp;order='+${param.order!=null and param.order[0]=='asc'?'desc':'asc'}" th:class="${param.sort!=null and param.sort[0]=='status'?param.order[0]:''}" th:text="#{column.status}">Status</a>

It will be better to look like this
<a th:href="@{/admin/user/user}+'?sort=status&amp;order='+${param.order=='asc'?'desc':'asc'}" th:class="${param.sort=='status'?param.order:''}" th:text="#{column.status}">Status</a>
```

Thank you very much. You're making java fun again.

**Comment by ffesseler** [comment]
yes agree, would be great!

**Comment by danielfernandez** [comment]
Thymeleaf 3.0's use of the request parameters has changed so that now it is possible to output a single-valued parameter like:

```
${param.something}
```

Instead of being forced to write (which is still valid):

```
${param.something[0]}
```

However, note that this is achieved by means of returning `something` as a custom implementation of `java.util.List` that will be accessible through index just like an array, and will output the first value of the list when its `toString()` method is called.

Note that this means that an expression such as:

```
${param.order == 'asc'}
```

...will still fail, because we would be trying to compare a `List` with a `String`. For such cases, we would still need to do one of the following:

```
${param.order.toString() == 'asc'}
${param.order[0] == 'asc'}
```

**Comment by danielfernandez** [comment]
This is in `3.0.0-SNAPSHOT` already

**Comment by hussachai** [comment]
I think that it would be better to add method like .first() instead of overriding toString()
Because sometimes if we want to see parameters for debugging purpose, the default List.toString() is quite useful.
The .first() method is supposed to return either null or the first element of List and I think its name is more correct than .toString() in term of semantic.

What do you think?

**Comment by danielfernandez** [comment]
I don't see a difference between the `param.something.first()` you describe and simply using indexed access like `param.something[0]`, which was valid until now and will continue to be.

Overriding `toString()` is perfectly fine for debugging also, because it will always return the data inside. The only real difference is that, when there's only one element, there will be no `[....]` brackets around the result.

**Comment by hussachai** [comment]
Sweet! I misunderstood I thought toString() will return only the first element.
Now I'm perfectly clear what you said. Thanks a lot.
