### ISSUE TITLE
execute thymeleaf from project directory

### ISSUE THREAD

**Issue by adrianodanduino** [thymeleaf/thymeleaf#854]
I created a library which, in combination with thymeleaf (without spring), deals with sending e-mails.
I add this library to my project dependencies and there is a problem - the library does not use the html template from the project's "resources / templates",it uses template from library resources.
How can this be changed? Do you have a sample solution?
I want this library to take html template for email from resources/templates of project that is using this library.
I tried with setting prefix to ClassLoaderTemplateResolver - every version of file:src/main/resources/templates/ and classpath:src/main/resources/templates/ and so on, and so on.
Which template resolver I should use and how to set it proper? Ty in advance for help!

**Comment by danielfernandez** [comment]
The `resources/templates` folder is only the default folder for Thymeleaf web HTML templates in Spring Boot applications, per Spring Boot (auto)configuration.

If you want to load your templates from your `src/main/resources/templates/` folder you can use `ClassLoaderTemplateResolver` as long as you make sure that your `src/main/resources` folder ends up being the root of your class loader path, as it usually is. In such case, you would need to refer to your templates with `/templates/mytemplate.html`, because that will be the path to your template in runtime (all that `src/main...` is only the path in your source code).
