### ISSUE TITLE
Spring MVC: Should error message be looked up from IMessageResolver instead of MessageSource?

### ISSUE THREAD

**Issue by hussachai** [thymeleaf/thymeleaf#86]
I don't like the Spring MessageSource because it's designed to be a big centralized message.
I have to namespace every message and that make my message key longer and longer.

I like the idea of StandardMessageResolver that Thymeleaf provides. Instead of namespace
the message key, StandardMessageResolver namespace the cache key instead. It's very convenient. IMO the performance should be better.

It seems like the Spring form is integrated well with Thymeleaf but the message.

``` java
public void doSomething(User user, BindingResult result){
    result.rejectValue("username", "error.exists");
}
```

and

``` html
<span class="error" th:if="${#fields.hasErrors('username')}" th:errors="*{username}"></span>
```

The error.exists message key resides in user.properties accompanying with user.html
My error message "Username is already in use!" should be rendered but the org.springframework.context.NoSuchMessageException throw up instead.

Do you think that Thymeleaf should look up the message from IMessageResolver instead of MessageSource? 

Thank you,
Hussachai

**Comment by danielfernandez** [comment]
Hi,

I'm not sure I understand the problem you are describing here...

When Thymeleaf is used along with Spring by using a `SpringTemplateEngine` instance, several things get preconfigured: 1. The _SpringStandard_ dialect is used, and 2. A `SpringMessageResolver` instance is used.

`SpringMessageResolver` is an implementation of `IMessageResolver` that, in order to have a better integration with the rest of the Spring architecture, delegates all requests to the underlying Spring `MessageSource` instances. That's why Thymeleaf resolves messages using the MessageSource.

If you don't want to use Spring's MessageSource, then you should not use `SpringMessageResolver`, and instead use any other implementation of `IMessageResolver` like the standard one. The problem would be that Spring's core does not know about thymeleaf, so things like form error messages will continue to be resolved from Spring's `MessageSource`.

How to solve this? You could create a `MessageSource` implementation that delegates to Thymeleaf's `StandardMessageResolver`... but I don't know if such thing would be really possible.

Regards,
Daniel.

**Comment by hussachai** [comment]
Thank you for your response. I got your point. As I remember, I configured Thymeleaf to use StandardMessageResolver
and it worked well when I use #{messageCode} but with the Spring MVC form's error. It did not resolve the message from StandardMessageResolver but it used default Spring MessageSource instead.

I use "errors" attribute in Thymeleaf namespace to display the error but it caused the error instead.
It seems like org.thymeleaf.spring3.processor.attr.SpringErrorsAttrProcessor uses MessageSource instead of IMessageResolver that I've configured.

Your solution would work if I create custom MessageSource that delegate to StandardMessageResolver
but I think it requires a lot of hacks because resolveMessage method in IMessageResolver needs object of org.thymeleaf.Arguments as the first parameter. That class has a lot of dependencies.
I think I can do that but I don't like hacking because it will not guarantee to work with the future version of Thymeleaf.

Here's part of stacktrace.

``` java
...
org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'org.thymeleaf.spring3.processor.attr.SpringErrorsAttrProcessor' (/admin/localisation/countryForm:39)
    org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:223)
    org.thymeleaf.dom.Node.applyNextProcessor(Node.java:897)
    org.thymeleaf.dom.Node.processNode(Node.java:858)
    org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    ...
org.springframework.context.NoSuchMessageException: No message found under code 'code.notExist.country.isoCode2' for locale 'en'.
    org.springframework.context.support.DelegatingMessageSource.getMessage(DelegatingMessageSource.java:79)
    org.springframework.context.support.DelegatingMessageSource.getMessage(DelegatingMessageSource.java:71)
    org.springframework.context.support.AbstractApplicationContext.getMessage(AbstractApplicationContext.java:1214)
    org.springframework.web.servlet.support.RequestContext.getMessage(RequestContext.java:571)
    org.springframework.web.servlet.support.BindStatus.initErrorMessages(BindStatus.java:177)
    org.springframework.web.servlet.support.BindStatus.getErrorMessages(BindStatus.java:273)
    org.thymeleaf.spring3.processor.attr.SpringErrorsAttrProcessor.processAttribute(SpringErrorsAttrProcessor.java:86)
    org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:74)
    org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
    ....

```

**Comment by danielfernandez** [comment]
Actually, after examining more parts of the Spring integration code, it does not seem feasible to use a message resolution mechanism different than Spring's when Spring is used. There is just too much code that needs the `MessageSource` related to Spring's form binding.

So I'm afraid the only realistic way to use a different message resolution mechanism in a Spring application is creating a `MessageSource` implementation. I'm therefore closing this ticket.
