### ISSUE TITLE
Exception evaluating OGNL expression: "#request.requestURI"

### ISSUE THREAD

**Issue by kamenik** [thymeleaf/thymeleaf#883]
Hello,

I am trying to use Thymeleaf 3.1.0-snapshot because of jakarta namespace support and it crashes at this simple code:

`
<th:block th:if="${#request.requestURI} == '/for/somebody'">
`

with root exception

`
Caused by: ognl.OgnlException: source is null for getProperty(null, "requestURI")
`

I just replaced original

`
templateEngine.process(template, new WebContext(request, response, request.getServletContext()), response.getWriter());
`

with 

`
var exchange = JakartaServletWebApplication.buildApplication(getServletContext()).buildExchange(request, response);
templateEngine.process(template, new WebContext(exchange), response.getWriter());
`

**Comment by danielfernandez** [comment]
The `#request`, `#response`, `#session` and `#servletContext` expression utility objects have been removed in Thymeleaf 3.1.0 for both security reasons and web-technology agnosticism (#886). They can still be manually added if necessary, but their direct use from templates is not recommended by default.

However, there was an issue in the explanatory error message that this usage should have caused, which has now been fixed by means of #887.
