### ISSUE TITLE
HTML result is different than expected.

### ISSUE THREAD

**Issue by rjeeb** [thymeleaf/thymeleaf#894]
I have a case where I write this html
```
<div>
	<a>
		<ul>
			<li><a href="/test">test</a></li>
			<li><a href="/test2">test2</a></li>
		</ul>
	</a>
</div>
```
and after run the page on the browser, the result html is as follows
```
<div>
	<a></a>
	<ul>
		<a></a>
		<li><a></a><a href="/test">test</a></li>
		<li><a href="/test2">test2</a></li>
	</ul>
</div>
```
not sure why the result is different than what I expect.

> I'm using 3.0.15.RELEASE

**Comment by duoduobingbing** [comment]
This issue is not caused by Thymeleaf.

To test this: Create a plain HTML file and write
```
<!DOCTPYE HTML>
<html>
<head></head>
<body>
<div>
	<a>
		<ul>
			<li><a href="/test">test</a></li>
			<li><a href="/test2">test2</a></li>
		</ul>
	</a>
</div>
</body>
</html>
```

to it and then open it with your browser and use "Inspect Element". You will see that the browser transformed the structure to 
```
<div>
	<a></a>
	<ul>
		<a></a>
		<li><a></a><a href="/test">test</a></li>
		<li><a href="/test2">test2</a></li>
	</ul>
</div>
```

This is because you can not have an `a` element inside of an `a` element as per HTML specification. The browser attempts to correct the erroneous HTML resulting in the output that you have got.
