### ISSUE TITLE
Thymeleaf 3.1.0 refers to milestone Spring dependencies

### ISSUE THREAD

**Issue by bclozel** [thymeleaf/thymeleaf#932]
Thymeleaf 3.1.0.RELEASE has been published to Maven Central, but [its parent POM](https://repo.maven.apache.org/maven2/org/thymeleaf/thymeleaf-parent/3.1.0.RELEASE/thymeleaf-parent-3.1.0.RELEASE.pom) still refers to non-GA versions of Spring projects. See: https://github.com/thymeleaf/thymeleaf/blob/eac55ee4ab20878c5289b3ad1e99dec9c07d3e20/pom.xml#L147-L149

Could you please release a maintenance version with GA versions for those artifacts?

**Comment by danielfernandez** [comment]
Sure, 3.1.1 is actually already being tested, and the Spring Security one is already changed in master. See https://github.com/thymeleaf/thymeleaf/blob/37fc3318a6a492a060bdee38f9cf22fe0f0b6e88/pom.xml#L147

But... is there a release for Spring Webflow 3.0.0? Support for it was requested in #900, but I cannot find it [here](https://repo1.maven.org/maven2/org/springframework/webflow/spring-webflow/). Perhaps it's somewhere else?

**Comment by wilkinsona** [comment]
@rstoyanchev will be able to help with WebFlow 3.0.0.

Unlike the reference to `spring-security-bom`, the dependency management for WebFlow isn't causing a problem. That's because `spring-security-bom` is used as an import, requiring consumers to resolve the bom so that they have a complete view of Thymeleaf's pom. In other words, from a consumer's perspective, I think https://github.com/thymeleaf/thymeleaf/commit/e15902db510050a2f02ba2528738f33c98f1cf50 has already taken care of this.

**Comment by danielfernandez** [comment]
So just to confirm: releasing Thymeleaf 3.1.1 with a dependency on Spring Security 6.0.0 and Spring Webflow 3.0.0-M1 would be OK for you? If so, that is a matter of minutes as the staging repo for 3.1.1 is already closed in Sonatype since yesterday.

**Comment by wilkinsona** [comment]
Yeah, that's fine. The WebFlow dependency won't affect anyone as it's marked as provided anyway. Please don't rush on our account though. We've worked around the problem for Spring Boot 3.0.0. We'll pick up Thymeleaf 3.1.1 when it's available.
