### ISSUE TITLE
th:replace by POST response view

### ISSUE THREAD

**Issue by kelvinchiew** [thymeleaf/thymeleaf#988]
I would suggest to have th:replace support POST response view. 

**index.xml**

- fragmenr replace by POST response from server. 

```
<div th:replace="@{~/menu}"></div>
```

**menu.xml** 

- contain Spring Modal attribute menuList for further process

```
<div xmlns:th="http://www.thymeleaf.org">
    <script th:inline="javascript">
        $(document).ready(() => {
            var menuList = /*[[${menuList}]]*/ null;
            console.log(menuList);
            if(null != menuList){
                // some logic to populate menu
            }
        })
    </script>
    <div id="menu"></div>
</div>
```

**MenuController.java**

- POST response to set menuList model attribute

```
@RequestMapping(value = "/menu", method = RequestMethod.POST)
    public String menu(HttpServletRequest httpServletRequest, Model model) {
        logger.debug("menu controller");
        List<Menu> menuList = null;
        Object object = httpServletRequest.getServletContext().getAttribute(SESSION_NAME_MENU);

        if(Objects.nonNull(object)){
            try{
                menuList = (List<Menu>) object;
            } catch (Exception e){}
        }

        if(Objects.isNull(menuList)){
            Menu home = new Menu();
            home.setId(1L);
            home.setTitle("Home");
            home.setUrl("home.html");
            menuList.add(home);

            // ... more menu
        }

        model.addAttribute("menuList", menuList);
        return "layout/menu";
    }
```

**Comment by jmiguelsamper** [comment]
Hello Kelvin,

Thanks for your suggestion. Thymeleaf is a server-side template engine and, as such, its goal is to produce output by composing the server-side resources instead of doing AJAX calls to render the final content.

Compositing pages using AJAX calls is already done by many Javascript frameworks that do their job very well.

On the other hand, please note that using POST requests to get view content is not a good practice and against the HTTP specification at https://datatracker.ietf.org/doc/html/rfc2616 
If you want to get view content, you should always do a GET request, POST is reserved for data modification.

Thanks anyway for your suggestions.
